### PR TITLE
Improved Tmdb/Tvdb database access.

### PR DESCRIPTION
**Pull request by wagnered**
Added MPAA Certification and TV content rating.
Added Movie/TV show search.
Added import of TV show art from mp4/quicktime files.
Updated Tmdb module and added new Tmdb dependency modules.
Updated config file and update.class.php to version 30.
Updated database to 380000.

Had to re-arrange some module sub-folders because none of Ampache's autoloaders could handle the composer/psr-4 specifiations.

### CODE REVIEW

**Comment by Afterster** [comment]
Thanks, I really mean it.
But I don't think this is yet ready :)
On a first review:
 1. parseFileName function code redondency on TMDB / TVDB modules
 2. Looks ok for Psr, Reactn Symfony Tmdb modules, but Guzzle looks wrong. We're already using Guzzle but on a previous version, can't we consolidate Guzzle dependency into one version only? Also, it looks like you added several subproject to GuzzleHttp module whereas the official release doesn't have so much files. Did I miss something or could you details? Thanks

**Comment by wagnered** [comment]
For GuzzleHttp:

    That is the way the revised version is set up.  So the
sub-components could be added as needed: which the Tmdb api does
require.  I used Composer to down-load the projects into a separate
vendor folder then copied the relevant (sub)components to the Ampache
modules folder. The problem is that some of the sub-projects have their
own dependencies.

    I stepped through the code using Eclipse to be able to re-organize
the new module folders to accommodate Amphache's autoloader, so I saw
every class that was called by The Tmdb api and its sub-components they
were dependent on. There were several optional components, such as
Monolog, that I did not install as I didn't think there would be a need
for a log at that level.

    I thought about the existing deprecated Guzzle that Ampache is
using, but I also thought that the complete changeover might be done in
steps to keep the scope of a PR focused on one or two related goals.

    I'll take a look as to what it will take to move existing code to
use GuzzleHttp/Guzzle.  Hopefully, It won't take much more than
pre-pending the base class \GuzzleHttp to all script that references
Guzzle. That is, hope there won't be any deprecated functions that have
to be changed to alternate functions in the updated class. that would
definitely obfuscate the purpose of the original PR. 

For parseFfileName:

    I thought that because the function in tmdb.plugin.php additionally
parses movie names, it was sufficiently different from the one that is
in tvdb.plugin.php.  

    Also, I thought that since accessing the Tmdb database is quite
slow(it takes over 40 minutes to finish 100 mp4s) loading another class
to process the file name each time would significantly and
unnecessarily, slow the catalog processing. 

    I thought I already checked that Vainfo might already be
instantiated: I thought not but I'll check again. If it is, I'll place
it in that class to be accessed by both Tmdb and Tvdb.

That's my rational for "doing it my way". ( ; ' >


-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----From: Afterster <notifications@github.com>
Reply-to: ampache/ampache <reply
+005d506eafebc33d92a67ec7f293318ae64b1a5dd3c8aa8c92cf00000001117da34a92a169ce04d4efc7@reply.github.com>
To: ampache/ampache <ampache@noreply.github.com>
Cc: Ernest Wagner <wagnered@comcast.net>
Subject: Re: [ampache] Improved Tmdb/Tvdb database access. (#868)
Date: Wed, 27 May 2015 08:22:50 -0700



Thanks, I really mean it.
But I don't think this is yet ready :)
On a first review:

     1. parseFileName function code redondency on TMDB / TVDB modules
     2. Looks ok for Psr, Reactn Symfony Tmdb modules, but Guzzle looks
        wrong. We're already using Guzzle but on a previous version,
        can't we consolidate Guzzle dependency into one version only?
        Also, it looks like you added several subproject to GuzzleHttp
        module whereas the official release doesn't have so much files.
        Did I miss something or could you details? Thanks

**Comment by wagnered** [comment]
@Afterster,

I just did a grep of my Ampache directory tree (excluding modules/) and did not find any references to the Guzzle class in any of the files.  Am I missing  something?

**Comment by wagnered** [comment]
I was sorta correct in my memory. Vainfo is instantianted( it's what calls AmpacheTmdb class), but is not available to AmpacheTmdb without a new object being created.

Where do you  suggest i put the parseFileName function so both Tmdb and Tvdb plugins can access it?
I got it! How about adding it to Vainfo as a public static function. That way it wouldn't need to be instantiated and would be located where all the other parse routines are located?

**Comment by Afterster** [comment]
Mhh ok... dependency management is really needed to avoid to ask ourself this kind of question... because here I cannot answer myself about Guzzle current use, at least on a short view... But that's another issue as you know :) Ok for doing that later.
Looks ok to move the parse function in Vainfo as static.

I will review your PR in details this week end. Thanks again.

**Comment by wagnered** [comment]
Luck abounds...

I just finished a grep of each module and only the musicbrainz module
accesses the modules/Guzzle component and only in one file.

I'm not sure what musicbrainz is, but I'll explore it and test out the
change to \GuzzleHttp\Guzzle.  }: ' }


-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----From: Afterster <notifications@github.com>
Reply-to: ampache/ampache <reply
+005d506ece974d96f5de09eded4d9ee3a3bf3ab071f232a292cf00000001117dff2a92a169ce04d4efc7@reply.github.com>
To: ampache/ampache <ampache@noreply.github.com>
Cc: Ernest Wagner <wagnered@comcast.net>
Subject: Re: [ampache] Improved Tmdb/Tvdb database access. (#868)
Date: Wed, 27 May 2015 14:54:50 -0700



Mhh ok... dependency management is really needed to avoid to ask ourself
this kind of question... because here I cannot answer myself about
Guzzle current use, at least on a short view... But that's another issue
as you know :) Ok for doing that later.
Looks ok to move the parse function in Vainfo as static.

I will review your PR in details this week end. Thanks again.

**Comment by Afterster** [comment]
More detailed review:

 - On /templates:
  - Why did you removed childs tags overwrite options on TVShow?
  - On all display and edition pages, you should avoid specific video type test (`if ($video_type != 'tvshow_episode')` ...), there is a *_partial_* logic in place to avoid this. Put specific fields in correct *_partial_* views
  - You completely removed original name, and now title edition from the video base edition. This makes personal video title uneditable. Please test Personal Videos too.
  - Could you remind me the reason to remove Prefix split from the name?

 - On /lib/class:
  - You added new fields on tables but didn't updated the corresponding movies/tvshow_episode classes with these new field members

**Comment by wagnered** [comment]
@Afterster,


1.  Except as used in Ampache, the word "Tag" is a generic term that
describes meta-data that is inserted into a file. Only Ampache refers to
"Genre" as "Tags".  When I was checking the edit dialog, I was thinking
in terms of "content-rating" which by universal definition is a "Tag".
And of course content-rating is only stored in the tvshow table.
 ; ' >

2. I guess I thought that "content-rating" is more relevant to the TV
show description than is year, or any physical property that is
displayed in the "partial..." views.  (I thought it was important enough
to work on the PR myself and get it done. ;'> ) Actually I would like to
see the ability to re-arrange the order of the displayed meta-data,
which might be much easier to accomplish in an M-V-C model.


3, Yes, I did forget to check how far the changes to title/original_name
would affect the whole application.  I will check "Personal Videos" and,
I guess, "Music Clips". I do/did realize that "original_name" even
though now independent of the title, still needs capability to be
edited.

4. "prefix split" thing: For some reason, I thought that sorting of TV
shows should be treated differently from movies. I assume that this the
only reason for the split anyway.

5. On "/lib/class" I'm not sure I have and excuse {;'> .


Thanks,


-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----From: Afterster <notifications@github.com>
Reply-to: ampache/ampache <reply
+005d506e07472c39b825bf60d44e5c60c43f8c0317cc760092cf000000011181dd5892a169ce04d4efc7@reply.github.com>
To: ampache/ampache <ampache@noreply.github.com>
Cc: Ernest Wagner <wagnered@comcast.net>
Subject: Re: [ampache] Improved Tmdb/Tvdb database access. (#868)
Date: Sat, 30 May 2015 13:19:36 -0700



More detailed review:

      * On /templates:
        
              * Why did you removed childs tags overwrite options on
                TVShow?
              * On all display and edition pages, you should avoid
                specific video type test (if ($video_type !=
                'tvshow_episode') ...), there is a partial logic in
                place to avoid this. Put specific fields in correct
                partial views
              * You completely removed original name, and now title
                edition from the video base edition. This makes personal
                video title uneditable. Please test Personal Videos too.
              * Could you remind me the reason to remove Prefix split
                from the name?
      * On /lib/class:
        
              * You added new fields on tables but didn't updated the
                corresponding movies/tvshow_episode classes with these
                new field members

**Comment by wagnered** [comment]
Oh yea, as for the first point, I guess I didn't understand what
"sub-episode" meant.  In my mind each TV show ha episodes, not
sub-episodes. In my mind and KODI specs, "sub-episodes" refer to "part
1, part 2[, part n] of each episode. And the ampache tables aren't set
up to differentiate.

-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----From: Afterster <notifications@github.com>
Reply-to: ampache/ampache <reply
+005d506e07472c39b825bf60d44e5c60c43f8c0317cc760092cf000000011181dd5892a169ce04d4efc7@reply.github.com>
To: ampache/ampache <ampache@noreply.github.com>
Cc: Ernest Wagner <wagnered@comcast.net>
Subject: Re: [ampache] Improved Tmdb/Tvdb database access. (#868)
Date: Sat, 30 May 2015 13:19:36 -0700



More detailed review:

      * On /templates:
        
              * Why did you removed childs tags overwrite options on
                TVShow?
              * On all display and edition pages, you should avoid
                specific video type test (if ($video_type !=
                'tvshow_episode') ...), there is a partial logic in
                place to avoid this. Put specific fields in correct
                partial views
              * You completely removed original name, and now title
                edition from the video base edition. This makes personal
                video title uneditable. Please test Personal Videos too.
              * Could you remind me the reason to remove Prefix split
                from the name?
      * On /lib/class:
        
              * You added new fields on tables but didn't updated the
                corresponding movies/tvshow_episode classes with these
                new field members

**Comment by Afterster** [comment]
No problem and sorry for taking so much time to give feedbacks sometimes.
I'm not sure to get your point about the "sub-episode" thing, there is no such thing in ampache.

**Comment by wagnered** [comment]
Then I guess I don't understand why you asked: 
    "Why did you removed childs tags overwrite options on TVShow?"

I thought you were referring to the options:
   "Overwrite tags of sub episodes" and
   "Add tags to sub episodes"
on the tvshow edit dialog that exists pre-this PR.

I had only removed the $POST data for the options, not the actual logic.

If the options were meant to refer to tv show episodes, I'm not sure it's necessary because the various on-line databases associate the Genre only with the TV show and not the episodes.

And if that's not what you are referring to, then I'll await your further explanation.

**Comment by Afterster** [comment]
Yes it's what I mean, I didn't noticed it was named "sub episode"...
We should keep this logic even on tvshow and even if online database doesn't provide this kind of relation. To make it consistent with other Ampache features.

**Comment by wagnered** [comment]
While I'm working with the dialog, should I replace "sub episode" on the
dialog to just "episode" for both options?

-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----From: Afterster <notifications@github.com>
Reply-to: ampache/ampache <reply
+005d506ea76d88dec97bda7aacd0c7b5a0471b529084023f92cf000000011183ad5b92a169ce04d4efc7@reply.github.com>
To: ampache/ampache <ampache@noreply.github.com>
Cc: Ernest Wagner <wagnered@comcast.net>
Subject: Re: [ampache] Improved Tmdb/Tvdb database access. (#868)
Date: Sun, 31 May 2015 22:19:23 -0700



Yes it's what I mean, I didn't noticed it was named "sub episode"...
We should keep this logic even on tvshow and even if online database
doesn't provide this kind of relation. To make it consistent with other
Ampache features.

**Comment by Afterster** [comment]
Yes, ok for "episode" label :)

**Comment by wagnered** [comment]
@Afterster,

You haven't commented on my reason for removing the split column in the
TVshow/movie tables, but here is further explanation:

I double checked the sort logic for movies and TV shows and the logic
indicates that movies are sorted on video.title, which isn't split: Why
have the split in movie titles if the sort isn't dependent on the split
movie title?

 But TV shows were sorted on tvshow.name, which was split. I don't
understand why sorting of movies was treated differently from the sorting
of TV shows.

So, should I revert the movie/tvshow tables to the way they were before my PR?

-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----From: Afterster <notifications@github.com>
Reply-to: ampache/ampache <reply
+005d506e07472c39b825bf60d44e5c60c43f8c0317cc760092cf000000011181dd5892a169ce04d4efc7@reply.github.com>
To: ampache/ampache <ampache@noreply.github.com>
Cc: Ernest Wagner <wagnered@comcast.net>
Subject: Re: [ampache] Improved Tmdb/Tvdb database access. (#868)
Date: Sat, 30 May 2015 13:19:36 -0700



More detailed review:

      * On /templates:
        
              * Why did you removed childs tags overwrite options on
                TVShow?
              * On all display and edition pages, you should avoid
                specific video type test (if ($video_type !=
                'tvshow_episode') ...), there is a partial logic in
                place to avoid this. Put specific fields in correct
                partial views
              * You completely removed original name, and now title
                edition from the video base edition. This makes personal
                video title uneditable. Please test Personal Videos too.
              * Could you remind me the reason to remove Prefix split
                from the name?
      * On /lib/class:
        
              * You added new fields on tables but didn't updated the
                corresponding movies/tvshow_episode classes with these
                new field members

—
Reply to this email directly or view it on GitHub.



-- 
73 From Ernie D

AA1AD | CN87ug

-- 
73 From Ernie D

AA1AD | CN87ug

**Comment by Afterster** [comment]
Mhh I think this was an issue. The correct behavior should be having movie title split too.

**Pull request closed without merging**
