### PR TITLE
add placeholder text to search box

### PR DESCRIPTION
**Pull request by brownl**
Another very minor aesthetic change, but I think it makes the purpose of the field a bit more obvious to new users.
Before:
Before
After:
After

### CODE REVIEW

**Comment by SUTJael** [comment]
Yes thanks but you need to think about other languages: ``<?php echo T_('Search...'); ?>``

**Comment by brownl** [comment]
oh, sorry, I completely forgot... I'll sort that out - what happens if the string hasn't been translated? does it just echo nothing?

**Comment by brownl** [comment]
I sorted it

**Comment by Afterster** [comment]
Thanks for your PR, merged ;)
If the string hasn't been translated, it echo the default string (=English).

**Pull request merged**
