### PR TITLE
General Translation update

### PR DESCRIPTION
**Pull request by Psy-Virus**
Fixed: plurals aren't recognized by `gather-messages.sh` since #1239
Translations and Translation catalog updated to the latest state and
plurals are readded to the POT.

### CODE REVIEW

**Comment by Phyks** [comment]
Closes #1329.

**Comment by Psy-Virus** [comment]
So if I had written that this PR closes this issue, it would be closed automatically, @Phyks ?
If so, is there a source, where such "commands" are listed? I don't know for what I should search. :-D

**Comment by Phyks** [comment]
Yes, see https://github.com/ampache/ampache/pull/1310 and associated issue. See https://help.github.com/articles/closing-issues-via-commit-messages/ for more infos on the syntax.

**Comment by Psy-Virus** [comment]
Oh cool, thanks! Around two years on github and didn't even think about that this keywords trigger an action. I always thought that it's only for the history or something. XDD

**Comment by Psy-Virus** [comment]
And it also doesn't work with an edit.

**Comment by Phyks** [comment]
=(

**Comment by Psy-Virus** [comment]
Oh.. ehm the text suggests, that the issue would be closed by merging the PR.^^

**Comment by Psy-Virus** [comment]
But I closed it already, so we won't see it... :-(

**Comment by Phyks** [comment]
^^

**Comment by Niols** [comment]
If needed, you can reopen the issue ^^ By the way, that wouldn't be a so bad idea since the fix didn't reach `develop` for now

**Comment by Psy-Virus** [comment]
Hehe sure. It's reopened. ^^

**Comment by Afterster** [comment]
Gotcha, thanks!

**Pull request merged**
