### PR TITLE
Transcoding not finishing process

### PR DESCRIPTION
**Pull request by nan4k7**

### CODE REVIEW

**Comment by Afterster** [comment]
Ok thanks, now it's better as a PR and simpler to review your changes :)
I have few questions now:
 - Why do you added a prefix to run in background? What was wrong with the previous solution
 - The manual process kill stuff you added shouldn't be done only on Windows? On linux we could use the regular `proc_terminate` function isn't it?

**Comment by nan4k7** [comment]
About the things you asked:
- The prefix is because of what it says here (http://php.net/manual/es/function.proc-get-status.php comment by Mark Seecof). When you don't use it, proceses are opened by sh and that leaves a child.

- The kill function is because of something similar (http://php.net/manual/es/function.proc-terminate.php) if you use proc_terminate there are chances of leaving a child (comments by  jerhee at ucsd dot edu and  v dot denegin at yahoo dot com)

**Comment by Afterster** [comment]
Interesting, thanks for the links (I will add them to source code comments when merging) and thanks for your work to resolve your issue.
I'm not a big fan to always send kill -9, maybe it could be an option that you enable depending your environment/transcode utility, what do you think?
Could some other people watching Ampache repo also try this fix and give feedbacks before the merge? Thanks!

**Comment by Afterster** [comment]
After several feedbacks (not here) and testing your fix really looks the best way to process.
Transcoding is an important feature, really helpful. I merged it, thanks again for your time and this fix.

**Pull request closed without merging**
