### PR TITLE
add search in lyrics

### PR DESCRIPTION
**Pull request by jleipsig**
Proposal for feature request #2414

### CODE REVIEW

**Comment by lachlan-00** [comment]
i should have something with tagged lyrics, testing now

**Comment by kuzi-moto** [comment]
This would be a great thing to add, I know it's been requested before. I haven't looked at the code for this yet, but would this work in just the advanced search, or also in the global search at the top of the page? 

Additionally, does the global search have a priority, such as showing matches first by Artist, then Album, then title, etc.? If it does, might be good to make sure lyrics have a lower priority.

**Comment by lachlan-00** [comment]
it's a text search so it would be possible to add.

global runs the search.php 
* the search from the header is hardcoded to 0/contains
* it looks at a glance that it only searches Artist, album, title

The results window loads if you search and lets you dig deeper

**Comment by lachlan-00** [comment]
If you search anywhere it does one search for each Artist, then album, then song then outputs the results.

the ajax/JS waits for 2 characters then executes the search each keypress.

I think it's fine keeping it in advanced_search as even just these like searches can be heavy

**Comment by lachlan-00** [comment]
@kuzi-moto  move into #2414 if you want, i've tested this out and the searches are working correctly.

i've also documented this in the wiki as well.

**Pull request merged**
