### PR TITLE
Add a permalink in the search form

### PR DESCRIPTION
**Pull request by fufroma**
This patch add a permalink, so people can bookmark a search or share it with a link.

### CODE REVIEW

**Comment by fufroma** [comment]
And yes, one can argue it's quite a dirty piece of code.

**Comment by lachlan-00** [comment]
that;s a pretty good idea. cause i do searches manually often for sanity checks

**Comment by lachlan-00** [comment]
composer cs:fix will sort you out here but i'm doing it now

**Comment by lachlan-00** [comment]
made some additional changes in 9abf7423f872b019e6a4cac228d6ecfeed1b2023 to allow post and request data checks and will only show the link button when you have run an search action

**Pull request merged**
