### PR TITLE
More translations (es_ES)

### PR DESCRIPTION
**Pull request by k3xr**
Added some Spanish translations

### CODE REVIEW

**Comment by Psy-Virus** [comment]
Hey @k3xr,

I've added a general translation update [PR](https://github.com/ampache/ampache/pull/1287), that also includes es_ES changes, updated translation catalog, no obsolete translations and so on.

So you can close this PR if you wish.

:-)

**Comment by Phyks** [comment]
@Psy-Virus Does your PR also covers the changes from this PR?

**Comment by Psy-Virus** [comment]
If they were made through Transifex (as recommended), yes.
If not, it could be a huge merging trouble, 'cause there wasn't any discussion about manual contributing in the Spain language Team or in general... But he is registered at Transifex and in the Spanish translation team. So I think his changes are included.

**Comment by Psy-Virus** [comment]
Okay, after some research, I'm not sure about it any more...

@k3xr, did you use the latest `.po` version from Transifex or did you use one from any Ampache Archive?
If you used the Transifex Version, this PR should be merged after mine or I'll merge it into mine.
If not, could you let us know what Ampache version you have used?

Thanks

:-)

**Comment by k3xr** [comment]
Don't worry, I'll translate again after your merge using Transifex. I used the latest .po version from the code for this PR.

**Comment by Afterster** [comment]
Thanks @k3xr 
@Psy-Virus as you manage translation for Ampache, could you confirm this can be merged or it should be closed and done through Transifex? Thank you.

**Comment by Psy-Virus** [comment]
@Afterster, I compared it against my version and I only see additions and formatting changes through the used editor. So it can safely be merged.

But @k3xr, for the future, please use Transifex. It's simply to much work to synchronize the Transifex and offline files, if translators are working on both sides at the same time.

The offline method is more a fail safe or backup solution, if it's not possible for someone to work with Transifex.

Thank you

:-)

**Comment by Afterster** [comment]
Ok thanks for the review @Psy-Virus and again for the translation @k3xr!

**Pull request closed without merging**
