### PR TITLE
Lessen rfc 3514

### PR DESCRIPTION
**Pull request by mitchray**
Removes the superfluous use of the [evil bit](https://en.wikipedia.org/wiki/Evil_bit), keeping just one unobtrusive reference in the [header](https://github.com/ampache/ampache/blob/31088e92252c61eb4aaa8d8484c9c7fd86a2a870/public/templates/header.inc.php#L107). 

It was also being used for actual output so those have been renamed.

(sorry to whoever implemented this originally)

### CODE REVIEW

**Comment by lachlan-00** [comment]
Seems to break the webplayer popup with this one

**Comment by mitchray** [comment]
Wow, its actually being used for critical operation. I'll revisit this.

Again, wow.

**Comment by vollmerk** [comment]
> Wow, its actually being used for critical operation. I'll revisit this.
> 
> Again, wow.

Hahaha, AMAZING - I added that when "AJAX" was just starting to be a thing, and you had to edit the DOM manually. Sad to see it go, but glad that it survived this long in a way.

**Comment by mitchray** [comment]
Its a testament to your efforts (and the web as a whole) that it still works!

New PR here https://github.com/ampache/ampache/pull/3945

**Comment by lachlan-00** [comment]
Classic Ampache here. (love it)

ajax pages echo xoutput_from_array
image

which defaults to xml
image


(the xoutput request variable only seems to be for next/prev on browses)
image

And then loops back to xoutput_from_array as a callback
image

which seems to be used to avoid putting a header on the string
image

Which is then all echoed out.

at least that makes sense to why the arrays are there.

**Pull request merged**
