### PR TITLE
remove useless code, look at groups further.

### PR DESCRIPTION
**Pull request by lachlan-00**
* Now that things are coming together, double check #2023 changes.
* get_by_year is just a search so use that instead

### CODE REVIEW

**Comment by lachlan-00** [comment]
@noyse27 can you check the following link for an artist you know is multidisk as well as single disk
 * https://site.com/artists.php?action=show&artist=%artistnumber%

Then check an album that's multi disk with grouping enabled and disabled
* https://site.com/albums.php?action=show&album=%albumnumber%

Finally just give me a query for each of these
```
SELECT * FROM `album` WHERE `name` = '%albumname%';
SELECT * FROM `song` WHERE `album` IN (SELECT `id` FROM `album` WHERE `name` = '%albumname%');
```

I do see that search results should include disk, so that's an additional fix needed.

**Comment by noyse27** [comment]
@lachlan-00 
here are the results of the url things that i had to do ;)



artist url w/o grouping


artist url with grouping


album url is not helpful because of every disc has its own album id




```
MariaDB [ampache]> select * from album where name = 'Рядом с Евой';
+------+------------------------+--------+------+------+------+------------+--------------+--------------+---------------+---------+----------------+
| id   | name                   | prefix | mbid | year | disk | mbid_group | release_type | album_artist | original_year | barcode | catalog_number |
+------+------------------------+--------+------+------+------+------------+--------------+--------------+---------------+---------+----------------+
| 8054 | Рядом с Евой           | NULL   | NULL | 2019 |    1 | NULL       | NULL         |         9622 |          NULL | NULL    | NULL           |
| 8055 | Рядом с Евой           | NULL   | NULL | 2019 |    2 | NULL       | NULL         |         9622 |          NULL | NULL    | NULL           |
+------+------------------------+--------+------+------+------+------------+--------------+--------------+---------------+---------+----------------+
2 rows in set (0.024 sec)
```
`MariaDB [ampache]> select * from song where album in(select id from album where name = 'Рядом с Евой')\G
*************************** 1. row ***************************
           id: 98231
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/01-летозолото 5777-мы.mp3
      catalog: 1
        album: 8054
         year: 2019
       artist: 9622
        title: Летозолото 5777
      bitrate: 320046
         rate: 44100
         mode: vbr
         size: 7341749
         time: 180
        track: 1
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303326
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 2. row ***************************
           id: 98232
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/02-рядом-мы.mp3
      catalog: 1
        album: 8054
         year: 2019
       artist: 9622
        title: Рядом
      bitrate: 320038
         rate: 44100
         mode: vbr
         size: 8728309
         time: 214
        track: 2
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303327
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 3. row ***************************
           id: 98233
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/03-спасательный круг-мы.mp3
      catalog: 1
        album: 8054
         year: 2019
       artist: 9622
        title: Спасательный круг
      bitrate: 320055
         rate: 44100
         mode: vbr
         size: 6176692
         time: 150
        track: 3
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303327
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 4. row ***************************
           id: 98234
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/04-потратили-мы.mp3
      catalog: 1
        album: 8054
         year: 2019
       artist: 9622
        title: Потратили
      bitrate: 320077
         rate: 44100
         mode: vbr
         size: 4473492
         time: 108
        track: 4
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303327
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 5. row ***************************
           id: 98235
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/05-золото-мы.mp3
      catalog: 1
        album: 8054
         year: 2019
       artist: 9622
        title: Золото
      bitrate: 320060
         rate: 44100
         mode: vbr
         size: 5690793
         time: 138
        track: 5
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303328
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 6. row ***************************
           id: 98236
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/06-журавль-мы.mp3
      catalog: 1
        album: 8054
         year: 2019
       artist: 9622
        title: Журавль
      bitrate: 320037
         rate: 44100
         mode: vbr
         size: 8959235
         time: 220
        track: 6
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303328
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 7. row ***************************
           id: 98237
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/07-дно2-мы.mp3
      catalog: 1
        album: 8054
         year: 2019
       artist: 9622
        title: Дно2
      bitrate: 320063
         rate: 44100
         mode: vbr
         size: 5415980
         time: 131
        track: 7
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303328
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 8. row ***************************
           id: 98238
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/08-boys and girls-мы.mp3
      catalog: 1
        album: 8054
         year: 2019
       artist: 9622
        title: Boys and Girls
      bitrate: 320064
         rate: 44100
         mode: vbr
         size: 5292702
         time: 128
        track: 8
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303329
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 9. row ***************************
           id: 98239
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/09-брат и сестра-мы.mp3
      catalog: 1
        album: 8054
         year: 2019
       artist: 9622
        title: Брат и сестра
      bitrate: 320051
         rate: 44100
         mode: vbr
         size: 6621811
         time: 162
        track: 9
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303329
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 10. row ***************************
           id: 98240
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/10-нелюбовь-мы.mp3
      catalog: 1
        album: 8054
         year: 2019
       artist: 9622
        title: Нелюбовь
      bitrate: 320063
         rate: 44100
         mode: vbr
         size: 5400315
         time: 131
        track: 10
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303329
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 11. row ***************************
           id: 98241
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/11-утро-мы.mp3
      catalog: 1
        album: 8054
         year: 2019
       artist: 9622
        title: Утро
      bitrate: 320054
         rate: 44100
         mode: vbr
         size: 6305189
         time: 154
        track: 11
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303330
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 12. row ***************************
           id: 98242
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/12-время-мы.mp3
      catalog: 1
        album: 8054
         year: 2019
       artist: 9622
        title: Время
      bitrate: 320050
         rate: 44100
         mode: vbr
         size: 6749272
         time: 165
        track: 12
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303330
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 13. row ***************************
           id: 98243
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/13-дети-мы.mp3
      catalog: 1
        album: 8055
         year: 2019
       artist: 9622
        title: Дети
      bitrate: 320069
         rate: 44100
         mode: vbr
         size: 4961450
         time: 120
        track: 13
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303330
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 14. row ***************************
           id: 98244
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/14-осень-мы.mp3
      catalog: 1
        album: 8055
         year: 2019
       artist: 9622
        title: Осень
      bitrate: 320050
         rate: 44100
         mode: vbr
         size: 6687623
         time: 163
        track: 14
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303330
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 15. row ***************************
           id: 98245
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/15-осень2-мы.mp3
      catalog: 1
        album: 8055
         year: 2019
       artist: 9622
        title: Осень2
      bitrate: 320042
         rate: 44100
         mode: vbr
         size: 7974939
         time: 195
        track: 15
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303331
addition_time: 1566252947
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 16. row ***************************
           id: 98246
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/16-люблюз и любог-мы.mp3
      catalog: 1
        album: 8055
         year: 2019
       artist: 9622
        title: Люблюз и любог
      bitrate: 320033
         rate: 44100
         mode: vbr
         size: 10010417
         time: 246
        track: 16
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303331
addition_time: 1566252948
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 17. row ***************************
           id: 98247
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/17-зима-мы.mp3
      catalog: 1
        album: 8055
         year: 2019
       artist: 9622
        title: Зима
      bitrate: 320038
         rate: 44100
         mode: vbr
         size: 8822348
         time: 217
        track: 17
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303331
addition_time: 1566252948
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 18. row ***************************
           id: 98248
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/18-близость-мы.mp3
      catalog: 1
        album: 8055
         year: 2019
       artist: 9622
        title: Близость
      bitrate: 320046
         rate: 44100
         mode: vbr
         size: 7341735
         time: 180
        track: 18
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303332
addition_time: 1566252948
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 19. row ***************************
           id: 98249
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/19-выше-мы.mp3
      catalog: 1
        album: 8055
         year: 2019
       artist: 9622
        title: Выше
      bitrate: 320063
         rate: 44100
         mode: vbr
         size: 5378364
         time: 130
        track: 19
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303332
addition_time: 1566252948
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 20. row ***************************
           id: 98250
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/20-весна2-мы.mp3
      catalog: 1
        album: 8055
         year: 2019
       artist: 9622
        title: Весна2
      bitrate: 320057
         rate: 44100
         mode: vbr
         size: 5987544
         time: 146
        track: 20
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303332
addition_time: 1566252948
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 21. row ***************************
           id: 98251
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/21-love is [feat. счастливые люди]-мы.mp3
      catalog: 1
        album: 8055
         year: 2019
       artist: 9622
        title: Love is (feat. Счастливые Люди)
      bitrate: 320047
         rate: 44100
         mode: vbr
         size: 7233112
         time: 177
        track: 21
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303333
addition_time: 1566252948
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 22. row ***************************
           id: 98252
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/22-папа и мама-мы.mp3
      catalog: 1
        album: 8055
         year: 2019
       artist: 9622
        title: Папа и Мама
      bitrate: 320052
         rate: 44100
         mode: vbr
         size: 6464027
         time: 158
        track: 22
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303333
addition_time: 1566252948
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 23. row ***************************
           id: 98253
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/23-киты [feat. сансара]-мы.mp3
      catalog: 1
        album: 8055
         year: 2019
       artist: 9622
        title: Киты (feat. Сансара)
      bitrate: 320065
         rate: 44100
         mode: vbr
         size: 5261367
         time: 128
        track: 23
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303333
addition_time: 1566252948
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 24. row ***************************
           id: 98254
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/24-победители-мы.mp3
      catalog: 1
        album: 8055
         year: 2019
       artist: 9622
        title: Победители
      bitrate: 320066
         rate: 44100
         mode: vbr
         size: 5143274
         time: 125
        track: 24
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303334
addition_time: 1566252948
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
*************************** 25. row ***************************
           id: 98255
         file: /volume1/music/[]-/Мы/[2019]-рядом с евой/25-как в море корабли-мы.mp3
      catalog: 1
        album: 8055
         year: 2019
       artist: 9622
        title: Как в море корабли
      bitrate: 320046
         rate: 44100
         mode: vbr
         size: 7365788
         time: 180
        track: 25
         mbid:
       played: 0
      enabled: 1
  update_time: 1567303334
addition_time: 1566252948
  user_upload: NULL
      license: NULL
     composer:
     channels: 2
25 rows in set (0.001 sec)
`

**Comment by lachlan-00** [comment]
I think i've found a similar issue for me.
image

The 'Various' code seems to be an issue. This was really helpful!

**Comment by lachlan-00** [comment]
that album was a tag issue. i'll keep looking at this.

The logic around the albums is cleaner now but still very convoluted.

**Comment by lachlan-00** [comment]
okay @noyse27 i've fixed the counting problems. it was still not handling groups well.

Now i think the last thing is that when you are ungrouped that disk 1 and disk 2 aren't showing?

рядом с евой is having the same problem as your original issue? i'm going to try and find an album that does the same thing for me now.

**Comment by lachlan-00** [comment]
Found it. Old code only let you group when an mbid is present.

Now that i group everything i've added extra options to group without an mbid.

**Comment by noyse27** [comment]
seems to be work now :)

**Comment by noyse27** [comment]
sorry there is still a little problem - if the sevearl artists have a album of the same name they 
will be grouped too...

**Comment by lachlan-00** [comment]
No problem. These must all have no album artist so I'll push another fix soon

**Comment by lachlan-00** [comment]
I don't have any dupes to test this. 

can you give me a 
```
select * from album where name = 'Essentials';
```

**Pull request merged**
