### PR TITLE
Update json_data.class.php

### PR DESCRIPTION
**Pull request by AshotN**
Why is `id` begin cast to string when it's number? 

Fix the include not working in Album.

There are some type errors that still need to be resolved.

### CODE REVIEW

**Comment by usox** [comment]
Well, using `string` as type for ids is not a bad idea (at least as parameter type for external communication). Changing those parameters to `int` will remove some flexibility from the api (maybe, in future someone comes up with the idea to use uuids as id) - just sayin'.

**Comment by lachlan-00** [comment]
XML requires the id to be strings to generate valid xml. Because of that i've made it a rule to do all object ids as a string and i'd like to keep JSON the same as XML.

We also have one string type; Smart playlists in the api are sent with a "smart_" prefix which would then be different if we went to ints.

**Comment by lachlan-00** [comment]
I also just realised we don't have a users api call to get a list of users. that seems a bit of an oversight

**Comment by AshotN** [comment]
I can revert the string->int casting then. But should JSON be held back due to XML.

**Comment by AshotN** [comment]
I've made the requested changes, if you could review. If everything is alright, please squash and merge :)

**Pull request merged**
