### PR TITLE
transcode decision problem found when using DSub for Android

### PR DESCRIPTION
**Pull request by lockcole**
I found a problem while using DSub v5.3.4.

**Situation Description**
DSub always sends request bitrate even if the max bitrate setting is "Unlimited". It just request for the same bitrate as the original file.
For example, it will request 320k bitrate for playback of a mp3 file which is already 320k.
And it will request a 968K bitrate for playback of a flac file which has bitrate of 968241

**log for flac:**
> 2017-02-27 10:35:53 [lockcole] (subsonic) -> Stream proxy: https://myserver:443/ampache/play/index.php?ssid=5190db9e0c7f6efc29067f1d1df9e433&type=song&oid=527&uid=3&client=DSub&noscrobble=1&bitrate=968&player=api&name=Lira%20-%20-.flac
> 2017-02-27 10:35:53 [ampache] (play) -> Asked for type {song}
> 2017-02-27 10:35:53 [lockcole] (session) -> 5190db9e0c7f6efc29067f1d1df9e433 has been extended to Mon, 27 Feb 2017 12:35:53 +0800 extension length 7200
> 2017-02-27 10:35:53 [lockcole] (play) -> Playing file (/data/storage/Music/[110810] Lira - Dear Lilac/02. Track 02.flac}...
> 2017-02-27 10:35:53 [lockcole] (play) -> Media type {flac}
> 2017-02-27 10:35:53 [lockcole] (play) -> Custom play action {}
> 2017-02-27 10:35:53 [lockcole] (play) -> Transcode to {}
> 2017-02-27 10:35:53 [lockcole] (play) -> Transcoding because explicit bitrate request
> 2017-02-27 10:35:53 [lockcole] (stream.class.php) -> Starting transcode for {/data/storage/Music/[110810] Lira - Dear Lilac/02. Track 02.flac}. Type {}. Options: Array
> 2017-02-27 10:35:53 [lockcole] (stream.class.php) -> (
> 2017-02-27 10:35:53 [lockcole] (stream.class.php) ->     [bitrate] => 968
> 2017-02-27 10:35:53 [lockcole] (stream.class.php) -> )
> 2017-02-27 10:35:53 [lockcole] (stream.class.php) -> }...
> 2017-02-27 10:35:53 [lockcole] (media) -> Using default target format
> 2017-02-27 10:35:53 [lockcole] (media) -> Transcode settings: from flac to mp3
> 2017-02-27 10:35:53 [lockcole] (media) -> Command: ffmpeg Arguments: -i %FILE% -vn -b:a %BITRATE%K -c:a libmp3lame -f mp3 pipe:1
> 2017-02-27 10:35:53 [lockcole] (stream) -> Final transcode bitrate is 968
> 2017-02-27 10:35:53 [lockcole] (stream) -> %SAMPLE% not in transcode command
> 2017-02-27 10:35:53 [lockcole] (stream) -> %MAXBITRATE% not in transcode command
> 2017-02-27 10:35:53 [lockcole] (stream) -> %RESOLUTION% not in transcode command
> 2017-02-27 10:35:53 [lockcole] (stream) -> %QUALITY% not in transcode command
> 2017-02-27 10:35:53 [lockcole] (stream) -> Transcode command: ffmpeg -i '/data/storage/Music/[110810] Lira - Dear Lilac/02. Track 02.flac' -vn -b:a 968K -c:a libmp3lame -f mp3 pipe:1
> 2017-02-27 10:35:53 [lockcole] (stream) -> Transcode command prefix: exec

**Problems found:**
1. A bug in bitrate comparison is causing unnecessary transcode while it is not actually needed.
2. for flac (not checked with other formats), the reported bitrate will be something like  968241. So a
`($bitrate * 1000 < $$media->bitrate)` => (968000 < 968241)
 comparsion is not handling this situation very well. And thus causing unnessary transcode (transcoding to a 968K mp3 is meaningless anyway)

**What have I fixed**
I fixed the comparsion code for fix (1) and did some adjustment to handle problem (2) slightly better.
Hope that my fix is OK and will be accepted.

### CODE REVIEW

**Comment by linucksrox** [comment]
Thank you for this patch, it solves the issue I was having with noticeable quality loss when transcoding a 128kbps mp3 to 128kbps. I think there's also an issue on Dsub's side where it specifically requests 128kbps bitrate although it's set to unlimited, but I'll have to open an issue on their repo for that.

**Comment by lachlan-00** [comment]
codestyle error
```
$media_bitrate = floor($media->bitrate/1000);
```
should be
```
$media_bitrate = floor($media->bitrate / 1000);
```

**Comment by lockcole** [comment]
@lachlan-00 
I have fixed the code style. 
Sorry for not fixing it for a long time.

**Comment by lachlan-00** [comment]
Hey no problem, just trying to go through the pulls and try them out so I only noticed when I tried it on my server.

**Comment by lachlan-00** [comment]
Closing this as i've merged it into my fork and will merge it into the official core branch soon.

You are now an Ampache contributor!

**Pull request closed without merging**
