### PR TITLE
Do not force write_playlists.php to be called from bin folder

### PR DESCRIPTION
**Pull request by Phyks**
As reported in https://github.com/ampache/ampache/issues/405#issuecomment-244550648.

### CODE REVIEW

**Comment by Phyks** [comment]
@roba91 Could you check this matches the error reported [here](https://github.com/ampache/ampache/issues/405#issuecomment-244550648)?

**Comment by roba91** [comment]
@Phyks: How should I check that?

**Comment by Phyks** [comment]
You can check out [this branch](https://github.com/phyks/ampache/tree/Phyks-patch-1) and check that it actually works if not calling from `bin` folder. I am not with my usual computer with dev stuff for Ampache at the moment, and cannot check this modification actually match your issue :/

**Comment by roba91** [comment]
I think it's a overhead of about an hour for me to make it run under similar conditions as my productive system now. I guess it would be much easier for you to do so as soon as you have your dev machine back...

**Comment by Phyks** [comment]
Ok, I'll check.

**Comment by Afterster** [comment]
Okay, finally merged :wink:. Thanks!

**Pull request merged**
