### PR TITLE
Fix typo: s/quiting/quitting/

### PR DESCRIPTION
**Pull request by Gano16**

### CODE REVIEW

**Comment by Niols** [comment]
@Psy-Virus, I've taken a look at #1335 that fixed the typo in #1309, and I believe that this PR is valid.
However, how can one reflect the change in Transifex?

**Comment by Psy-Virus** [comment]
Hey @Niols,
basically #1309 was fixing the typo in #1309. ^^
With #1335 I recreated the POT file (and also pulled the translations from Transifex and merged everything together), including the fix, from source and PRed it. Transifex then pulled it from GitHub after it was merged and Transifex saw a change.

So you can't simply fix it on Transifex, except you have write permissions to the Source file.

Wanna steal my job, eh? :-D

Please take a look at [this](https://github.com/ampache/ampache/blob/master/locale/base/TRANSLATIONS.md) and into the help screen of `/locale/base/gather-messages.sh --help` for more information. This should give you everything you need to know. But if you have further questions, you know where to find me.^^

:-)

**Comment by Psy-Virus** [comment]
But why was this PR closed?

**Comment by Phyks** [comment]
Was pushed onto the wrong branch. See https://github.com/ampache/ampache/pull/1342.

**Comment by Psy-Virus** [comment]
Oh, okay^^

**Pull request closed without merging**
