### PR TITLE
Base database-words.txt and translation catalog updated

### PR DESCRIPTION
**Pull request by Psy-Virus**
I've updated them to match the latest state.
I also changed the auto-update link in Transifex to match the RAW-messages.pot file on GitHub as described in the Transifex docs. So this is also a test for Transifex if it automatically pulls the latest version after merge.

@Afterster, have you changed the preference IDs in the DB?
You see that I had to rewrite many of the IDs in the DB-W.txt, and check if they match the DB-entries. 
This needs a lot of time, because it have to be done manually at the moment.
I thought, that the IDs do not change if you add preferences, so I used them as a fix point, so that I only have to check which prefs are gone and which are new and update only these.

Otherwise if they are generated automatically in any situation, I maybe should update the `gather-messages.sh` to automatically read the preferences and IDs as [discussed](https://github.com/ampache/ampache/issues/155), around a year ago. To avoid these time eating manual checks...

### CODE REVIEW

**Comment by Afterster** [comment]
Mhh interesting @Psy-Virus. Indeed the preference IDs shouldn't change but we shouldn't forget in future commits that some stuff is related to it. This is error prone, I think we can still deal with it now but we need to be careful to not change the IDs anymore.
I updated the default sql script creation few months ago, maybe it changed the preference IDs on new installation sorry I didn't looked about that. As you said reading the IDs from db (in a second time) will make it sure everything is correct.
I probably did a misconfiguration in Transifex too... Thanks again for taking care of the translation management, this is highly important and you're helping a lot here.

**Comment by Psy-Virus** [comment]
All right.. After messing around with my Database on my dev-instance and some learning about and brawling with mysql, I've nearly finished the dbentryautoupdatetogather-messages.sh skript thing.

Aaand you are the lucky winner who will do a second beta test :D

Here's what I've done
https://github.com/ampache/ampache/compare/develop...Psy-Virus:Psy-Virus-ampache-gather-messages.sh-db-fetch

And here's the script.

Simply copy it over to `/locale/base/gather-messages.sh` and run it like `./gather-messages.sh --all`
This will firstly delete the `translation-words.txt`and the `messages.pot`, then recreate the pot using the source strings and after that it connects to the mysql server with your credentials, provided in your `ampache.cfg.php`, fetch the strings we need and saves them in the `translation-words.txt` (I know, we also coud put it directly in). After that, the content of T-W.txt is copied to the pot. 
The last step is the merge into the other files like before, et voilà we have an everything's nice device... or script... O.o

```shell
#!/bin/bash
#
# vim:set softtabstop=4 shiftwidth=4 expandtab:
#
# Copyright 2001 - 2015 Ampache.org
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v2
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#

PATH=$PATH:/bin:/usr/bin:/usr/local/bin
dbhost=$(grep -oP "(?<=database_hostname = \")[^\"\n]+" ../../config/ampache.cfg.php)
dbname=$(grep -oP "(?<=database_name = \")[^\"\n]+" ../../config/ampache.cfg.php)
dbuser=$(grep -oP "(?<=database_username = \")[^\"\n]+" ../../config/ampache.cfg.php)
dbpass=$(grep -oP "(?<=database_password = \")[^\"\n]+" ../../config/ampache.cfg.php)

# gettext package test
if ! which xgettext &>/dev/null ; then
    echo "xgettext not found. Do you need to install gettext?"
    exit 1;
fi

[[ $OLANG ]] || OLANG=$(echo $LANG | sed 's/\..*//;')
POTNAME='messages.pot'

usage() {
    echo "usage: $0 [--help|--get|--init|--merge|--format|--all]"
    echo
    echo 'See also: http://ampache.org/wiki/dev:translation'
    exit 1
}

generate_pot() {
    echo "Deleting old messages.pot"
    rm messages.pot
    xgettext    --from-code=UTF-8 \
                --add-comment=HINT: \
                --msgid-bugs-address="translations@ampache.org" \
                -L php \
                --keyword=gettext_noop --keyword=T_ --keyword=T_gettext --keyword=T_ngettext --keyword=ngettext \
                -o $POTNAME \
                $(find ../../ -type f -name \*.php -o -name \*.inc | sort)
    if [[ $? -eq 0 ]]; then
        echo "pot file creation succeeded"
        echo "delete old translation-words.txt"
        rm translation-words.txt
        echo "Adding database words to pot file..."
        mysql -N --database=$dbname --host=$dbhost --user=$dbuser --password=$dbpass -se "SELECT id FROM preference" | 
        while read dbprefid; do
            dbprefdesc=$(mysql -ND"ampache-dev" -h"localhost" -u"ampache-dev" -p"847274656" -se "SELECT description FROM preference where id=$dbprefid")
            dbprefdescchk=$(grep "\"$dbprefdesc\"" messages.pot)
            if [ ! "$dbprefdescchk" ]; then
            echo    "#: Database preference table id $dbprefid" >> translation-words.txt
            echo -e "msgid \"$dbprefdesc\"" >> translation-words.txt
            echo -e "msgstr \"\"\n" >> translation-words.txt
            else
            echo    "#: Database preference table id $dbprefid" >> translation-words.txt
            echo -e "# is already in the source code\n# but to avoid confusion, it's added and commented" >> translation-words.txt
            echo -e "# msgid \"$dbprefdesc\"" >> translation-words.txt
            echo -e "# msgstr \"\"\n" >> translation-words.txt
            fi
        done
        cat translation-words.txt >> messages.pot
    else
        echo "pot file creation failed"
    fi
}

do_msgmerge() {
    source=$POTNAME
    target="../$1/LC_MESSAGES/messages.po"
    echo "Merging $source into $target"
    msgmerge --update --backup=off $target $source
    echo "Obsolete messages in $target: " $(grep '^#~' $target | wc -l)
}

do_msgfmt() {
    source="../$1/LC_MESSAGES/messages.po"
    target="../$1/LC_MESSAGES/messages.mo"
    echo "Creating $target from $source"
    msgfmt --verbose --check $source -o $target
}

if [[ $# -eq 0 ]]; then
    usage
fi

case $1 in
    '--all'|'-a'|'all')
        generate_pot
	for i in $(ls ../ | grep -v base); do
	    do_msgmerge $i
	    do_msgfmt $i
	done
    ;;
    '--allformat')
	for i in $(ls ../ | grep -v base); do
	    do_msgfmt $i
	done
    ;;
    '--allmerge')
	for i in $(ls ../ | grep -v base); do
	    do_msgmerge $i
	done
    ;;
    '--get'|'-g'|'get')
        generate_pot
    ;;
    '--init'|'-i'|'init')
        outdir="../$OLANG/LC_MESSAGES"
        [[ -d $outdir ]] || mkdir -p $outdir
	msginit -l $LANG -i $POTNAME -o $outdir/messages.po
    ;;
    '--format'|'-f'|'format')
        do_msgfmt $OLANG
    ;;
    '--merge'|'-m'|'merge')
        do_msgmerge $OLANG
    ;;
    '--help'|'-h'|'help'|'*')
        usage
    ;;
esac
```

**Comment by Psy-Virus** [comment]
All right.. After messing around with my Database on my dev-instance and some learning about and brawling with mysql, I've nearly finished the dbentryautoupdatetogather-messages.sh script thing.

Aaand you are the lucky winner who will do a second beta test :D

Here's what I've done
https://github.com/Psy-Virus/ampache/commit/7f42bbbb4ea134826103d4e3d5c0f9bf9133e382

And here's the script.

Simply copy it over to `/locale/base/gather-messages.sh`
and run it like `./gather-messages.sh --all`
This will firstly delete the `translation-words.txt`and the `messages.pot`, then recreate the pot using the source strings and after that it connects to the mysql server with your credentials, provided in your `ampache.cfg.php`, fetch the strings we need and saves them in the `translation-words.txt` (I know, we also coud put it directly in). After that, the content of T-W.txt is copied to the pot. 
The last step is the merge into the other files like before, et voilà we have an everything's nice device... or script... O.o

Hope, you like it :-)

```shell
#!/bin/bash
#
# vim:set softtabstop=4 shiftwidth=4 expandtab:
#
# Copyright 2001 - 2015 Ampache.org
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v2
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#

PATH=$PATH:/bin:/usr/bin:/usr/local/bin
dbhost=$(grep -oP "(?<=database_hostname = \")[^\"\n]+" ../../config/ampache.cfg.php)
dbname=$(grep -oP "(?<=database_name = \")[^\"\n]+" ../../config/ampache.cfg.php)
dbuser=$(grep -oP "(?<=database_username = \")[^\"\n]+" ../../config/ampache.cfg.php)
dbpass=$(grep -oP "(?<=database_password = \")[^\"\n]+" ../../config/ampache.cfg.php)

# gettext package test
if ! which xgettext &>/dev/null ; then
    echo "xgettext not found. Do you need to install gettext?"
    exit 1;
fi

[[ $OLANG ]] || OLANG=$(echo $LANG | sed 's/\..*//;')
POTNAME='messages.pot'

usage() {
    echo "usage: $0 [--help|--get|--init|--merge|--format|--all]"
    echo
    echo 'See also: http://ampache.org/wiki/dev:translation'
    exit 1
}

generate_pot() {
    echo "Deleting old messages.pot"
    rm messages.pot
    xgettext    --from-code=UTF-8 \
                --add-comment=HINT: \
                --msgid-bugs-address="translations@ampache.org" \
                -L php \
                --keyword=gettext_noop --keyword=T_ --keyword=T_gettext --keyword=T_ngettext --keyword=ngettext \
                -o $POTNAME \
                $(find ../../ -type f -name \*.php -o -name \*.inc | sort)
    if [[ $? -eq 0 ]]; then
        echo "pot file creation succeeded"
        echo "delete old translation-words.txt"
        rm translation-words.txt
        echo "Adding database words to pot file..."
        mysql -N --database=$dbname --host=$dbhost --user=$dbuser --password=$dbpass -se "SELECT id FROM preference" | 
        while read dbprefid; do
            dbprefdesc=$(mysql -N --database=$dbname --host=$dbhost --user=$dbuser --password=$dbpass -se "SELECT description FROM preference where id=$dbprefid")
            dbprefdescchk=$(grep "\"$dbprefdesc\"" messages.pot)
            if [ ! "$dbprefdescchk" ]; then
            echo    "#: Database preference table id $dbprefid" >> translation-words.txt
            echo -e "msgid \"$dbprefdesc\"" >> translation-words.txt
            echo -e "msgstr \"\"\n" >> translation-words.txt
            else
            echo    "#: Database preference table id $dbprefid" >> translation-words.txt
            echo -e "# is already in the source code\n# but to avoid confusion, it's added and commented" >> translation-words.txt
            echo -e "# msgid \"$dbprefdesc\"" >> translation-words.txt
            echo -e "# msgstr \"\"\n" >> translation-words.txt
            fi
        done
        cat translation-words.txt >> messages.pot
    else
        echo "pot file creation failed"
    fi
}

do_msgmerge() {
    source=$POTNAME
    target="../$1/LC_MESSAGES/messages.po"
    echo "Merging $source into $target"
    msgmerge --update --backup=off $target $source
    echo "Obsolete messages in $target: " $(grep '^#~' $target | wc -l)
}

do_msgfmt() {
    source="../$1/LC_MESSAGES/messages.po"
    target="../$1/LC_MESSAGES/messages.mo"
    echo "Creating $target from $source"
    msgfmt --verbose --check $source -o $target
}

if [[ $# -eq 0 ]]; then
    usage
fi

case $1 in
    '--all'|'-a'|'all')
        generate_pot
	for i in $(ls ../ | grep -v base); do
	    do_msgmerge $i
	    do_msgfmt $i
	done
    ;;
    '--allformat')
	for i in $(ls ../ | grep -v base); do
	    do_msgfmt $i
	done
    ;;
    '--allmerge')
	for i in $(ls ../ | grep -v base); do
	    do_msgmerge $i
	done
    ;;
    '--get'|'-g'|'get')
        generate_pot
    ;;
    '--init'|'-i'|'init')
        outdir="../$OLANG/LC_MESSAGES"
        [[ -d $outdir ]] || mkdir -p $outdir
	msginit -l $LANG -i $POTNAME -o $outdir/messages.po
    ;;
    '--format'|'-f'|'format')
        do_msgfmt $OLANG
    ;;
    '--merge'|'-m'|'merge')
        do_msgmerge $OLANG
    ;;
    '--help'|'-h'|'help'|'*')
        usage
    ;;
esac
```

**Comment by Afterster** [comment]
Mhh this looks good so far, and more complicated than I thought thanks ^^.
*But*, could you make it an option in the command line (not activated by default), so it will keep current behavior by default and doesn't need a valid ampache installation with live mysql database if your attempt is just to translate files. Thanks!

**Comment by Psy-Virus** [comment]
Hmm if I understand you right, you mean, the script should read the `sql/ampache.sql`file... 
@Afterster? Either you have a strange kind of humour, or you want me to hate you :D
... As the saying is: ~"You're growing with your challenges"

I'll try it, but that will be more complex, because I have to use more tools, parse the text from a specific line to another, filter the text to get only the columns we want and so on; contrary to use only mysql, what selects the right values automatically with `select from bla where bla`. But I understand why it would be better to read it offline/from the source file.

> But, could you make it an option in the command line (not activated by default), so it will keep current behavior by default

I don't know if this makes great sense because the T-W.txt is also automatically added in the current behaviour. My modification only generates it automatically and up to date before it is added.
I mean, the preferences have to be added to the pot. Isn't it better and more comfortable to do this completely automated? The same is for the automation of the pot generation on github in future. If this automation works like a normal Linux box you only have to run it via cron, one or two times every day, then.

Or do you see another upcoming problem I haven't thought about?

**Comment by Afterster** [comment]
Nop it's not what I mean.
I think current implementation you just did is really good, but today ampache can be translated without the requirement to be connected. With your changes ampache will have to be setup to be allowed to translate it. I would not like to have it by default because few peoples (I know few who did that and I found even myself translating ampache 'offline' on a regular computer without any webserver/mysql/...).
A simple argument passed in the script shell to enable this new behavior will be enough.

**Comment by Psy-Virus** [comment]
Ahh okay :bulb:, Now I got it :-)

The way I mentioned would also be too complex. I tried it and ended up with something like this:
```shell
$ awk '/INSERT INTO \`preference\` \(\`id\`, \`name\`, \`value\`, \`description\`, \`level\`, \`type\`, \`catagory\`\) VALUES/{f=1;next} /-- --------------------------------------------------------/{f=0} f' ampache.sql | 
grep -oP '(?<=\().*(?=\),)' | 
while read line; do 
    nl=$(echo $line | cut --delimiter="," -f 1,4)
    echo $nl
done
```
And even this isn't complete.

---

Is `translations@ampache.org` still a valid mail address?

Oh and sorry for the delay.

Here's the comparison for the updated script against the ~original:
https://github.com/Psy-Virus/ampache/commit/736c1f8785003c1d501d18137cee0b6f35df554f

And here's the updated script:

```shell
#!/bin/bash
#
# vim:set softtabstop=4 shiftwidth=4 expandtab:
#
# Copyright 2001 - 2015 Ampache.org
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License v2
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#

PATH=$PATH:/bin:/usr/bin:/usr/local/bin

# gettext package test
if ! which xgettext &>/dev/null ; then
    echo "xgettext not found. Do you need to install gettext?"
    exit 1;
fi

[[ $OLANG ]] || OLANG=$(echo $LANG | sed 's/\..*//;')
potfile='messages.pot'
twtxt=translation-words.txt

usage() {
    echo ""
    echo -e "usage: $0 [--help|--get|--init|--merge|--format|-utw|--all]"
    echo ""
    echo -e "[-g|--get]\t Creates the messages.pot file from translation strings within the source code."
    echo -e "[-i|--init]\t Creates a new language catalog and its directory structure."
    echo -e "[-m|--merge]\t Merges the messages.pot into the language catalogs and shows obsolet translations."
    echo -e "[-f|--format]\t Compiles the .mo file for its related .po file."
    echo -e "[-a|--all]\t Does all exept --init and --utw."
    echo -e "[-au|--allutw]\t Does all exept --init and Updates/creates the 'translation-words.txt'.\n\t\t Ampache needs to be fully setup."
    echo -e "[-h|--help]\t Shows this help screen."
    echo ""
    echo "See also: https://github.com/ampache/ampache/blob/master/locale/base/TRANSLATIONS"
    echo ""
    exit 1
}

generate_pot() {
    echo "Generating/updating pot-file"
    xgettext    --from-code=UTF-8 \
                --add-comment=HINT: \
                --msgid-bugs-address="translations@ampache.org" \
                -L php \
                --keyword=gettext_noop --keyword=T_ --keyword=T_gettext --keyword=T_ngettext --keyword=ngettext \
                -o $potfile \
                $(find ../../ -type f -name \*.php -o -name \*.inc | sort)
    if [[ $? -eq 0 ]]; then
        echo "Pot file creation succeeded. Adding 'translation-words.txt"
        cat $twtxt >> $potfile
    else
        echo "pot file creation failed"
    fi
}

generate_pot_utw() {
    echo ""
    echo "Generating/updating pot-file"
    echo ""
    xgettext    --from-code=UTF-8 \
                --add-comment=HINT: \
                --msgid-bugs-address="translations@ampache.org" \
                -L php \
                --keyword=gettext_noop --keyword=T_ --keyword=T_gettext --keyword=T_ngettext --keyword=ngettext \
                -o $potfile \
                $(find ../../ -type f -name \*.php -o -name \*.inc | sort)
    if [[ $? -eq 0 ]]; then
        echo -e "Pot creation/update successful\n"
        echo -e "Reading database login information from Amapche config file\n"
        
        dbhost=$(grep -oP "(?<=database_hostname = \")[^\"\n]+" ../../config/ampache.cfg.php)
        if [ ! $dbhost ]; then
            echo ""
            echo "Error: No or false database host setting detected!"
            read -r -p "Type in a host or simply press enter to use localhost instead: " dbhost
                if [ ! $dbhost ]; then
                    dbhost=localhost
                else
                    continue
                fi
        fi
        echo "Saved '$dbhost' as your database host"
        
        dbport=$(grep -oP "(?<=database_port = \")[^\"\n]+" ../../config/ampache.cfg.php)
        if [ ! $dbport ]; then
            echo ""
            echo "Error: No or false database_port setting detected!"
            read -r -p "Type in a port or simply press enter to use default port 3306 instead: " dbport
                if [ ! $dbport ]; then
                    dbport=3306
                fi
        fi
        echo "Saved '$dbport' as your database port"
        
        dbname=$(grep -oP "(?<=database_name = \")[^\"\n]+" ../../config/ampache.cfg.php)
        if [ ! $dbname ]; then
            echo ""
            echo "No datatabase name detected, please check your 'database_name' setting"
            read -r -p "or type in the right database name here for temporary use: " dbname
                if [ ! $dbname ]; then
                    echo ""
                    echo "Error: You didn't type in a database name, Sorry but I have to exit :("
                    exit
                fi
        fi
        echo "Saved '$dbname' as you database name"
        
        dbuser=$(grep -oP "(?<=database_username = \")[^\"\n]+" ../../config/ampache.cfg.php)
        if [ ! $dbuser ]; then
            echo "You need to set a valid database user in you Ampache config file"
            read -r -p "Or type it in here for temporary use: " dbuser
                if [ ! $dbuser ]; then
                    echo "Error: You didn't type in a database user! Sorry but I have to exit :("
                    exit
                fi
        fi
        echo "Saved '$dbuser' as your database user"

            dbpass=$(grep -oP "(?<=database_password = \")[^\"\n]+" ../../config/ampache.cfg.php)
        if [ ! $dbpass ]; then
            echo "You haven't set a database password in your Amapche config."
            read -r -p "If this is OK, press Y to continue. Otherwise we will break here: " answer
            if [[ $answer =~ ^([yY][eE][sS]|[yY])$ ]]; then
                echo "Great, lets go on"
            else
                exit
            fi
            echo "Saved 'password123' as your database password... Hehe, just kidding, but I won't show it here again"
        fi
        echo "Saved 'password123' as your database password... Hehe, just kidding, but I won't show it here"
        
        echo ""
        echo "Deleting old translation-words.txt"
        echo ""
        rm $twtxt

        echo -e "Creating new 'translation-words.txt' from database\n"
        mysql -N --database=$dbname --host=$dbhost --user=$dbuser --password=$dbpass -se "SELECT id FROM preference" | 
        while read dbprefid; do
            dbprefdesc=$(mysql -N --database=$dbname --host=$dbhost --user=$dbuser --password=$dbpass -se "SELECT description FROM preference where id=$dbprefid")
            dbprefdescchk=$(grep "\"$dbprefdesc\"" $potfile)
            if [ ! "$dbprefdescchk" ]; then
                echo -e "\n#: Database preference table id $dbprefid" >> $twtxt
                echo -e "msgid \"$dbprefdesc\"" >> $twtxt
                echo -e "msgstr \"\"" >> $twtxt
            else
                echo -e "\n#: Database preference table id $dbprefid" >> $twtxt
                echo -e "# is already in the source code\n# but to avoid confusion, it's added and commented" >> $twtxt
                echo -e "# msgid \"$dbprefdesc\"" >> $twtxt
                echo -e "# msgstr \"\"" >> $twtxt
            fi
        done
        echo -e "Adding preference-table strings to pot file...\n"
        cat $twtxt >> $potfile
    else
        echo "pot file creation failed"
    fi
}
        
do_msgmerge() {
    source=$potfile
    target="../$1/LC_MESSAGES/messages.po"
    echo "Merging $source into $target"
    msgmerge --update --backup=off $target $source
    echo "Obsolete messages in $target: " $(grep '^#~' $target | wc -l)
}

do_msgfmt() {
    source="../$1/LC_MESSAGES/messages.po"
    target="../$1/LC_MESSAGES/messages.mo"
    echo "Creating $target from $source"
    msgfmt --verbose --check $source -o $target
}

if [[ $# -eq 0 ]]; then
    usage
fi

case $1 in
    '-a'|'--all')
        generate_pot
	for i in $(ls ../ | grep -v base); do
	    do_msgmerge $i
	    do_msgfmt $i
	done
    ;;
    '-af'|'--allformat')
	for i in $(ls ../ | grep -v base); do
	    do_msgfmt $i
	done
    ;;
    '-am'|'--allmerge')
	for i in $(ls ../ | grep -v base); do
	    do_msgmerge $i
	done
    ;;
    '-g'|'--get')
        generate_pot
    ;;
    '-au'|'--allutw')
        generate_pot_utw
    ;;
    '-i'|'--init'|'init')
        outdir="../$OLANG/LC_MESSAGES"
        [[ -d $outdir ]] || mkdir -p $outdir
	msginit -l $LANG -i $potfile -o $outdir/messages.po
    ;;
    '-f'|'--format'|'format')
        do_msgfmt $OLANG
    ;;
    '-m'|'--merge'|'merge')
        do_msgmerge $OLANG
    ;;
    '-h'|'--help'|'help'|'*')
        usage
    ;;
esac
```

**Comment by Afterster** [comment]
Yes good it's what I meaned thanks.
If you are confident with your script you can PR then, I will give a try later this week (sorry for the delay, not much availibility this last days).
Any @ampache.org address should be avoided:
 1. Emails are buggy on the domain name and we never receive the emails. But that's fine because of 2.
 2. Any private discussion for the project development direction should be public

**Comment by Psy-Virus** [comment]
> Yes good it's what I meaned thanks.

Hehe, great!

> Any @ampache.org address should be avoided:

All right, then I will kick it out of the script.

> Emails are buggy on the domain name and we never receive the emails. But that's fine because of Any private discussion for the project development direction should be public

Yes sure but for more official communications or something in that direction, an @ampache.org mail address wouldn't be wrong. :] .... any time in the future^^

> If you are confident with your script you can PR 

yep, I'll look over it in the afternoon. Maybe I find something, what could need improvement..

**Pull request merged**
