### PR TITLE
case insensitive sort on metadata field list in advanced search

### PR DESCRIPTION
**Pull request by jleipsig**
proposal for feature #2425 

sorting is done in javascript. Because the subtypes are stored as objects in `var types` via search-data.php, it's not possible to do the sorting on the server side.

### CODE REVIEW

**Comment by lachlan-00** [comment]
So to match subtypes like
Label
LABEL
label?

It would be good to possibly lower case meta inserts as well to avoid creating dupes like that

**Comment by lachlan-00** [comment]
Oh, sorry alpha sorted!

**Comment by lachlan-00** [comment]
it actually just needs to get sorted here in search.class
image

**Comment by jleipsig** [comment]
That was my first thought also. But when this becomes a javascript object, the sorting gets undone

**Comment by jleipsig** [comment]
When sorting on the server side, the structure of the json data of the subtypes has be be changed from an object with { key1 : value1, key2 : value2 } to an array like [ {key1 : value1}, {key2 : value2} ]

**Comment by lachlan-00** [comment]
so should it go back further to the original query part as well? the matedata fields are selected in Repository.php (not sure if there are other tables using this)
image

**Comment by jleipsig** [comment]
That would be a great solution to also get the metadata field sorted on the preferences page. For the presentation on the advanced search, there is still something needed in the translation in lib/javascript/search-data.php arrayToJSON($search->types)
The sorting is not preserved in javascript, when presented as an object (see previous comment).

**Comment by lachlan-00** [comment]
ahh, i'm with you now. i'll sort and you JS here.

**Pull request merged**
