### PR TITLE
Xml api: filter parameter is optional for songs

### PR DESCRIPTION
**Pull request by BLeeEZ**
Implementing feature request https://github.com/ampache/ampache/issues/2285

### CODE REVIEW

**Comment by wagnered** [comment]
@BLeeEZ, should this apply only to songs?

**Comment by BLeeEZ** [comment]
After a short review, this could also be applied to videos. For videos the parameter filter is also mandatory.

**Comment by wagnered** [comment]
Thank you for checking....

**Comment by lachlan-00** [comment]
I'll have a once over now and merge

**Comment by lachlan-00** [comment]
just fixed up the docstring, will merge after travis

**Pull request merged**
