### PR TITLE
fix for ldap_require_group does not work #2388

### PR DESCRIPTION
**Pull request by mneiger**
replaced user_dn with username as property to check for group membership in ldap.

### CODE REVIEW

**Comment by lachlan-00** [comment]
is distinguished name used in a specific ldap server? 

you could do a `(?=$user_dn|$username)` that would cover both?

**Comment by mneiger** [comment]
Notwithstanding the fact that I'm not able to check the exact PHP syntax, i agree that checking against both user_dn and username would make sense. My ldap server is openldap;  we should have someone using Active Directory and/or more proficient with LDAP give his 2 cents.
I'd be glad to adjust the pull request if you feel so.

**Comment by mneiger** [comment]
my latest findings:
I first thought it was an OpenLdap vs Active DIrectory directory difference, but it's not.
The member attribute array of a group can either store dn or uid (i.e. username)., For users, it usually stores the username rather than dn, dn is mainly used for nested groups.
Though we should theoretically have a more comprehensive code to deal with both case and nested groups, we would need someone actually knowledgeable about ldap or willing to investigate. I do not have the time and skills myself to go much further.

**Comment by lachlan-00** [comment]
i think we've had enough problems with groups that this will probably fix it.

If there are implementations of ldap that do it differently i'll make it a config option.

**Comment by lachlan-00** [comment]
> replaced user_dn with username as property to check for group membership in ldap.

Welcome as a new contributor to Ampache!

**Comment by mneiger** [comment]
Many thanks, this is actually my first real pull request on github. I'm proud it to be for ampache.

**Pull request merged**
