### PR TITLE
truncate song title to max 255 bytes, before insert into db

### PR DESCRIPTION
**Pull request by jleipsig**
fix for #2406

### CODE REVIEW

**Comment by lachlan-00** [comment]
we should do this for artist, album and title as well.

do you want to move sanitize_title to say lib/general and update the artist/album inserts as well?

happy to do it for you but i like people to have their contributions fully theirs.

**Comment by jleipsig** [comment]
Moved the `sanitize_title` function to `Catalog::check_length`, because most other sanitizing stuff is also in Catalog. After consulting the MYSQL documentation and some more testing (both a bit too late :)), I changed the check from max byte length to max character length.
Maybe I took it a bit too far, but the check is now added for artist, album_artist, album, composer, label, language, catalog_number and barcode :)

`Song::insert` and `Catalog::update_song_from_tags` have a lot of (almost) duplicate code.  `Catalog::update_song_from_tags` cleans lyrics before storage, `Song::insert` doesn't, resulting in unnecessary updates.
Also, when catalog_number or barcode are changed in file tags, `Catalog::update_song_from_tags` doesn't update them.

**Comment by lachlan-00** [comment]
I'll double check the database but if it covers it all then no problem.

**Comment by lachlan-00** [comment]
Thanks for all this work you're a bloody star.
i'm starting to go through these all now

**Pull request merged**
