### PR TITLE
Rating icons replaced by material SVG icon

### PR DESCRIPTION
**Pull request by Simounet**
I tried to look at every section containing the rating system but maybe I missed something. I removed the reset icon, you need to click on the current rated icon to remove your note.
I added to translation, not sure how you want me to handle that:
- T_('Reset rating')
- T_('Rate ' . $count)
- T_('Favorite')
- T_('Unfavorite')

### CODE REVIEW

**Comment by lachlan-00** [comment]
I'll check it out when I'm free again but I would say clear or remove

The text is stars and flag mostly so

%d star/s
Remove stars
Flag
Remove flag

**Comment by Simounet** [comment]
The "flag" wording looks weird to me because the app use "favorite".

**Comment by lachlan-00** [comment]
yeah that's fine i think i'm thinking more from the backend.

It looks good but i don't think we change the behaviour of clicking the star again to reset the value, i've added in the 0 stars button again. clicking the same icon will function as it did before and reset the star and apply plugins.

image

**Comment by lachlan-00** [comment]
what a banger pull though, brings it all together

**Pull request merged**
