### PR TITLE
Add a cache mechanism on user bandwidths

### PR DESCRIPTION
**Pull request by Niols**
This PR follows what has been said in issue #1322.
It adds a static variable in the User class, that is here to cache the result of bandwidth calculation. The first time a user needs it, it is calculated for all users. And after that, the value can be obtained without a SQL request.

On my instance, it save around 3 or 4 requests per page. According to what @madeye-matt said in issue #1322, it could save around 400 requests per page on large instances.
I believe that this pattern can be applied to more than bandwidth, reducing SQL traffic and speeding up Ampache (on my instance, Ampache is currently doing ~200 SQL request per page… I think that it's way too much).

I'm not really satisfied by this PR, this I don't like the use of static variables in dynamic classes.
However, this is to show that more consideration should be put into the caching of SQL requests.
By the way, I can see in Ampache footer that it counts the number of requests, cached requests and loading time. My cached requests number seems to always be 0. Does that mean that there's a way to add a SQL cache? Or that there used to be one that no longer exists? @Afterster, would you know anything about it?

### CODE REVIEW

**Comment by Phyks** [comment]
@Niols it looks like you included a lot of code style changes in this PR making it really large (kind of related to https://github.com/ampache/ampache/pull/1269.

Concerning extending this cache mechanism further, I would personnally say it is also related to the Laravel rewrite as this is something that would be a lot easier and faster to do at this time.

**Comment by Niols** [comment]
Yes, I ran PHP-CS-Fixer. I don't know why develop wasn't up-to-date with the codestyle in wiki.
I can remove this if needed.

About the Laravel rewrite, I totally agree. However, this rewrite isn't ready yet, and wont be for a long time, so I think that we still need to think about it

**Comment by Phyks** [comment]
> Yes, I ran PHP-CS-Fixer. I don't know why develop wasn't up-to-date with the codestyle in wiki.
> I can remove this if needed.

Hmm, codestyle settings have been updated recently, but the whole `develop` branch has not been set up to date with it, as per pull #1269 and related pull.

> About the Laravel rewrite, I totally agree. However, this rewrite isn't ready yet, and wont be for a long time, so I think that we still need to think about it

Sure, my point was just that it could be difficult, time consuming and hacky to implement it at the moment, and that we should take care to not waste too much time on optimizations if we plan a major rewrite, no?

**Comment by Afterster** [comment]
Well if this is small things and it is proposed in such simple PR, I'm not against it. Thanks @Niols.
But this should be done according to user caching setting (`memory_cache`) and using existing caching mechanisms, see https://github.com/ampache/ampache/blob/develop/lib/class/database_object.abstract.php#L111

**Pull request closed without merging**
