### PR TITLE
#2527 Playlist duration added to UI

### PR DESCRIPTION
**Pull request by theTendo**
Initially, it was added as a column in `show_playlists.inc.php`, however, after user feedback, it has been changed to be shown inside `show_playlist_medias.inc.php` for a better look.

note 1: It works both for normal playlists and smart playlists.
note 2: In case the duration is >86400 seconds (a day) the hour format takes in all the extra hours i.e. 99728s = 27:42:08.

### CODE REVIEW

**Comment by lachlan-00** [comment]
Thanks for posting this one, i'll be able to test and merge after work!

**Comment by lachlan-00** [comment]
for large lists are these hour minutes seconds still?
image


only other thing left to check is the duration for searches is setting the duration after displaying, i can probably do that but have had to go home early today for family stuff.

**Comment by theTendo** [comment]
> for large lists are these hour minutes seconds still?
> image

Yep, the example from your screenshot would represent 1006 hours, 46 minutes and 0 seconds

> only other thing left to check is the duration for searches is setting the duration after displaying, i can probably do that

Okay, nice 👍

> have had to go home early today for family stuff

No problem, family is more important than this :)

**Comment by lachlan-00** [comment]
okay, we're done here. i see where it's happening now.

when you 'browse' a list you run a search but we just keep an array of objects instead of the search/playlist. so we need to set a duration at the browse time instead of relying on the search/playlist count as the objects will probably not match.
image


last_duration in this respect is actually a second search after the original browse.

Thanks for doing the leg work on this it was actually really good to follow up and work on the code in this area. Now you're the 101st Ampache contributor!

**Pull request merged**
