### PR TITLE
 Fix: Unable to update album info #2141 

### PR DESCRIPTION
**Pull request by Rhythm-of-Time**
New Albums / Artists can be created and existing artists or album can be assigned to songs.

Some fine-tuning to be done - a lot of debug messages still there, and maybe the Song Edit Dialog needs a little work if the meta tags for Artist and Song ID should be updated by AJAX to reflect changes made in the dropdown.

Sorry for the large quantity of commits - I am still practising using Github. Only tools.js and song.class.php are needed for the fix - that is, the last two commits.

### CODE REVIEW

**Comment by lachlan-00** [comment]
I can squash and play around with the commits so don't work too much about that.

An easy fix is to copy the changes out of your repo and do a reset.
Then you copy the changes files back in after for a single commit

git reset --hard upstream/develop
git push origin develop --force

These commands may be wrong. I'm not home for another day

**Comment by Rhythm-of-Time** [comment]
Thanks for the advice, using the command line is much easier than using Github Dektop (on Windows) which also creates troubles of it own sometimes. Didn't dare to use reset --hard, now I know how to deal with the files. Backing up outside of a repo is always a good thing...

**Comment by lachlan-00** [comment]
okay, all tested now. see what happens when you contribute? you get the bug for it.

**Comment by lachlan-00** [comment]
The commands above should work to reset your local repo to the correct commits. just make sure you pull first
```
// make sure the ampache upstream url is available
git remote set-url upstream https://github.com/ampache/ampache.git
git pull
```
```
// This will reset to Ampache\develop
git reset --hard upstream/develop
```
```
// This will overwrite Rhythm-of-Time:origin/develop to develop based on your reset
git push origin develop --force
```

**Comment by Rhythm-of-Time** [comment]
Thanks. Worked like charm.

**Pull request merged**
