### PR TITLE
p-chart is released under gplv3

### PR DESCRIPTION
**Pull request by lachlan-00**
restore it.

### CODE REVIEW

**Comment by wagnered** [comment]
@lachlan,

PChart is dual licensed; ampache.org cannot change that.

I don't remember the exact details, maybe you do, but someone wanted to create a package to include with one of the Linux distributions.  He was refused because of this dual license situation.  I think it might have been Fedora.

Until pChart is replaced by chart.js or other open-source charting library, I would like to suggest that pChart be  enabled on the admin tab with the user being required to acknowledge that for commercial use, a commercial license must be purchased, and point to http://www.pchart.net/license for details and to purchase a commercial license.

I suggest this to reduce the potential for ampache.org becoming involved in legal issues.



-------- Original message --------
Subject: Re: [ampache/ampache] p-chart is released under gplv3 (#2175)

**Comment by lachlan-00** [comment]
It is definitely dual licensed still but has changed from MIT to gplv3 since that issue.

Graphs are disabled by default requiring config to enable so it could go in there.

I need to do more research in the reasoning behind the fedora packaging with dual licensing as I don't think a lot of the restrictions apply to Ampache itself.

**Comment by wagnered** [comment]
The [Fedora docs](https://docs.fedoraproject.org/en-US/quick-docs/setup_rpmfusion/) might shed some light on that.

I think someone at pChart finally decided to look at the wording of the of the MIT is excludes any attempt to impose copyright or proprietary clauses to the conditions of usage.

**Comment by lachlan-00** [comment]
I've reopend the issue #1515 and put it to debian maintainers of the old versions as well.

I think to avoid all this i'll separate c-pchart package from the base composer and detail the extra requirements to enable in the config and wiki. that way it's not included in the base install without multiple manual steps.

**Pull request merged**
