### PR TITLE
Solve #768

### PR DESCRIPTION
**Pull request by thegeekrv**
Solve bug #768

### CODE REVIEW

**Comment by jpbaril** [comment]
I perhaps did not test the fix correctly (I manually changed the css value with firebug), but that did not fix it. In my view, the bug relies in the fact that 'position: fixed' is used and that the top position is not modified in the same way that the 'rightbar' div top value is modified when scrolling the browser window.

**Comment by thegeekrv** [comment]
I see where is the problem, I ll fix it maybe this afternoon, or later :)

**Comment by thegeekrv** [comment]
Ok, now it's ok :)

**Comment by jpbaril** [comment]
Seems OK.
Often, when trying to move cursor over the submenu, the submenu disappear like if there was a gap between the menu and submenu, but I think it's another bug.

**Comment by thegeekrv** [comment]
I think it's because of the border...

**Comment by Afterster** [comment]
Looks fine to me too, thanks.
@SUTJael, as you did this css part, could you give some hints on your choices to @jpbaril? Thanks!

**Comment by thegeekrv** [comment]
You are welcome :)

**Comment by jpbaril** [comment]
@thegeekrv I tried removing the border and still got the problem.

I took the time to recheck the fix and as I mentioned, I think that even if visually it seems like the bug is fixed, I think that unfortunately it is not completely solved.

I used Firebug to change the background color of the submenu (for sake of visual clarity while testing) and indeed, there is a gap between the menu items and the submenu, which is obviously the source of the problem. Now, why it does not always happen is beyond me.
capture d ecran 2015-03-21 a 18 38 28

In the end, this bug will need more work. Unfortunately my CSS is very far so I cannot say at this moment what should be changed.

**Comment by jpbaril** [comment]
I think I found it.

I think the gap is the "line-height" of the <li> in the menu (rb_action <ul>).

**Pull request merged**
