### PR TITLE
Feature: Import Artist images from file tags.

### PR DESCRIPTION
**Pull request by wagnered**

### CODE REVIEW

**Comment by lachlan-00** [comment]
ah cool, this is a pretty good idea. the image 8 is artist and 3 is front/cover?

**Comment by lachlan-00** [comment]
just looked it up here. https://en.wikipedia.org/wiki/ID3#ID3v2

that's going to help a lot of obsessive taggers. i should start putting artist in mine as well.

**Comment by wagnered** [comment]
yea, all that good id3 info for every version can be found at id3.org.

I've been entertaining the idea of importing other picture types such as $13, the band or artist's  logo,  $0F photo from performance.

**Comment by wagnered** [comment]
There is an image "kind" column that is hard-coded to 'defaut' which might be used in some way.  Also, there seems to be plenty room for more images on the artist or album page even on my 6 " display.

**Comment by lachlan-00** [comment]
performance would be good for boots?

I've only ever put front on my files but would the other types be popular?

**Comment by wagnered** [comment]
I believe that a favorite band's logo might be popular.  An audiophile of classic music might have a favorite conductor.

**Comment by wagnered** [comment]
Most taggers offer only covers. Easy tag will mass insert any type of valid  images, but does not search for anything but front covers I think.

**Pull request merged**
