### PR TITLE
Fix registration page styles

### PR DESCRIPTION
**Pull request by kuzi-moto**
These fixes should solve the problems in #1990 and #1988, and I have to say, it looks beautiful now! Unfortunately it probably wont get much use but such is life.

Some shots of what it looks like:

image
image
image

### CODE REVIEW

**Comment by kuzi-moto** [comment]
One thing I wanted to look into further, is if we enable administrator activation, as well as email verification, if Ampache will actually require both before the user can sign in.

**Comment by lachlan-00** [comment]
I'll enable registration and confirm.

Users would start disabled so enabling both would probably mean that whichever does it first would enable them?

**Comment by kuzi-moto** [comment]
If both are enabled, would we want to make sure that both are done before they can log in? Otherwise, just throw a notification or something saying that they need to verify the email still. I can see reasons you would want to ensure valid emails.

Also, this needs a little tweaking. One of my changes to the css broke things once logging in.

**Comment by lachlan-00** [comment]
It might be better to not enable the user when these are set then notify the admin somehow. (A PM +/or email)

So, User registers -> email sent to user -> user confirms -> admin notified to manually enable the user as they have confirmed their email.

**Comment by kuzi-moto** [comment]
Okay, I have completed all my changes and pretty much overhauled much of the styles for the login, registration, and lost password pages. Here's a list of some tweaks:

* Generally simplified the CSS in default.css
* added `.alert-danger` class to actually change the color of an alert. Before the text sort of blended in with other text
* Looks much better on mobile devices
* Changed footer for lost password page to mach others
* Added color to asterisk on registration page
* Login page: made login button same line as "remember me" checkbox. Moved "Lost password" and "Register" buttons below the login.
* Did the same thing for register page, and accepting the user agreement.
* lots of little style tweaks to register page.
* Changed the confirmation text for registration depending on what was set in config.
* Possibly some other small things.

**Comment by lachlan-00** [comment]
run cs over that and you're done.

I'll need to sit down tonight and get all this recent stuff merged as well as the extra checks in #1989

**Comment by kuzi-moto** [comment]
I did, for some reason it's not showing here :/

**Comment by lachlan-00** [comment]
okay that's no problem, i'll pull it onto my debian desktop at home when i add in the 1989 checks.

**Comment by lachlan-00** [comment]
it's fixed in the repo so it's travis that's locked.

**Comment by lachlan-00** [comment]
very slick looking now. The pages won't be shown unless mail_enabled is also true which means it must be manually enabled to allow registration.

**Pull request merged**
