### PR TITLE
crop images from the centre instead of resizing into a square

### PR DESCRIPTION
**Pull request by mitchray**
First change is to keep aspect ratio of original images during art selection

art-selection

Second is to crop non-square images from the centre (or slightly above centre for portrait images making the assumption that faces would most likely be higher), instead of squashing the image into being a square. This does mean there is a possibility of faces being cut off but I feel that is better than distorted images

before-after

### CODE REVIEW

**Comment by lachlan-00** [comment]
haven't checked with the new commit (will later) but image search would not insert the image after selecting one with the first one.

**Comment by mitchray** [comment]
It was working fine prior I just thought it best to be thorough, is it failing for any attempt or some specific artists?

**Comment by lachlan-00** [comment]
i'll make sure i clean up my server and try again. it may have been from other work i was doing

**Comment by lachlan-00** [comment]
looking good now, must have just been me. just pulled and merged with develop so no issue now
image

**Pull request merged**
