### PR TITLE
Added "case 'tv_episode':" to "function _cleanup_quicktime($tags)".

### PR DESCRIPTION
**Pull request by wagnered**
Cleaned "tv_episode" into $parsed['tvshow_episode'] to store episode number.

### CODE REVIEW

**Comment by Afterster** [comment]
Is `tvshow_episode` an official quicktime tag? Do you have a link just for my knowledge? Thanks.

**Comment by wagnered** [comment]
Sure. Check 

https://code.google.com/p/mp4v2/wiki/iTunesMetadata

and

http://atomicparsley.sourceforge.net/mpeg-4files.html


The tag symbol 'tves' (TV episode number) is parsed as valid data by
getID3: That seems to tell me that it is a valid tag.

Also, I have advised the getID3 team that 'tven' (TV episode name (ID))
is ignored and reported as a warning:  I would like to eventually use it
instead of the series title which is used now.

Also, I asked the team to include 'hdvd' which indicates hd video.  The
MetaX app from DanHinsley.com uses it to indicate 720 or 1080 video. I
refer to the MetaX app because Dan Hinsley, in email communications
advised me that he precisely follows the iTunes specs.

I ,myself, would feel more comfortable if I could acquire the original
source documents for this information.


-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by Afterster** [comment]
Ok thanks for the details.
Could you fix your code style (tab / spaces here I believe, see travis build error)? So you can see how it works for the next PR ;)

**Comment by wagnered** [comment]
I guess you are referring to:


php-cs-fixer.phar fix -v
--fixers=indentation,linefeed,trailing_spaces,short_tag,braces,controls_spaces,eof_ending,visibility .

I forgot about that .phar utility.  I've gone through so many re-clones
of ampache that I lost track of it.

Also, ironically, I just ran it on my local file and there was only
(eof_ending) on the config file. Maybe I absentmindedly fixed the
indentation problem after committing.


-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by wagnered** [comment]
So where does that leave the status of my own fork? Should I reset that commit on my side?

Actuallly, I discovered some more additions to that switch are needed that were hidden by another bug. (Without filename in "metadata_order_video" tvshow and tvshow_season were left null.)

So, if I can reset the commit, I would like to issue one that includes all the needed changes at the same time.

**Comment by Afterster** [comment]
In fact you just have to commit your change on your branch. If these changes are fix on your PR you should clean your commits locally and force push on the remote branch, the PR will be updated automatically ^^.

**Comment by Afterster** [comment]
Ok looks fine now. Any more addition or can I merge?

**Comment by wagnered** [comment]
That takes care of importing/displaying the season/episode numbers and
tv show name correctly from mp4 files and can now be merged.

For my own use, I'm considering changing the title that is displayed on
the season/episodes view page from the show's title to the episode's
title if available. Also, because kids may be accessing the TV shows and
movies, I am going to include the ability to import/display content
ratings. If those features seem acceptable to a production version of
Ampache, I'll merge the features into the Ampache develop branch.   

But that's for a different discussion here or on the Google forum.


-- 
73 From Ernie D

AA1AD | CN87ug 

-----Original Message-----

**Comment by Afterster** [comment]
Ok, thanks!
Your other PR will be welcome, content rating for instance is something on the todo list (it should also be imported from external metadata services too) so it would be great :)

**Pull request merged**
