### PR TITLE
Changed tvshow.summary to tvshow.overview to remove

### PR DESCRIPTION
**Pull request by wagnered**
conflict with tvshow_episode.summary.
Modified edit dialog and update functions to edit tvshow.overview.
Modified tvdb and tmdb plugins to reflect change to tvshow.overview.
Fixed Vainfo::_parse_filename after regression tests exposed bug.

### CODE REVIEW

**Comment by Afterster** [comment]
Thanks. Looks ok but can't we just rename `summary` for tvshow to `tvshow_summary` inside plugins results and still keep `summary` as the db field name? I don't see a reason why this should be named `overview` here, the conflict is only when getting metadata from plugins, isn't it?
If I'm wrong, then you should also update https://github.com/ampache/ampache/blob/develop/lib/class/tvshow.class.php#L29 to `overview` (and refs to this var), but if I'm right then no need to change the db or classes but only plugins and their handling.

**Comment by wagnered** [comment]
First, "overview" is how it is labeled at the point that the tmdb plugin
fetches it.

Second, It is a more accurate description of the data as it describes
with more details, the entire set of episodes/seasons.

Third, I really didn't catch it until a few days ago and just recently
made the change to the variable tvshow.summary to tvshow.overview. :'{ I
forgot to submit the change to the PR.

I guess my rational is for  accuracy and consistency in labeling.

BUT, if there exists some rational for not changing the column name from
summary, to overview, I will gladly make the necessary changes from
"overview" to "tvshow_summary" in all the affected classes.


On 11/26/2015 11:39 AM, Afterster wrote:
> Thanks. Looks ok but can't we just rename |summary| for tvshow to
> |tvshow_summary| inside plugins results and still keep |summary| as the
> db field name? I don't see a reason why this should be named |overview|
> here, the conflict is only when getting metadata from plugins, isn't it?
> If I'm wrong, then you should also update
> https://github.com/ampache/ampache/blob/develop/lib/class/tvshow.class.php#L29
> to |overview| (and refs to this var), but if I'm right then no need to
> change the db or classes but only plugins and their handling.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/pull/1022#issuecomment-159984062>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
OK, I reverted the change to tvshow.overview back to tvshow.summary.

**Comment by Afterster** [comment]
Thanks @wagnered :smile:. Merged!

**Comment by wagnered** [comment]
Noticed problem with vainfo.class.php after fetching upstream to update my local and fork.  It seems that somehow I added an unclean merged file. I cleaned up the file but then ampache failed. I'm getting a blank screen.

 I'm debugging it now it now and will keep at it until I find out what is wrong. The Eclipse IDE doesn't indicate serious errors (only cvc type 3.1.3 errors which were not a problem before.)
So I'll step through it until I find the exception.

**Comment by wagnered** [comment]
Found the problem:  Another vendor was added and I didn't realize it. Ampache is working now.

**Pull request merged**
