### PR TITLE
Update upnpplayer.class.php

### PR DESCRIPTION
**Pull request by jahak7**

### CODE REVIEW

**Comment by Afterster** [comment]
Thanks @jahak7 but any reason for such changes?

**Comment by jahak7** [comment]
@Afterster https://secure.php.net/manual/ru/function.is-null.php#84161

**Comment by jahak7** [comment]
@Afterster Micro optimization

**Comment by jahak7** [comment]
@Afterster https://gist.github.com/jahak7/52856ec4a9cb54792305

**Comment by Afterster** [comment]
This is really micro optimization, I don't think Ampache is at this level of performance to see a difference. I generally prefer to lost few nanoseconds and have a better code btw.
But here `is_null` or `=== null` doesn't really matter for code readability, I'm gonna merge your PRs thanks ;).

**Comment by jahak7** [comment]
@Afterster Thank you for ampache :)

**Pull request merged**
