### PR TITLE
fix wrong translation

### PR DESCRIPTION
**Pull request by teknoraver**
`Disabilitato` means `disabled`, not `disable`

### CODE REVIEW

**Comment by mitchray** [comment]
Unfortunately that file you edited is a compiled file, all translations need to be done through Transifex: https://www.transifex.com/ampache/ampache/

If you are able to make an account there and update the translation it would be most helpful

**Comment by lachlan-00** [comment]
Thanks for creating @teknoraver. Transifex acts as the translation source and is merged back into Ampache from there every month or so.

If you join the team and make your changes there it will be merged back in.

**Comment by teknoraver** [comment]
joined, fixed

**Comment by lachlan-00** [comment]
thanks for helping us out!

**Pull request closed without merging**
