### PR TITLE
Translation Update March 2022

### PR DESCRIPTION
**Pull request by Psy-Virus**
Translation Update March 2022

### CODE REVIEW

**Comment by lachlan-00** [comment]
@Psy-Virus with 982ff9c28 i've found that some of the xhtml templates do not have php T_() translations so they will have been dropped from transifex.

I've updated gather messages and added a text file with the missing strings. i'll do another quick check to make sure strings are in.

if i update the pot file that should sync with transifex?

**Comment by Psy-Virus** [comment]
Yepp, Transifex pulls the pot in some interval automatically if changed.
But wouldn't it make more sense to put the ```xhtmltxt='../../resources/untranslated-strings.txt'``` into the ```locale/base``` dir to keep all the translation stuff together?

**Comment by lachlan-00** [comment]
i was thinking to keep it with the templates in resources but either way is fine with me so i can put it there.

**Comment by lachlan-00** [comment]
moved and set with a42e4dd40

**Pull request merged**
