### PR TITLE
Fix header

### PR DESCRIPTION
**Pull request by kuzi-moto**
I cannot remember why I added this... but it looks like it breaks the header from one of the latest commits.

### CODE REVIEW

**Comment by lachlan-00** [comment]
this one?
image

Do you know what it's doing? i can't really see anything out of the ordinary

**Comment by kuzi-moto** [comment]
Yeah, for some reason I didn't see it right away but when logged in the search bar section is aligned to the left, rather than the ride side.

**Comment by lachlan-00** [comment]
Ahh, now i see it.

want to stick it in #2004 and i'll merge it tonight?

**Comment by lachlan-00** [comment]
closing, put the revert in the other open request editing default.css

**Pull request closed without merging**
