### PR TITLE
Api5 (WIP)

### PR DESCRIPTION
**Pull request by lachlan-00**
just want to check issues in the code before merging, still a lot more to do.

* objects to return instead of empty arrays
* errors instead of empty data
* check new methods

### CODE REVIEW

**Comment by usox** [comment]
Oh my. This will be a huge merge party in source-changes :laughing:

**Comment by lachlan-00** [comment]
it was too big a change to just dump into develop. I'm going to try and cause less heart attacks than i did with 4.0.0!

after it's done i'll move into source-changes on my main server full time.

**Comment by usox** [comment]
I'll keep my fingers away from the api methods in source-changes until you're done.

**Comment by lachlan-00** [comment]
> I'll keep my fingers away from the api methods in source-changes until you're done.

 definitely, I've already changed my mind a few times today but should be done this week

**Comment by lachlan-00** [comment]
@AshotN here's something that i'm looking at changing.

for the below, each xml album comes in as an album object
```
<?xml version="1.0" encoding="UTF-8" ?>
<root>
    <album id="57887">
        <name><![CDATA[(It (Is) It) Critical Band]]></name>
        <artist id="9205"><![CDATA[90 Day Men / GoGoGoAirheart]]></artist>
        <year>2000</year>
        <tracks>8</tracks>
        <disk>1</disk>
        <tag id="674" count="1" ><![CDATA[Math Rock]]></tag>
        <tag id="1415" count="1" ><![CDATA[Post Rock]]></tag>
        <art><![CDATA[https://music.com.au/image.php?object_id=57887&object_type=album&auth=eeb9f1b6056246a7d563f479f518bb34]]></art>
        <flag>0</flag>
        <preciserating></preciserating>
        <rating></rating>
        <averagerating></averagerating>
        <mbid><![CDATA[d6fc36cc-9351-4b53-b7db-7f5b30804800]]></mbid>
    </album>
</root>
```

JSON comes in as an array
```
[
    {
        "id": "57887",
        "name": "(It (Is) It) Critical Band",
        "artist": {
            "id": "9205",
            "name": "90 Day Men \/ GoGoGoAirheart"
        },
        "year": "2000",
        "tracks": "8",
        "disk": "1",
        "tag": [
            {
                "id": "674",
                "name": "Math Rock"
            },
            {
                "id": "1415",
                "name": "Post Rock"
            }
        ],
        "art": "https:\/\/music.com.au\/image.php?object_id=57887&object_type=album&auth=eeb9f1b6056246a7d563f479f518bb34",
        "flag": "0",
        "preciserating": null,
        "rating": null,
        "averagerating": null,
        "mbid": "d6fc36cc-9351-4b53-b7db-7f5b30804800"
    }
]
```

Should this be returning album objects? it seems like that would be a lot easier to handle if i documented each json/xml response with the same object name and also a good time to make this change in api5

**Comment by lachlan-00** [comment]
For documentation i'm thinking something like the element and children being returned? @usox and @wagnered, @kuzi-moto do you have an extra thoughts about this? I'm going to fully document the current methods before making more changes.

I'm happy to keep things in arrays for json as long as we document what does and doesn't have objects.

**But** I would like to make sure that anything with an ID in the database comes back in an object. that way we can nest things and document a bit better by saying "album will return nested song if included".

once this is done i'll start creating more links to examples.

These 2 examples are the sort of shell docs i'm shooting for

### handshake (json)

This is the function that handles verifying a new handshake Takes a timestamp, auth key, and username.

```
@param array $input
@return array (
          "auth",
          "api",
          "session_expire",
          "update",
          "add",
          "clean",
          "songs",
          "albums",
          "artists",
          "playlists",
          "videos",
          "catalogs"
        )
@throws "error"
```

### handshake (xml)

This is the function that handles verifying a new handshake Takes a timestamp, auth key, and username.

```
@param array $input
@return <root>
            <auth>
            <api>
            <session_expire>
            <update>
            <add>
            <clean>
            <songs>
            <albums>
            <artists>
            <playlists>
            <videos>
            <catalogs>
        </root>
@throws <error>
```

**Comment by lachlan-00** [comment]
https://github.com/ampache/ampache.org-api/blob/master/content/api-xml-methods.md

**Comment by lachlan-00** [comment]
TODO
advanced search  'playlist', 'label', 'user', 'video' objects won't be returned

**Pull request merged**
