### PR TITLE
Multi-artist support for API calls

### PR DESCRIPTION
**Pull request by mitchray**
For JSON I've added a new ```artists``` array which also includes the artist MBID since there was (and still is) a separate ```artist_mbid```

For XML there will be extra ```<artist>``` entries, each with its own MBID

Have left in the  ```artist_mbid``` (and single ```artist``` for JSON) for the time being, I'm guessing it should be left in for compatibility but nows the time to break things!

Examples:
```json
 {
    "id": "34687",
    "title": "Enth E Nd (feat. Motion Man)",
    "name": "Enth E Nd (feat. Motion Man)",
    "artist": {
        "id": "2503",
        "name": "Kutmasta Kurt",
        "prefix": null,
        "basename": "Kutmasta Kurt"
    },
    "artists": [
        {
            "id": "2503",
            "name": "Kutmasta Kurt",
            "prefix": null,
            "basename": "Kutmasta Kurt",
            "mbid": "abf9f319-da2f-4fdf-a3e4-40c4d0b0075d"
        },
        {
            "id": "2504",
            "name": "Motion Man",
            "prefix": null,
            "basename": "Motion Man",
            "mbid": "1cee1f74-179d-446d-8347-de31e8202f2b"
        }
    ],
    ...
    ...
    ...
    "artist_mbid": "abf9f319-da2f-4fdf-a3e4-40c4d0b0075d",
}
```

```xml
<song id="34687">
    <name><![CDATA[Enth E Nd (feat. Motion Man)]]></name>
    <title><![CDATA[Enth E Nd (feat. Motion Man)]]></title>
    <artist id="2503">
      <name><![CDATA[Kutmasta Kurt]]></name>
      <prefix><![CDATA[]]></prefix>
      <basename><![CDATA[Kutmasta Kurt]]></basename>
      <mbid><![CDATA[abf9f319-da2f-4fdf-a3e4-40c4d0b0075d]]></mbid>
    </artist>
    <artist id="2504">
      <name><![CDATA[Motion Man]]></name>
      <prefix><![CDATA[]]></prefix>
      <basename><![CDATA[Motion Man]]></basename>
      <mbid><![CDATA[1cee1f74-179d-446d-8347-de31e8202f2b]]></mbid>
    </artist>
    ...
    ...
    ...
    <artist_mbid><![CDATA[abf9f319-da2f-4fdf-a3e4-40c4d0b0075d]]></mbid>
</song>
```

### CODE REVIEW

**Comment by lachlan-00** [comment]
do you need mbid when you have the id?

**Comment by mitchray** [comment]
Personally no, I was just going by the existing data

I can remove the mbid stuff, should I also remove the ```artist_mbid```?

**Comment by lachlan-00** [comment]
i would either include it in name array or not. unless it's really needed for display or something else it's just an extra call to make per item?

**Comment by mitchray** [comment]
Sweet I'll purge them 😈

**Comment by mitchray** [comment]
Should be good now

```json
{
    "id": "34687",
    "title": "Enth E Nd (feat. Motion Man)",
    "name": "Enth E Nd (feat. Motion Man)",
    "artists": [
        {
            "id": "2503",
            "name": "Kutmasta Kurt",
            "prefix": null,
            "basename": "Kutmasta Kurt"
        },
        {
            "id": "2504",
            "name": "Motion Man",
            "prefix": null,
            "basename": "Motion Man"
        }
    ],
    "album": {
        "id": "4424",
        "name": "Reanimation",
        "prefix": null,
        "basename": "Reanimation"
    },
    "albumartist": {
        "id": "2016",
        "name": "Linkin Park",
        "prefix": null,
        "basename": "Linkin Park"
    },
    "disk": 1,
    "track": 3,
    "filename": "\\\\tower\\multimedia\\music\\MR\\L\\Linkin Park\\Reanimation [2002]\\03 - Enth E Nd.opus",
    "genre": [
        {
            "id": "36",
            "name": "Alternative Rock"
        },
        {
            "id": "38",
            "name": "Nu Metal"
        }
    ],
    "playlisttrack": 1,
    "time": 239,
    "year": 2002,
    "format": "opus",
    "stream_format": "opus",
    "bitrate": 169263,
    "stream_bitrate": 169263,
    "rate": 48000,
    "mode": "vbr",
    "mime": "audio\/ogg; codecs=opus",
    "stream_mime": "audio\/ogg; codecs=opus",
    "url": "http:\/\/ampache-preview\/play\/index.php?ssid=3936168b76b12285acdfeeb991e2a6f1&type=song&oid=34687&uid=2&player=api&name=Kutmasta%20Kurt%20-%20Enth%20E%20Nd%20-feat.%20Motion%20Man-.opus",
    "size": 5107675,
    "mbid": "af9b3327-58ee-4151-8a9e-8e18030175e6",
    "art": "http:\/\/ampache-preview\/image.php?object_id=4424&object_type=album&auth=3936168b76b12285acdfeeb991e2a6f1",
    "flag": false,
    "rating": null,
    "averagerating": null,
    "playcount": 2,
    "catalog": 4,
    "composer": "J. Hahn\/B. Delson\/R. Bourdon\/M. Shinoda\/C. Bennington",
    "channels": 2,
    "comment": "Produced by Mike Shinoda. Mixed by Mark 'Spike' Stent at Olympic Studios, London. Assisted by David Treahem. Protools engineer: Paul 'P-Dub' Walton.",
    "license": null,
    "publisher": "Warner Bros. Records",
    "language": "eng",
    "lyrics": "",
    "replaygain_album_gain": null,
    "replaygain_album_peak": null,
    "replaygain_track_gain": null,
    "replaygain_track_peak": null,
    "r128_album_gain": 0,
    "r128_track_gain": 477
}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <total_count>17166</total_count>
  <song id="34687">
    <name><![CDATA[Enth E Nd (feat. Motion Man)]]></name>
    <title><![CDATA[Enth E Nd (feat. Motion Man)]]></title>
    <artist id="2503">
      <name><![CDATA[Kutmasta Kurt]]></name>
      <prefix><![CDATA[]]></prefix>
      <basename><![CDATA[Kutmasta Kurt]]></basename>
    </artist>
    <artist id="2504">
      <name><![CDATA[Motion Man]]></name>
      <prefix><![CDATA[]]></prefix>
      <basename><![CDATA[Motion Man]]></basename>
    </artist>
    <album id="4424">
      <name><![CDATA[Reanimation]]></name>
      <prefix><![CDATA[]]></prefix>
      <basename><![CDATA[Reanimation]]></basename>
    </album>
    <albumartist id="2016">
      <name><![CDATA[Linkin Park]]></name>
      <prefix><![CDATA[]]></prefix>
      <basename><![CDATA[Linkin Park]]></basename>
    </albumartist>
    <disk><![CDATA[1]]></disk>
    <track>3</track>
    <genre id="36">
      <name><![CDATA[Alternative Rock]]></name>
    </genre>
    <genre id="38">
      <name><![CDATA[Nu Metal]]></name>
    </genre>
    <filename><![CDATA[\\tower\multimedia\music\MR\L\Linkin Park\Reanimation [2002]\03 - Enth E Nd.opus]]></filename>
    <playlisttrack>1</playlisttrack>
    <time>239</time>
    <year>2002</year>
    <format>opus</format>
    <stream_format>opus</stream_format>
    <bitrate>169263</bitrate>
    <stream_bitrate>169263</stream_bitrate>
    <rate>48000</rate>
    <mode><![CDATA[vbr]]></mode>
    <mime><![CDATA[audio/ogg; codecs=opus]]></mime>
    <stream_mime><![CDATA[audio/ogg; codecs=opus]]></stream_mime>
    <url><![CDATA[http://ampache-preview/play/index.php?ssid=3936168b76b12285acdfeeb991e2a6f1&type=song&oid=34687&uid=2&player=api&name=Kutmasta%20Kurt%20-%20Enth%20E%20Nd%20-feat.%20Motion%20Man-.opus]]></url>
    <size>5107675</size>
    <mbid><![CDATA[af9b3327-58ee-4151-8a9e-8e18030175e6]]></mbid>
    <art><![CDATA[http://ampache-preview/image.php?object_id=4424&object_type=album&auth=3936168b76b12285acdfeeb991e2a6f1]]></art>
    <flag>0</flag>
    <rating/>
    <averagerating/>
    <playcount>2</playcount>
    <catalog>4</catalog>
    <composer><![CDATA[J. Hahn/B. Delson/R. Bourdon/M. Shinoda/C. Bennington]]></composer>
    <channels>2</channels>
    <comment><![CDATA[Produced by Mike Shinoda. Mixed by Mark 'Spike' Stent at Olympic Studios, London. Assisted by David Treahem. Protools engineer: Paul 'P-Dub' Walton.]]></comment>
    <license><![CDATA[]]></license>
    <publisher><![CDATA[Warner Bros. Records]]></publisher>
    <language>eng</language>
    <lyrics><![CDATA[[ti:Enth E Nd (feat. Motion Man) (Kutmasta Kurt Reanimation)]<br />[ar:Linkin Park/Motion Man]<br />[al:Hybrid Theory (20th Anniversary Edition) (Explicit)]<br />[by:]<br />[offset:0]<br /><br />[00:00.00]Enth E Nd (Kutmasta Kurt Reanimation) [feat. Motion Man] - Linkin Park (林肯公园)/Motion Man<br />[00:05.41]Lyrics by：Bradford Philip Delson/Chester Charles Bennington/David Michael Farrell/Joseph Hahn/Michael Kenji Shinoda/Robert Gregory Bourdon<br />[00:10.82]Hey yo when this first started off it was just Linkin Park<br />[00:14.96]<br />[00:17.19]And then in the middle came Motion Man<br />[00:20.73]<br />[00:22.12]And at the end of it all it was KutMasta Kurt with a remix<br />[00:26.60]<br />[00:27.80]One thing I don't know why<br />[00:29.69]It doesn't even matter how hard you try<br />[00:31.92]Keep that in mind I designed this rhyme<br />[00:34.17]When I was obsessed with time<br />[00:35.50]All I know time was just slipping away<br />[00:38.77]And I watched it count down to the end of the day<br />[00:41.10]Watched it watch me and the words that I say<br />[00:43.14]The echo of the clock rhythm in my veins<br />[00:45.21]I know that I didn't look out below<br />[00:47.84]When I watched the time go right out the window<br />[00:50.31]Trying to grab hold trying not to watch<br />[00:52.56]I wasted it all on the hands of the clock<br />[00:55.17]But in the end no matter what I pretend<br />[00:57.21]The journey is more important than the end or the start<br />[00:59.53]And what it meant to me will eventually be a memory<br />[01:02.17]Of a time when I tried so hard<br />[01:03.60]I tried so hard and got so far<br />[01:07.95]But in the end it doesn't even matter<br />[01:11.96]I had to fall to lose it all<br />[01:16.93]But in the end it doesn't even matter<br />[01:22.21]Ay yo one thing I don't know why<br />[01:24.64]It doesn't even matter how hard you try<br />[01:26.90]Keep that in mind<br />[01:27.84]I designed this rhyme to explain in due time<br />[01:30.43]All I know hah I so-socialize<br />[01:33.65]Like the host of the party<br />[01:34.87]I spoke shaked and made eye contact<br />[01:36.81]Partied and toasted strong all that<br />[01:38.43]Northeast Southwest coast<br />[01:39.78]I'm staring out the window<br />[01:40.89]No opportunity to mingle<br />[01:42.56]I tried to sew it up you weaken your system<br />[01:44.43]And had to throw it up<br />[01:45.46]I brought you back into things<br />[01:46.77]Like imaginary man of your dreams<br />[01:48.42]You'd always seem to make it worth it<br />[01:50.28]I pig-skin I never nerf it<br />[01:51.65]You felt leather never pleather<br />[01:52.95]Real bringing the pleasure<br />[01:54.09]By any means it means I'm leaving your team<br />[01:56.21]Hell of a team man it seems<br />[01:57.59]But I tried so hard and got so far<br />[02:02.76]But in the end it doesn't even matter<br />[02:06.78]I had to fall to lose it all<br />[02:11.71]But in the end it doesn't even matter<br />[02:17.09]<br />[02:17.68]Linkin Park<br />[02:18.12]<br />[02:18.90]Remix<br />[02:19.93]Mo-Mo-Motion Man<br />[02:21.42]<br />[02:22.24]Linkin Park<br />[02:22.90]In the end<br />[02:24.28]Kutmasta Kurt<br />[02:26.74]Linkin Park<br />[02:27.31]<br />[02:28.24]Remix<br />[02:28.96]Mo-Mo-Motion Man<br />[02:30.43]<br />[02:31.43]Linkin Park<br />[02:32.06]In the end<br />[02:33.21]<br />[02:34.21]Kutmasta Kurt<br />[02:35.12]Remix<br />[02:35.71]One thing I don't know how<br />[02:37.71]It doesn't even matter when you look at it now<br />[02:39.81]'Cause when I designed this rhyme<br />[02:41.02]I was scared of it all scared to fall<br />[02:42.93]And hadn't even tried to crawl<br />[02:44.34]But I was forced to run with you mocking me<br />[02:47.25]Stopping me backstabbing me constantly<br />[02:49.50]Remembering all the times you fought with me<br />[02:51.75]Watch the clock now chock full of hypocrisy<br />[02:54.17]But now your mouth wishes it could inhale<br />[02:55.99]Every single little thing you said to make things fail<br />[02:58.24]Every single word you sputtered just to get your piece<br />[03:00.59]But it really doesn't matter to me<br />[03:02.31]'Cause from the start to the end no matter what I pretend<br />[03:05.06]The journey is more important than the end or the start<br />[03:07.49]And what it meant to me will eventually be a memory<br />[03:10.31]Of a time when I tried so hard<br />[03:11.49]I tried so hard and got so far<br />[03:15.99]But in the end it doesn't even matter<br />[03:19.83]I had to fall to lose it all<br />[03:24.83]But in the end it doesn't even matter<br />[03:29.75]In the end]]></lyrics>
    <replaygain_album_gain/>
    <replaygain_album_peak/>
    <replaygain_track_gain/>
    <replaygain_track_peak/>
    <r128_album_gain>0</r128_album_gain>
    <r128_track_gain>477</r128_track_gain>
  </song>
</root>

```

**Comment by lachlan-00** [comment]
seems much better without all the mbid's now

**Comment by lachlan-00** [comment]
i forgot album artists but adding them in now

**Pull request merged**
