### PR TITLE
Feature/translation spanish

### PR DESCRIPTION
**Pull request by xoxefdp**
- Updated spanish translation

- Update translate revision date for es_ES

### CODE REVIEW

**Comment by Psy-Virus** [comment]
The official way to send in translations is via [Transifex](https://www.transifex.com/ampache/ampache/dashboard/). This has some reasons.
 + Everything can be managed centralized as everyone is working with the same files and data.
 + There will be no conflicts when translations are updated.
 + And last but not least, we have an overview of how much is translated and how the reviewing state is.

So please @lachlan-00, revert this commit and @xoxefdp, please head over to transifex and commit your translations there, as we will have conflicts and maybe a bigger than needed mess, when I commit my next general translation update.


Thanks

**Comment by Psy-Virus** [comment]
We probably should put a warning into the wiki. Or more or less delete the manual way, as everyone with a browser can use Transifex.

**Comment by lachlan-00** [comment]
@Psy-Virus  reverted.

**Comment by lachlan-00** [comment]
I forgot to add I removed the manual parts of the translations from the wiki as well.

**Comment by Psy-Virus** [comment]
Muchas gracias

@xoxefdp, would you be willing to port your changes to Transifex? As I don't know if someone was active on Transifex in the time you created your version of the Spanish translation, I can't just upload it without killing someone's translations/improvements, sorry :(

It's still a pity that we don't have reviewers for the different languages. I was planning months ago to only update reviewed language strings, so we can be sure to get the best quality and who we can blame if something's messed up. :D

:)

**Comment by xoxefdp** [comment]
Yeah thats ok, i already created a transifex account for the port

**Comment by xoxefdp** [comment]
Is there a problem on transifex? I don't see any update

**Comment by Psy-Virus** [comment]
Welp, sry, my fault.
I somehow missed the Transifex mails and totally didn't think about checking for them.

I accepted your request.

Happy localizing!

:)

**Comment by xoxefdp** [comment]
Port done, however i'm not familiarized with the transifex process to review the translated strings

**Comment by Psy-Virus** [comment]
Well, it's pretty easy.
If you're familiar with the grammar of the language you're translating Ampache into, and want to do quality checking and stuff, you can become a reviewer and decide when a translation is perfect and mark it so.
That's then done on the same view where you edit the translations and save them. But instead of just saving them, you can also mark them as reviewed.

**Pull request merged**
