### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by wagnered**
Updated component installer and removed the php-cs-fixer package. This is a lot of work maintaining 2 repositories.  Especially since I hadn't updated it for about a year and a half.  When I "relieved" @Afterster, I just pushed directly to Ampache/Ampache.  

A little work was needed on my fork to bring it up to date which I needed to do  to push my changes to it.  I had originally cloned my local from the Ampache repo and needed to push it to my fork..

### CODE REVIEW

**Comment by lachlan-00** [comment]
Today is a great day. :)

**Comment by lachlan-00** [comment]
want me to rebase on your branch or squash them all in?

**Comment by wagnered** [comment]
Just squash them, I think.  It's been so long I can't remember if it'll cause the comment from my original commit to disappear.   I hope not. But that reminded me: I didn't update the

**Comment by wagnered** [comment]
Ok, now I don't mind if you squash it.

**Pull request merged**
