### PR TITLE
Translation Update

### PR DESCRIPTION
**Pull request by Psy-Virus**
As usual new translations from Transifex

### CODE REVIEW

**Comment by lachlan-00** [comment]
you usually merge right away, is there anything you need?

**Comment by Psy-Virus** [comment]
grafik

No merge without permissions :D
Thought maybe it's a bug. But I still can't merge...

**Comment by lachlan-00** [comment]
Okay, that shouldn't happen for you at all so let me fix it. I must have been too restrictive when allowing ashot and kuzi into the other branches

**Comment by lachlan-00** [comment]
I've explicitly given the dev group develop and master (I think)

Sorry for stopping that!

**Pull request merged**
