### PR TITLE
Fix typo: s/folowing/following/

### PR DESCRIPTION
**Pull request by gturri**

### CODE REVIEW

**Comment by Afterster** [comment]
@Psy-Virus is this ok to merge or conflict with transifex?

**Comment by apachemic** [comment]
>

**Comment by Psy-Virus** [comment]
Hey @Afterster, sorry for the late reply, my e-mail filter was broken -.-

If you only merge ` templates/error_page.inc.php` and discard the others, we won't have any problems. This correction will then be catched by the next general translation update. :-)

@gturri, sorry, that you made the work in the other files for nothing. :-(

:-)

**Comment by gturri** [comment]
@Psy-Virus no problem.

Here, I updated the PR.

**Comment by Psy-Virus** [comment]
Thank you! :tada:

**Pull request merged**
