### PR TITLE
Subsonic API: Added token authentication handling. It just returns an unsupported e…

### PR DESCRIPTION
**Pull request by SenorSmartyPants**
…rror.

I do not see a way to implement this without altering password storage in the database.

This could address issues #1389 #1352

### CODE REVIEW

**Comment by Phyks** [comment]
Did you check this is the only change to be 1.13.0 compatible?

I mean, if we merge this, we advertise Ampache to be compatible with Subsonic API v1.13.0, so I think we should implement the whole differences and not only the authentication part, to provide a correct user experience. Else, it is the client's fault (IMO) if he cannot check the version we of the API we offer, and adapt its UX to it.

**Comment by SenorSmartyPants** [comment]
I have not checked for all the features of 1.13.

That's something I want to do but haven't yet.

**Comment by Phyks** [comment]
OK. I think we should wait for this check prior to merging.

**Comment by SenorSmartyPants** [comment]
Checking API support http://www.subsonic.org/pages/api.jsp

API 1.12
Present
getAlbumList2 - musicFolderId parameter present in code
getPlayQueue - but not supported, throws error.
savePlayQueue - but not supported, throws error.

Missing
getSongsByGenre - musicFolderId parameter missing
getStarred - musicFolderId parameter missing. Code comments this method is not supported, but returns XML
getStarred2 - see getStarred
search2 - musicFolderId parameter missing
search3 - just passes thru to search2
createUser - musicFolderId parameter missing. Several other parameters are ignored. Assuming ampache doesn't support those properties
updateUser - entire method is missing (was added in 1.10.1)

**Comment by SenorSmartyPants** [comment]
Checking API support http://www.subsonic.org/pages/api.jsp

API 1.13
Present
getNewestPodcasts

Missing
getTopSongs

**Comment by SenorSmartyPants** [comment]
I pushed an update which removes the API bump to 1.13.0

API published in files now stays at 1.11.0

Now this change can be merged and work can be done separately to add 1.12.0 and 1.13.0 features.

**Comment by Afterster** [comment]
Thanks! Subsonic API evolved a lot since I implemented the backend... I didn't except that ^^.
This is a good temporary fix to have better error handling but #1389 #1352 should be keep in mind.

**Pull request merged**
