### PR TITLE
Handle ID3v2.3 and v2.4 better regarding multivalued lists

### LINKED ISSUE #1402: Multiple entries for the same artist
# Environment
- Ampache version: 98094ad2bd9152f68bfbc88a4f6887959cba6ad2
- Web server + version: IIS 8.5 + PHP 7.0.11
- Server operating system:Server 2012 R2

# Description

There are multiple entries for the same artist in my newly imported catalog, for instance.
image

I have tagged all my albums with MusicBrainz Picard, here are a few examples from the Afrojack list.
image
image
When looking these up in Picard the Artist MBID and name are the same.

The Spark on Album Forget the World
image

Dynamite on Album Forget the World
image

Dynamite on Album Hitzone 70
image

Does it have something to do with multiple Artists on one song?

### PR DESCRIPTION
**Pull request by SenorSmartyPants**
This should correctly handle removing duplicates even when v2.4 is being used. Fixes #1402

### CODE REVIEW

**Comment by Phyks** [comment]
I see in the associated issue you have made some tests of it. Did you test it manually or in some kind of automated way? If it was partly automated, merging some kinds of unit-tests on this could be useful.

**Comment by SenorSmartyPants** [comment]
I preformed some manual tests with a variety mp3s that I had. 

I'm not familiar with writing unit tests for PHP or this project. Are there some examples you can point me to. How would we handle test data (I'm thinking of MP3s, or would it just be string data in the unit test files?)

**Comment by Phyks** [comment]
Sadly we don't have much unit tests for Ampache at the moment. Not sure it is a priority to write some for this PR then. I am OK with these changes then, but could not test it in details. 

Only @Afterster can merge or not though. 

Le 24 octobre 2016 11:47:11 UTC-04:00, SenorSmartyPants <notifications@github.com> a écrit :
>I preformed some manual tests with a variety mp3s that I had. 
>
>I'm not familiar with writing unit tests for PHP or this project. Are
>there some examples you can point me to. How would we handle test data
>(I'm thinking of MP3s, or would it just be string data in the unit test
>files?)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ampache/ampache/pull/1412#issuecomment-255779782

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by SenorSmartyPants** [comment]
Is there anything I should do with this to get in merged?

**Comment by Afterster** [comment]
Give me a second life :smile:? Kidding, sorry for being so late, I will have to setup a team to continue Ampache project management in my place as long I am so busy at work/life.

Anyway, thank you! 👍

**Comment by SenorSmartyPants** [comment]
No problem. This is my first push into github contributions so I was just checking if I needed to do something more.

Thanks for the work

**Pull request merged**
