### PR TITLE
Allow overwriting any template file in theme

### PR DESCRIPTION
**Pull request by Niols**
This is the pull request we talked about in issue #875.

I added the `UI::find_template` method, that tries to find the asked file in `$theme_path/templates/`, and, if it's not there, falls back on the file in `templates/`.

To prevent themes from having PHP access to the server, I added a `allow_php_themes` option set to false by default (infact null, because I didn't find out how to define the default value of an option).

Then I modified almost all the `/templates/…` occurrences by `UI::find_template(…)`. I say almost, because I did not modify all scripts related to installation, since I was not sure they had access to `UI`, and almost sure they had not access to `AmpConfig`.

This seems to be working for me, for the moment. I'll continue using it and testing it. I'll also start writing a theme.

I'm just opening this pull request so that we can talk about it and change things if they're not OK for you.

### CODE REVIEW

**Comment by Afterster** [comment]
Ok for the first changes. I only have a short remarks on AmpConfig::get('allow_php_themes') check that should be first on the list in find_template function, for performance reason.

Take your time to finish your changes as best (and please clean your git history for the merge once completed), I will only merge it on develop branch after 3.8.0 release (currently waiting few more days for issues to throw, just in case).
Thanks.

**Comment by Niols** [comment]
OK, I followed what you said: I recrafted my commit history so that it looks much cleaner, and I changed the order of the tests in find_template function. The function is firstly testing if the extension is php, and if it's the case testing if php is allowed.

I can still do some modifications.

**Comment by Afterster** [comment]
Ok thanks for the change.
I just think you did some mess on your history clean because now one of my commit is on your change list :)

**Comment by Niols** [comment]
Yes, I saw that. I don't know how I did that, and I didn't know how to cancel it. At least you're still the commit author ^^

**Comment by SUTJael** [comment]
Thanks for you work @Niols. Any chance to update the PR with latest sources and based on new files versions? Thanks

**Pull request merged**
