### PR TITLE
Updated _clean_vorbiscomments($tags) for changes to Picard

### PR DESCRIPTION
**Pull request by wagnered**
I believe the required changes can be contributed to both changes to Picard'changes in tag mapping and getID3' changes in gathering the tags.

### CODE REVIEW

**Comment by lachlan-00** [comment]
should we keep the old and new cases? or is this how it outputs the txxx now?

**Comment by wagnered** [comment]
TXXX is id3v2.3, this is vorbiscomments which is typically used in ogg(flac and opus) containers.

I'm thinking it  is dependent on the getID3 library.  So I'm not sure if the `_clean_vorbiscomments($tags)` function really did  work.

As for TXXX, the  MUSICBRAINZ_TRACKID is actually the music brains **recording** ID.  Is it used anywhere in Ampache? I question why that is gathered, instead of the Musicbrainz **release** track Id.  I think the release track Id might be more consistently used across the various taggers that incorporate the Musicbrainz identifiers. 

Also, Ampache, tests for the UFID tag to gather the MUSICBRAINZ_TRACKID frame.  If Picard Is the only tagger that includes the UFID frame, that might be problematic.

**Comment by lachlan-00** [comment]
i'll clean some file tags and redo them in picard to test

**Comment by lachlan-00** [comment]
which version of picard does this? i've got 2.5.6 which seems to be the latest and the old strings without space are coming through.

**Comment by lachlan-00** [comment]
for release track id i only see the track id. is it recording id?
image

**Comment by wagnered** [comment]
I have found two needed changes to the header.inc.php that didn't happen when source-changes migrated to the new develop branch.

I am going to close this PR and do the fix from this branch.

**Pull request closed without merging**
