### PR TITLE
filter_has_var is returning false in FCGI enabled PHP

### PR DESCRIPTION
**Pull request by GaneshKandu**
filter_has_var is returning false even if $_SERVER has HTTPS defined in FCGI enabled PHP versions, that causing this issue.

### CODE REVIEW

**Comment by GaneshKandu** [comment]
#3091

**Comment by lachlan-00** [comment]
cool! thanks for digging into this

**Comment by lachlan-00** [comment]
do you also have issues with filter_var or just filter_has_var?

**Review by lachlan-00 — APPROVED** [review]

**Comment by lachlan-00** [comment]
changed some more to match in 9e6448de0

**Comment by GaneshKandu** [comment]
> do you also have issues with filter_var or just filter_has_var?
with filter_has_var only

**Pull request merged**
