### PR TITLE
Modified Tvdb and Tmdb plugins to correctly parse filenames.

### PR DESCRIPTION
**Pull request by wagnered**
Also increased version number of both Tmdb and Tvdb plugins.

### CODE REVIEW

**Comment by wagnered** [comment]
I think that the Travis errors existed before I created a new fork of ampache/ampache. I forgot to run php php-cs-fixer.phar before I committed my changes, but none of my changes showed up in the dry run.

I ran php php-cs-fixer.phar without a dry run.  Should I push the changes to my fork?

**Comment by Afterster** [comment]
Thanks for this new PR @wagnered ;)
Travis error is coming from one of my previous commits yeah, you shouldn't care about it this time.
I have an unique remarks on your change: *Vainfo::parseFileName* is an improved duplicate of video parsing done inside *Vainfo::_parse_filename* and shouldn't be done on the plugins. Why not replacing the parsing inside *_parse_filename* by your one and using this values on plugins with *$media_info* array? Normally if *metadata_order_video* is set in correct order like *getID3,filename,Tmdb*, this should work and avoid code duplication / keep the plugin ordering logic.

**Comment by wagnered** [comment]
OK, will modify _parse_filename with "improved" code.  Although, from the description of the function, it looked like it was parsing the full folder path for tag information, but would probably need a switch in the config file to let the logic know that the full file path was being parsed. So I didn't think that through. ;'>

As for the "correct" order of metadata_order_video, I don't remember reading about the order other than something about (not) putting db first. It is not very intuitive ( at least in my mind ;'>), for as many times as I've stepped through the video code I didn't become aware that there was a correct order. Also, no software that I could find that embeds ID3 tags into mp4 video files. It is my opinion that only tag type of "general" should be needed and, automatically used with Tmdb or Tvdb and possibly parsing tag info from mp4 files.. 

regards,
Ernie

**Comment by Afterster** [comment]
Well yes it is currently parsing the full path but I think the solution is a mix of the two, full path should still be parsed as it could contains additional information for series for instance. But it shouldn't be two functions, all can be merged into one.

Yeah the correct order is not intuitive. I think we should add comments into the configuration file for the recommended first parser to set.

**Comment by wagnered** [comment]
Oh yea, I got to find some complex folder path examples to use, but at first glance, it looks like I might be incorporating a significant part of the logic in _parse_filename.

I'm anxious to see what format @octalman (#944) is using.

**Comment by wagnered** [comment]
update:

In vainfo::_parse_filename TV shows are specifically denied the ability
to get show info from folder path.

I'm going to see if vainfo::_parse_filename can be cleaned up some
because it looks like it might do a better job at eliminating garbage
stuff from the folder path and keeping important metadata. Maybe my
function won't be needed.


On 09/03/2015 10:51 AM, Afterster wrote:
> Well yes it is currently parsing the full path but I think the solution
> is a mix of the two, full path should still be parsed as it could
> contains additional information for series for instance. But it
> shouldn't be two functions, all can be merged into one.
> 
> Yeah the correct order is not intuitive. I think we should add comments
> into the configuration file for the recommended first parser to set.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/pull/943#issuecomment-137527110>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by Afterster** [comment]
Okay, let me know when your changes are completed and I will review them again. Thanks.

**Comment by wagnered** [comment]
@Afterster,
OK here is my update.  PHP regex has fantastic parse engine. I was able to reduce and streamline Vainfo->_parse_filename  with only a few of the tools provided by the Regex engine.  I have yet to understand "subroutins" and recursive actions of the engine.

**Comment by wagnered** [comment]
I see the issues and bug now.  They are a product of copying the music and clip routines to the new _parse_filename function.  Interesting that they did not prevent successful importing of music files into the database.

I will take care of them shortly.

**Comment by wagnered** [comment]
Looks Like my code broke the scrutinizer ; ' >

**Comment by wagnered** [comment]
No new scrutinizer issues.

**Comment by Afterster** [comment]
Ok thanks @wagnered.
I gave a try and from my opinion it's not yet that ^^.
First, it seems to be some problems with separators, I end up with names like `TVSHOW -` and `- TITLE`. Also when common suffix are removed (hdtv, divx, ...), separators are keep which result to titles names like `TITLE..-`. Worst, sometimes the name is not correctly retrieved for releases with dot only for separators (eg. the.gates.s01e02.hdtv.xvid-2hd.mp4). Same goes for movies about separators, *TITLE [1080p].mp4* become *TITLE []*.
I don't have much time to look on the algo here for now as it is a bit complicated and takes some time. Great if you can take care about it and then I will give another test when changed. Otherwise I will gonna try to fix it later too.

**Comment by wagnered** [comment]
I enjoy working with regex as it is like learning a new (programming)
language.

OK, do you have any different examples that do not parse correctly?  The
reason I asked is that I am using the Kodi specs of naming movie and TV
show files/folders. If you think that the routine should parse other
(any?) filename format, I think I need some examples to use. For
example, should the routine parse for braces too? angle brackets?
Shouldn't be hard.

Perhaps this is when I go to the Google forum and inquire for examples.

The removal of periods will be simple.  It's just that I was using the
TV show titled "Awkward." and was trying to allow for periods in the
title.  I guess there will always be some situation that won't
completely parse.

On 09/16/2015 02:59 PM, Afterster wrote:
> Ok thanks @wagnered <https://github.com/wagnered>.
> I gave a try and from my opinion it's not yet that ^^.
> First, it seems to be some problems with separators, I end up with names
> like |TVSHOW -| and |- TITLE|. Also when common suffix are removed
> (hdtv, divx, ...), separators are keep which result to titles names like
> |TITLE..-|. Worst, sometimes the name is not correctly retrieved for
> releases with dot only for separators (eg.
> the.gates.s01e02.hdtv.xvid-2hd.mp4). Same goes for movies about
> separators, /TITLE [1080p].mp4/ become /TITLE []/.
> I don't have much time to look on the algo here for now as it is a bit
> complicated and takes some time. Great if you can take care about it and
> then I will give another test when changed. Otherwise I will gonna try
> to fix it later too.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/pull/943#issuecomment-140907343>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
This latest patch will parse something like:
"To.Kill.a.Mockingbird <1962>.720p.BrRip.x264.YIFY.mp4"
using any combination of brackets, braces, parenthesis, periods or spaces as separators.

My issue is that because there is no reasonable limit to the variation of abbreviations that may be found in a file name, the list should be user manageable in a script or config file or maybe kept in the database.  I just added over six new real-world examples just debugging the code.

**Comment by Afterster** [comment]
Better but still not ok. I voluntary have samples tvshows with a variety of file name, type, organization just for testing.
Here is the ones that failing a little:
 * `Dollhouse/Season 01/Dollhouse - 1x08 - Needs.avi`: everything is parsed correctly except the season name with end up with trailing - character: `Dollhouse -`
 * `The Gates/Season 01/the.gates.s01e01.repack.hdtv.xvid-2hd.avi`: title set to     the.gates.s01e01.repack.hdtv.xvid-2hd
 * `The Gates/Season 01/The.Gates.S01E04.HDTV.XviD-P0W4.avi`: title set to P0W4
Maybe we should also standardize TV Show name with a first letter uppercase at each word?

I would also enjoy having a fallback on directory structure in case of missing information like it was in https://github.com/ampache/ampache/pull/943/files#diff-18e0da90cc518fe752b27ca4ba2544b6L1086, don't you agree?

I agree with the abbreviation list, I believe we should put the setting on ampache.cfg.php.

**Comment by wagnered** [comment]
@Afterster,

OK with P0W4 in the $commonabbr array, it doesn't show up anymore in the
title or anywhere else.

Season name?  Do you mean episode name?  If you do mean "Season name"
could you inform me as to what specs are used to define the
filename/folder structures you are using.

I made a change in the order of str_replace() and trim() and it seemed
to take care of the problems you mention below.

You wrote:
>I would also enjoy having a fallback on directory structure in case of
> missing information like it was in
 What missing information are you referring to? The only thing I could
get from the diff file was the usual show name, episode title, Season #
and Episode # I don't see parsing for any specific additional information.

Hopefully it doesn't break the movie side :'>

On 09/17/2015 01:40 PM, Afterster wrote:
> Better but still not ok. I voluntary have samples tvshows with a variety
> of file name, type, organization just for testing.
> Here is the ones that failing a little:
> 
>   * |Dollhouse/Season 01/Dollhouse - 1x08 - Needs.avi|: everything is
>     parsed correctly except the season name with end up with trailing -
>     character: |Dollhouse -|
>   * |The Gates/Season 01/the.gates.s01e01.repack.hdtv.xvid-2hd.avi|:
>     title set to the.gates.s01e01.repack.hdtv.xvid-2hd
>   * |The Gates/Season 01/The.Gates.S01E04.HDTV.XviD-P0W4.avi|: title set
>     to P0W4 Maybe we should also standardize TV Show name with a first
>     letter uppercase at each word?
> 
> I would also enjoy having a fallback on directory structure in case of
> missing information like it was in
> https://github.com/ampache/ampache/pull/943/files#diff-18e0da90cc518fe752b27ca4ba2544b6L1086,
> don't you agree?
> 
> I agree with the abbreviation list, I believe we should put the setting
> on ampache.cfg.php.
> 
> â
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/pull/943#issuecomment-141222145>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by Afterster** [comment]
I did a try again and the result wasn't perfect (empty title, bad parsed one). It is not tolerant enough right now. I sent you a listing of my tvshow sample folder so you can try by yourself too. Thanks.

**Comment by wagnered** [comment]
@Afterster,

The only badly parsed file that I noticed was: Dollhouse - 2x01 -
Vows.mkv that is the "Original_name was "Vo". That is because of "ws" in
the commonabbreviations list.  I'm sure there will be many more as there
will be an infinite variety of episode titles.

I tested several episodes from each tv show and they seemed to parse ok.

I don't know what to do with w4f-tw301.avi.  is w4f an unwanted
abbreviation? If it is, it should be at the end of the file name.
also, is "tw" or "w4f-tw" an unwanted abbreviation or is it the actual
show name?

Do you expect the parser to successfully parse any file/path structure?

The same goes for: bawls-thegatess1e9.avi. That appears to follow no
specifications that I am familiar with. I don't know of any way to parse
that one.  At least not easily and it would only be partially successful.

Also, the regex expression in the removeCommonAbbreviations() function
is not recursive so similar abbreviations must be placed carefully.

For example "vostfr" should be placed before "vost", otherwise "fr" will
remain.  I will look into recursive Regex later.

I wrote the procedure to conform to the structures I listed in the
functions comments.  This is a widely accepted set of file/path
structures from multimedia players to binary music files downloaded from
usenet groups.  All but two of your files as listed above conform. All
files in your list that conform parse correctly according to the Kodi specs.

So unless you want the function to parse anything, I am satisfied that
the function is currently adequate for Kodi style file name/path formats.

If I seem in a bad mood, it is because my work notebook died last night
and is going to cost me over $390 to repair.  I moved the hard drive
into my multimedia server which is slow and has only a 15 inch screen.
And of course my multimedia server is temporarily out of commission. :'>

On 09/22/2015 10:36 AM, Afterster wrote:
> I did a try again and the result wasn't perfect (empty title, bad parsed
> one). It is not tolerant enough right now. I sent you a listing of my
> tvshow sample folder so you can try by yourself too. Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/pull/943#issuecomment-142358042>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
As I was drifting off to sleep, or trying to, I thought of a fix for the
problems with the parsing of the episode title. It worked on the first
one I tried: I will try it on every episode that has an episode title.

On 09/22/2015 10:36 AM, Afterster wrote:
> I did a try again and the result wasn't perfect (empty title, bad parsed
> one). It is not tolerant enough right now. I sent you a listing of my
> tvshow sample folder so you can try by yourself too. Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/pull/943#issuecomment-142358042>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by Afterster** [comment]
No problem, I don't get easily offended if there is explanation ;)
I believe you should remove abbreviations only if it is a distinguish word (separates by space, union, ...).
In my sample listing, w4f-tw301.avi and bawls-thegatess1e9.avi and supposed to fail the parsing yes, don't worry about that (I'm getting information from ID3 for those).
But Dollhouse 2x01 is not the only one failing on my side. Most Torchwood episodes are going under an "Unknown" TV Show name with bad season/episode number.
I'm doing my test without Tvdb/Tmdb plugin enabled.

**Comment by wagnered** [comment]
@Afterster,

I removed the date pattern from the "$match =" statements.  The year is
captured in the next statement, so it wasn't necessary to have it there
anyway. The date in the pattern was evidently confusing the logic with
your file name structures.

OK, I think I understand and adding \b  to the pattern before and after
the keyword seems to have fixed the problem. I have successfully
regression tested all of your example file names and renamed an actual
file to "Dollhouse - 2x01 - Vows.mkv" to actually test it with Ampache.

Also, as I mentioned before, careful placement of the abbreviation in
the list is required to successfully remove somewhat similar
abbreviations. (Those having the same root.)

On 09/23/2015 12:32 PM, Afterster wrote:
> No problem, I don't get easily offended if there is explanation ;)
> I believe you should remove abbreviations only if it is a distinguish
> word (separates by space, union, ...).
> In my sample listing, w4f-tw301.avi and bawls-thegatess1e9.avi and
> supposed to fail the parsing yes, don't worry about that (I'm getting
> information from ID3 for those).
> But Dollhouse 2x01 is not the only one failing on my side. Most
> Torchwood episodes are going under an "Unknown" TV Show name with bad
> season/episode number.
> I'm doing my test without Tvdb/Tmdb plugin enabled.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/pull/943#issuecomment-142705743>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by Afterster** [comment]
Ok better for Vows episode yes thanks.
But for me we should still handle this:
 * The Gates/Season 01/bawls-thegatess1e9.avi, because TV Show / Season cannot be determined from file name, we should fallback on parent and parent of parent directory, just like it is actually without your merge
 * All Torchwood episodes end-up to Unknown tvshow, season and episode number. The file likes the one bellow should be handled correctly
  * Torchwood/Season 01/Torchwood.1x01.avi
  * Torchwood/Season 03/w4f-tw302.avi

**Comment by wagnered** [comment]
OK, I apologize: I obviously did not test the "Torchwood.1x01.avi"
pattern. I guess because they appeared similar to a well-established
tvshow naming pattern. Anyway, that fix was easy.

The problem I see with "w4f-tw302.avi" is that it somewhat conforms to
the widely accepted pattern "show.name.302.episode.title.ext" and I know
of no way to parse the pattern other than using the season and episode
numbers as the search items, so "w4f-tw302.avi" will never reach the
fallback statements. I am a bit slow at times, so please clue me in if
there is a way that I just can't think of.

Meanwhile, I will set up a unit test with the pre-merged function(s) and
see how well they actually do with well-established patterns such as
Kodi and others expect to find.


On 09/23/2015 10:20 PM, Afterster wrote:
> Ok better for Vows episode yes thanks.
> But for me we should still handle this:
> 
>   * The Gates/Season 01/bawls-thegatess1e9.avi, because TV Show / Season
>     cannot be determined from file name, we should fallback on parent
>     and parent of parent directory, just like it is actually without
>     your merge
>   * All Torchwood episodes end-up to Unknown tvshow, season and episode
>     number. The file likes the one bellow should be handled correctly
>       o Torchwood/Season 01/Torchwood.1x01.avi
>       o Torchwood/Season 03/w4f-tw302.avi
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/pull/943#issuecomment-142814351>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
Never mind!  I think that with very carefully designed patterns, I should be able to get "w4f-tw302.avi" to fall through to the fallback statements.  Right now, it is not getting past  the "1x10" type expressions.

**Comment by wagnered** [comment]
I'm progressing, but ran into a slight complication because of the
statement:
  $parsed['title'] = urldecode($this->_pathinfo['filename']);
in _parse_general($tags).

Shouldn't the file name be sent to the _parse_filename function to clean
up the title? Otherwise if $original_name is empty, the display logic
will use the result of $parsed['title'] which is stored in the video
table.  If the title is cleaned in _parse_general, the handling of an
empty original_name would be a little cleaner: The $original_name
variable could remain empty.

On 09/23/2015 10:20 PM, Afterster wrote:
> Ok better for Vows episode yes thanks.
> But for me we should still handle this:
> 
>   * The Gates/Season 01/bawls-thegatess1e9.avi, because TV Show / Season
>     cannot be determined from file name, we should fallback on parent
>     and parent of parent directory, just like it is actually without
>     your merge
>   * All Torchwood episodes end-up to Unknown tvshow, season and episode
>     number. The file likes the one bellow should be handled correctly
>       o Torchwood/Season 01/Torchwood.1x01.avi
>       o Torchwood/Season 03/w4f-tw302.avi
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/pull/943#issuecomment-142814351>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by Afterster** [comment]
Well, just by reading the code, normally _parse_filename *and* _parse_general are called in this order so it isn't required (or I am wrong?).

**Comment by wagnered** [comment]
No, you're not wrong, I just needed a reminder, I guess.  Got it now.

On 09/26/2015 01:26 AM, Afterster wrote:
> Well, just by reading the code, normally _parse_filename /and/
> _parse_general are called in this order so it isn't required (or I am
> wrong?).
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/pull/943#issuecomment-143409707>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
OK, now handles "w4f-tw302.avi" and typical file patterns with nothing (no episode title) to the right of the season/episode numbers for all patterns.  Also fixed statements in movie and video classes.

**Comment by wagnered** [comment]
OK, now handles "w4f-tw302.avi" and typical file patterns with nothing (no episode title) to the right of the season/episode numbers for all patterns.  Also fixed statements in movie and video classes.

**Comment by wagnered** [comment]
Changed `update_video_from_tags` to static.
I think at this  time, the PR is ready for merging.

**Comment by Afterster** [comment]
Ok after a review and few short fixes including a better directory parsing in my way I merged it.
Thank you for your time here @wagnered, I hope we will get positive feedbacks from this merge ;)

**Pull request merged**
