### PR TITLE
get_artists speed-up sql statement for album_count

### PR DESCRIPTION
**Pull request by t-master-t**
this speeds-up the whole statement atleast for my mysql database including 4400 songs

### CODE REVIEW

**Comment by lachlan-00** [comment]
Sorry I missed this. Will close it out tomorrow

**Comment by lachlan-00** [comment]
These queries actually take almost twice as long for me.

new queries

* without where catalog (13574 total, Query took 7.0098 seconds.)
* with catalog (13568 total, Query took 8.5706 seconds.)

current queries

* without where catalog (13574 total, Query took 4.5824 seconds.)
* with catalog (13568 total, Query took 5.9142 seconds.)

### new queries

Showing rows 0 - 24 (13574 total, Query took 7.0098 seconds.)
```
SELECT `artist`.`id`,
       `artist`.`name`,
       `artist`.`prefix`,
       `artist`.`summary`,
       COUNT(DISTINCT `song`.`album`) AS `albums`
FROM `song`
LEFT JOIN `artist` ON `artist`.`id` = `song`.`artist`
GROUP BY `artist`.`id`, `artist`.`name`, `artist`.`prefix`, `artist`.`summary`, `song`.`artist`
ORDER BY `artist`.`name` 
```

Showing rows 0 - 24 (13568 total, Query took 8.5706 seconds.)
```
SELECT `artist`.`id`,
       `artist`.`name`,
       `artist`.`prefix`,
       `artist`.`summary`,
       COUNT(DISTINCT `song`.`album`) AS `albums`
FROM `song`
LEFT JOIN `artist` ON `artist`.`id` = `song`.`artist`
WHERE `song`.`catalog` IN (2)
GROUP BY `artist`.`id`, `artist`.`name`, `artist`.`prefix`, `artist`.`summary`, `song`.`artist`
ORDER BY `artist`.`name` 
```

### current queries

Showing rows 0 - 24 (13574 total, Query took 4.5824 seconds.)
```
SELECT `artist`.`id`,
       `artist`.`name`,
       `artist`.`prefix`,
       `artist`.`summary`,
       (SELECT COUNT(DISTINCT album) from `song` as `inner_song` WHERE `inner_song`.`artist` = `song`.`artist`) AS `albums`
FROM `song`
LEFT JOIN `artist` ON `artist`.`id` = `song`.`artist`
GROUP BY `artist`.`id`, `artist`.`name`, `artist`.`prefix`, `artist`.`summary`, `song`.`artist`
ORDER BY `artist`.`name` 
```

Showing rows 0 - 24 (13568 total, Query took 5.9142 seconds.)
```
SELECT `artist`.`id`,
       `artist`.`name`,
       `artist`.`prefix`,
       `artist`.`summary`,
       (SELECT COUNT(DISTINCT album) from `song` as `inner_song` WHERE `inner_song`.`artist` = `song`.`artist`) AS `albums`
FROM `song`
LEFT JOIN `artist` ON `artist`.`id` = `song`.`artist`
WHERE `song`.`catalog` IN (2)
GROUP BY `artist`.`id`, `artist`.`name`, `artist`.`prefix`, `artist`.`summary`, `song`.`artist`
ORDER BY `artist`.`name` 
```

**Comment by t-master-t** [comment]
@lachlan-00  Thanks for verifying. My results are completly different thus it is worth to be more clear about the systems.

Using PHPMyAdmin executing the queries results for me in
New query: 1073 results, query took 0.1833 seconds
Old query: 1073 results, query took 83.2725 seconds (!!!)

And as you can see my database seems to be a lot smaller than yours.
The new query part to count the distinct albums is just inspired by the one in artist.class.php

More details:

13155 records in songs
1088 records in artist
1072 records in album

DB-Server: MySQL 5.7.33-0ubuntu0.18.04.1 - (Ubuntu) 
    Apache
    libmysql - 5.7.33
    mysqli curl mbstring 
    PHP 7.1.33

Hope that helps. In any case - for me and my current music library it works.

**Comment by stebe** [comment]
I thought I'd try too and I don't see any significant difference. Could it be the difference in the amount of memory and drive technology?

new queries

    without where catalog (8620 total, Query took 0.7800 seconds.)
    with catalog (4809 total, Query took 0.4028 seconds.) 

current queries

    without where catalog (8620 total, Query took 0.5349 seconds.) 
    with catalog (4809 total, Query took 0.3942 seconds.)

**Comment by lachlan-00** [comment]
i wonder if it's mysql specific? i'll do a bit more digging

**Comment by lachlan-00** [comment]
It might also be good to take these counts out into a table/column instead too

**Comment by SePHTaN** [comment]
> Using PHPMyAdmin executing the queries results for me in
> New query: 1073 results, query took 0.1833 seconds
> Old query: 1073 results, query took 83.2725 seconds (!!!)

This difference looks far too big for me. Might be some kind of caching by PHPMyAdmin or the database itself if one runs two query with many identical selects and joins.
So to make measurements comparable one should have identical starting conditions for variations of querys.
Thus it might be a good idea to empty the query cache from query results.
From MySQL Doku:
The RESET QUERY CACHE statement removes all query results from the query cache. The FLUSH TABLES statement also does this.

**Comment by lachlan-00** [comment]
i think this is MySQL specific. i'm just installing in AMPPS to test and it's running faster with your new queries

**Comment by lachlan-00** [comment]
i think the current query isn't doing things in a good way either so lets see if we can find something that works better on both

**Comment by usox** [comment]
Instead of just measuring the select-query speed, maybe consider using the mysql-profiling tools to get a better insight.
https://mysqlserverteam.com/mysql-explain-analyze/

**Comment by lachlan-00** [comment]
> 
> 
> Instead of just measuring the select-query speed, maybe consider using the mysql-profiling tools to get a better insight.
> https://mysqlserverteam.com/mysql-explain-analyze/

all of these counts which only change when the files change i'm going to more out of live counting. is seems redundant for this when counts will be largely static until the next album is added

**Comment by lachlan-00** [comment]
i'll finish my update on this tomorrow, doing a db update and stopping the constant checking.

**Comment by lachlan-00** [comment]
not needed now that the column is added to the table

**Pull request closed without merging**
