### PR TITLE
API improvements

### PR DESCRIPTION
**Pull request by Phyks**
* Remove `DEPRECATED` in API methods comments

WIP, don't merge right now please

### CODE REVIEW

**Comment by Phyks** [comment]
**TODO**: Upon merge,
- [ ] Update doc about `limit` in the wiki

**Comment by Phyks** [comment]
To discuss:
* Session expiration. I would add a `<session_expire>` node in every response personnally.
* Albums containing multiple disks. How to handle them?

**Comment by Phyks** [comment]
Actually I think this one is OK for merge. And I will push a new one with extra stuff for the api. This way, develop branch and my attempt to rework the UI won't be too much out of sync. :)

**Comment by Afterster** [comment]
Not useful for everybody but I believe it is required for some use case. Thanks.

**Comment by Phyks** [comment]
Actually, as I am working on [ampache_react](http://github.com/phyks/ampache_react), using the Ampache XML API, I find some issues in the API, which I list [here](https://github.com/ampache/ampache/issues/1292).

Whenever I have some time, I fix them in Ampache and make a PR to hopefully close the issue one day.

If I missed anything and some changes are not necessary as it can be achieved in another way, let me know :)

**Comment by Phyks** [comment]
Should be rebased and ok to merge right now. :)

**Comment by Afterster** [comment]
Good for me, thanks.

**Comment by Phyks** [comment]
Doc on limit updated: https://github.com/ampache/ampache/wiki/XML-API#methods.

**Pull request merged**
