### PR TITLE
Source changes

### PR DESCRIPTION
**Pull request by lachlan-00**

### CODE REVIEW

**Comment by stebe** [comment]
This was quite painless. Just followed your Wiki instructions [https://github.com/ampache/ampache/wiki/Ampache-Next-Changes](url) and the site is still running. I assume once the .htaccess files are moved; the old rest, play and channel folders can be deleted.

**Comment by lachlan-00** [comment]
> This was quite painless. Just followed your Wiki instructions [https://github.com/ampache/ampache/wiki/Ampache-Next-Changes](url) and the site is still running. I assume once the .htaccess files are moved; the old rest, play and channel folders can be deleted.
> 

I didn't think about left overs but yes they can go now that it's all in public

Was it just rest play and channel left over for you? I'll update the doc to note those.

I'm really glad to hear that it was easy to follow and move on which is exactly what I wanted it to be. :)

**Comment by stebe** [comment]
This is the folder listing in /var/www/ampache

```
drwxr-xr-x 15 www-data www-data   4096 Mar  2 03:33 .
drwxrwxr-x 20 root     root       4096 Mar  2 03:52 ..
drwxr-xr-x  2 www-data www-data   4096 Mar  2 03:26 bin
-rw-r--r--  1 www-data www-data   1331 Sep  1 22:02 .codeclimate.yml
-rw-r--r--  1 www-data www-data  13429 Mar  2 03:26 composer.json
-rw-r--r--  1 www-data www-data 306446 Mar  2 03:26 composer.lock
drwxr-xr-x  2 www-data www-data   4096 Mar  2 03:26 config
-rw-r--r--  1 www-data www-data   9283 Mar  2 03:26 CONTRIBUTING.md
drwxr-xr-x  5 www-data www-data   4096 Mar  2 03:26 docs
drwxr-xr-x  8 www-data www-data   4096 Mar  2 04:14 .git
-rw-r--r--  1 www-data www-data   2518 Jul 24  2020 .gitattributes
drwxr-xr-x  4 www-data www-data   4096 Dec 15 21:58 .github
-rw-r--r--  1 www-data www-data    572 Mar  2 03:26 .gitignore
-rw-r--r--  1 www-data www-data   1706 Mar  2 03:26 index.html
drwxr-xr-x  5 www-data www-data   4096 Mar  2 03:26 lib
drwxr-xr-x 32 www-data www-data   4096 Jan  4 07:26 locale
-rw-r--r--  1 www-data www-data    990 Mar  2 03:26 .php_cs
-rw-r--r--  1 www-data www-data   2350 Mar  2 03:26 .phpcs.xml
-rw-r--r--  1 www-data www-data    789 Mar  2 03:26 phpunit.xml.dist
drwxr-xr-x 14 www-data www-data   4096 Mar  2 03:26 public
-rw-r--r--  1 www-data www-data   6366 Mar  2 03:26 README.md
drwxr-xr-x  6 www-data www-data   4096 Mar  2 03:26 resources
-rw-r--r--  1 www-data www-data   2129 Mar  2 03:26 .scrutinizer.yml
-rw-r--r--  1 www-data www-data    670 Aug 23  2020 SECURITY.md
drwxr-xr-x  8 www-data www-data   4096 Mar  2 03:26 src
drwxr-xr-x  5 www-data www-data   4096 Mar  2 03:26 tests
-rw-r--r--  1 www-data www-data    477 Mar  2 03:26 .travis.yml
drwxr-xr-x  2 www-data www-data   4096 Jul 24  2020 .tx
drwxr-xr-x 46 www-data www-data   4096 Mar  2 04:14 vendor
```

**Comment by usox** [comment]
Maybe, we should include a simple cleanup-script for the 4->5 migration...

**Pull request merged**
