### PR TITLE
Negative tracknr

### PR DESCRIPTION
**Pull request by jleipsig**
sanitize track numbers, to prevent import fails
  negative track number are stored with an empty value
  big track numbers (>65535) are truncated to last 4 digits

### CODE REVIEW

**Comment by jleipsig** [comment]
proposed fix for #2429

**Comment by wagnered** [comment]
If there is no other way, I'll reluctantly agree with your solution. But I think there is.

I realize that error catching and debugging wasn't given much thought during Ampache's early days, but please give this problem some more thought. All the information does exist in the $params variable and in the $sql variable. A function could be created to examine the contents of those variables and issue a debug event with the suspect info. 

There is also PDOStatement::debugDumpParams` which might work out with server-side include(?), but doesn't seem promising.

We appreciate your enthusiasm in improving Ampache.

**Comment by lachlan-00** [comment]
Oh you better believe I'm putting in debugDumpParams in the code! I think it would be good to put that in for errors instead of the current debug at the very least

What are some examples of track numbers being so large as well? I can't say I've seen anything over 999 in my life.

**Comment by jleipsig** [comment]
I had several tracks with negative track numbers that didn't get imported. For a long time I didn't notice that they didn't get imported. After I found out it would be  easy to fix the tags and don't bother. But I wanted to help others with the same messy tags.
I never encountered the big numbers, but that was already in the code, so I kept it ( in an 'improved' way)
No problem if this is not the right fix. Now I'm going to finish my glass of wine. It's almost 3 am ...

**Comment by lachlan-00** [comment]
Haha, don't worry about that. Wine on the weekend is prime coding time.
I tend to work during the week in between my regular work so I'll start this tomorrow.

Keep going though. The amount of improvement we've had in the past week is amazing!

**Comment by kuzi-moto** [comment]
Would it be safe to assume that track numbers larger than say, 1000 and lower than 0 are likely errors? Maybe there could be some logic to assume the correct track number? If metadata is incorrect, look at the track title, or just increment +1 from the last track, then any other tracks that were incorrect would at least have a sane track number (even if it were incorrect).

Alternatively maybe Ampache could alert the user to the error in the interface to allow manual intervention.

**Comment by jleipsig** [comment]
Guessing the correct value could help, certainly in albums with successive track numbers. But I would prefer to leave the value as is or give the user enough information to correct it. F.e. I have one file '903_artist_title_year.mp3' with track number -121. It's in a folder with some singular tracks. Personally I would prefer to give it an empty value or -121, not a guessed value of 121 or 903.

I agree it would be very helpful to alert the user on errors (preferably without halting the import/update process), and supply enough information to allow some corrections.

The ID3v2 spec doesn't say the TRCK frame should contain a _positive_ number, although the description 'the order number [...] on its original recording' doesn't leave much room for negative values.
But I prefer the import/update to be forgiving towards funny data. Another solution for this negative track number issue, could be to alter the table field song.track into a signed number, so you don't need checks/guesses in the code. Maybe MEDIUMINT, to prevent the loss of existing values > 32767 and be a bit more lenient for some 'freak' track numbers possibly existing in this universe. It's just one byte / track extra storage.

(BTW thanks for the quick and constructive comments, that's what keeps it going. Wine on the weekend less so...)

**Comment by lachlan-00** [comment]
moving to signed MEDIUMINT over just flipping the table column to unsigned would cover any existing 65k track numbers (i know there wouldn't be many but we should be compatible to all existing databases) and allow negative ints,

Moving to that would cover pregap tracks like these.
image

but my only question then is the storage would increase from 2byte to 3bytes per track number?
https://dev.mysql.com/doc/refman/5.7/en/integer-types.html

That's a negligible number in the scheme of things but something to consider. After googling around i think supporting negative numbers is valid for albums.

**Comment by wagnered** [comment]
I don't think it matters much how large an integer to accept, as long as the upper limit is documented or just truncate the positive number. 

As for a negative number, what about getting the absolute value, then determine  if it is within the documented limit, or just  truncate it maybe with a warning.

**Comment by lachlan-00** [comment]
I would like to go the other way and allow negative numbers as they do exist in commercial albums
https://en.wikipedia.org/wiki/List_of_albums_with_tracks_hidden_in_the_pregap

**Comment by jleipsig** [comment]
Should I make a new pull request with the database change and close this one?

**Comment by lachlan-00** [comment]
I always vote with what albums do as what ampache should do.
If there are negative ints as a possible value i think we should support them.

My vote for what to do is a database update to signed int and truncate existing values that are higher first. @wagnerd what's your opinion on this? 

Apparently 300 is the (current) highest number of tracks on an album so i think we keep it the same size and view any data higher than the 32k limit as invalid.
image

We should probably keep check_tracknr as some kind of limit function. testing upper/lower values (default to 0 for lower and require an upper limit) The added data checks have made the import process a lot stronger. something like:
```
check_limit($upper, $lower = 0)
```

We should close this one off and move back to #2429; as it's been a good discussion but the pull doesn't actually solve the original issue. @jleipsig you've really brought on some good discourse and made some really valuable changes here. :)

**Comment by wagnered** [comment]
it sure would be nice to know the purpose of a negative track or album number. Couldn't find any reference to the subject in a web search.  The only reason I can think of is that people make mistakes so let the user eventually find it himself/herself or because "Everyone else is doing it". 😃

Actually, I like the PR in which @jliepsig uses the absolute value which seems to adhere the best to id3.org's i  But it doesn't fix the premise that people make mistakes. I just don't think an architectural change should be made to Ampache unless absolutely necessary. 

I thought this PR would take care of #2429. What am I missing?

**Comment by lachlan-00** [comment]
negative track numbers are used for pre-gap / unlisted tracks. which is commonly use as -1 instead of 0

**Comment by wagnered** [comment]
Ok, I always thought that track 0 was meant to be an introduction or verbal explanation of the album content, not an actual song.  I'm guessing that a negative numbered track would never be found on an original cd or album purchased and downloaded online.

Thank you for the information.  I don't know what it means, but if that kind of data is significant, then definitely convert it to signed integer.

**Pull request closed without merging**
