### PR TITLE
Increase copyright column size to fix issue #1861

### PR DESCRIPTION
**Pull request by zerojay**

### CODE REVIEW

**Comment by lachlan-00** [comment]
that will only update new installs. This should go into a database update instead.

Check out lib/class/update.class.php and make your updates there.

First you need to give it a version number and a string explaining the db update
```
        $update_string = "- Fix copyright max size in the podcast table.<br />";
        $version[]     = array('version' => '380013', 'description' => $update_string);
```     

Then at the bottom you do the sql part
```
    public static function update_380013()
    {
        $retval = true;

        $sql = "ALTER TABLE `podcast` MODIFY `copyright` VARCHAR(255)";
        $retval &= Dba::write($sql);
        return $retval;
    }
```

**Comment by Psy-Virus** [comment]
Hey @zerojay,
your PR looks reasonable and safe to merge. If you would change it from an "only on new installation" fix to a "Fix via database update" as @lachlan-00 described, I'd merge it.
Since the Laravel Branch is currently not developed, I guess there's no problem if I use my new permissions to merge also bug fixes and small enhancements, as long as they follow the standards @Afterster and @wagnered introduced.

**Comment by zerojay** [comment]
Hi, sorry for the lack of response on this. I've been extremely busy. I've made the updates to the pull request as... well, requested.

**Comment by lachlan-00** [comment]
@psy-virus I think you're the only person with push who has been active this year.

The update from @zerojay looks good to me. Big thumbs up for contributing.

**Comment by Psy-Virus** [comment]
Looks good. Just one last thing: Get rid of the first commit. :)
As the Database gets updated while Ampache is installed the first time, the first commit (where you have changed the database directly) is useless.
We only need the latest one.
You have some options now. You can reset your local branch to the last commit before your additions by doing: `git reset <commit ID> --hard`, readd your changed `update.class.php` and do a force push to your repository like: `git push origin develop --force`.

Or you do what ever is written [here](https://sethrobertson.github.io/GitFixUm/fixup.html), that helps you solving this.^^

The 3rd option would be that I commit the changes from your repo. But in the history would be written that I committed it with your authorization.
I'd prefer one of the first options, as it keeps the history clear.

:)

**Comment by lachlan-00** [comment]
Hey @zerojay 
Please make a new pull on the core branch
https://github.com/ampache/ampache/tree/core

because this is a DB update i'll do it separately with the other coding work and then you'll get the cred when merged back into dev/master

Thank you for patience with this one. Things are moving!

**Comment by lachlan-00** [comment]
@zerojay you can now merge into the core branch. You'll probably have to close this one as i don't think it will let you change branches. But i'd really like to have your contribution recorded instead of me just putting it in.

https://github.com/ampache/ampache/tree/core

make your update 400001 and i'll merge asap.

**Comment by lachlan-00** [comment]
Merged into my core branch and this will merge into the official branch soon so this pull isn't needed now.

Thanks for your efforts and you're now an Ampache Contributor!

**Pull request closed without merging**
