### PR TITLE
Disk handling updates (remove disk 0)

### PR DESCRIPTION
**Pull request by lachlan-00**
* Add new id3 tags to the database (album table).
  * original_year (release year)
  * barcode
  * catalog_number (moved out of song_data into album)
* default to disk 1 instead of disk 0
* update bin/sort_files.inc so that it actually works
* Add new functions for stat updates 
  * UserActivity::migrate
  * Userflag::migrate
  * Rating::migrate
* Faster tag updates/catalog verify! (Updating an album would update each file multiple times)

### CODE REVIEW

**Comment by lachlan-00** [comment]
@stebe Removed a lot of premature tag noise. and only log the add when it's actually added.
image

**Comment by lachlan-00** [comment]
TODO;

Says no update when it has updated?

**Comment by stebe** [comment]
Thanks @lachlan-00 I'm testing add right now. I'm getting this runtime error.

```
2019-08-14 07:17:05 [stebe] (art.class) -> Searching using:["db","tags","folder","musicbrainz","lastfm","Amazon","google"] 
2019-08-14 07:17:05 [stebe] (art.class) -> Method used: gather_db 
2019-08-14 07:17:05 [stebe] (art.class) -> Method used: gather_tags 
2019-08-14 07:17:05 [stebe] (art.class) -> Method used: gather_folder 
2019-08-14 07:17:05 [stebe] (art.class) -> gather_folder: Results: [] 
2019-08-14 07:17:05 [stebe] (art.class) -> Method used: gather_musicbrainz 
2019-08-14 07:17:05 [stebe] (art.class) -> Method used: gather_lastfm 
2019-08-14 07:17:05 [stebe] (amazonsearchengine.class) -> Retrieving from http://webservices.amazon.com/onca/xml 
2019-08-14 07:17:05 [stebe] (amazonsearchengine.class) -> Amazon request: http://webservices.amazon.com/onca/xml?AWSAccessKeyId=AAAAAAAAAAAAAAAAAAA&Artist=&AssociateTag=aaaaabbbbcccc&Keywords=%20Void_Chords&Operation=ItemSearchSearchIndex=Music&Service=AWSECommerceServiceTimestamp=2019-08-14T11%3A17%3A05Z&Title=&Version=2009-03-31&Signature=XrEO1A0gMO%2BMxwkxG9IgA1NE7l6mP0Eojbifkea7oeA%3D 
2019-08-14 07:17:06 [stebe] (amazon.plugin) -> Searched results page 1/1 
2019-08-14 07:17:06 [stebe] (amazon.plugin) -> Searched using  Void_Chords, results: 0 
2019-08-14 07:17:06 [stebe] (art.class) -> Method used: gather_google 
2019-08-14 07:17:06 [stebe] (art.class) -> Search url: http://www.google.com/search?source=hp&tbm=isch&q=%20Void_Chords&oq=&um=1&ie=UTF-8&sa=N&tab=wi&start=0&tbo=1&imgsz=m 
2019-08-14 07:17:07 [stebe] (art.class) -> Found image at: https://lookaside.fbsbx.com/lookaside/crawler/media/?media_id\u003d1517989141556027 
2019-08-14 07:17:07 [stebe] (art.class) -> Found image at: https://www.lantis.jp/img/tmp_84486d88ca2f24755a4150c78836895e-sp.jpg 
2019-08-14 07:17:07 [stebe] (art.class) -> Found image at: https://img7-us.anidb.net/pics/anime/236050.jpg 
2019-08-14 07:17:07 [stebe] (art.class) -> Found image at: https://cdnx.natalie.mu/media/pp/static/music/voidchords/pc_header.jpg 2019-08-14 07:17:07 [stebe] (art.class) -> Found image at:https://www.lyrical-nonsense.com/wp-content/uploads/Void-Chords-feat.MARU-The-Other-Sideof-the-Wall.jpg 
2019-08-14 07:17:07 [ampache] (log.lib) -> [Runtime Error] imagecreatefromstring(): Data is not in a recognized format in file /var/www/ampache/lib/class/art.class.php(213) 
2019-08-14 07:17:07 [stebe] (art.class) -> Image failed PHP-GD test 
2019-08-14 07:17:07 [ampache] (log.lib) -> [Runtime Error] imagedestroy() expects parameter 1 to be resource, bool given in file /var/www/ampache/lib/class/art.class.php(218) 
2019-08-14 07:17:07 [stebe] (art.class) -> Not inserting image for artist 39736, invalid data passed 
2019-08-14 07:17:07 [ampache] (log.lib) -> [Runtime Error] imagecreatefromstring(): Data is not in a recognized format in file /var/www/ampache/lib/class/art.class.php(213) 
2019-08-14 07:17:07 [stebe] (art.class) -> Image failed PHP-GD test 
2019-08-14 07:17:07 [ampache] (log.lib) -> [Runtime Error] imagedestroy() expects parameter 1 to be resource, bool given in file /var/www/ampache/lib/class/art.class.php(218) 
2019-08-14 07:17:07 [stebe] (art.class) -> Not trying to generate thumbnail, invalid data passed 
2019-08-14 07:17:10 [stebe] (art.class) -> Searching using:["db","tags","folder","musicbrainz","lastfm","Amazon","google"]


```

**Comment by lachlan-00** [comment]
Thanks. Will look asap

**Comment by lachlan-00** [comment]
I didn't change collection/gather code just added checks to reduce the frequency depending on order so hopefully a simple fix.

**Pull request merged**
