### PR TITLE
Propose the YunoHost badge for the installation

### PR DESCRIPTION
**Pull request by anmol26s**
Hi
The YunoHost have working Ampache package with install,remove,update,backup and restore script.  YunoHost makes self -hosting easy for end users. Please add the this badge so that people can find this solution.

### CODE REVIEW

**Comment by lachlan-00** [comment]
@Psy-Virus this should probably be merged to help spread the ampache love

**Comment by Psy-Virus** [comment]
Well, I'd like it more if the badge were on the "install" Wiki page as it is an option and not THE supported way to install and run Ampache.

But it could be at top like:

# Install title
Bla bla
## Install Ampache automated and get updates [...]
further bla bla

## You have your own Server? Do it yourself [...]
Much more bla bla

**Comment by lachlan-00** [comment]
@anmol26s would you like to make a page in the wiki and submit it for approval?

**Comment by anmol26s** [comment]
Hi @lachlan-00 @Psy-Virus 

You mean install page on this wiki page, pointing to  Yunohost install guide?

**Comment by Psy-Virus** [comment]
This one: https://github.com/ampache/ampache/wiki/Installation

**Comment by lachlan-00** [comment]
hey @anmol26s have you sent an edit to the wiki?

I'll be working on the wiki soon so if you haven't send it through so you can be credited.

**Comment by lachlan-00** [comment]
closing this, @anmol26s as i would like this in the wiki

Make an update on the installation page (can be done in a browser) and i will approve.

**Pull request closed without merging**
