### PR TITLE
Feature/improve genre splitting

### PR DESCRIPTION
**Pull request by Razrael**
As discussed in a earlier pullrequest I changed the genre splitting to a regex-based function.
I included it at all places where the cleanup happens, not only id3v2, so I renamed also the config tag.

@lotan I think it is the same way you mentioned, the catalog patterns are also regex, but they have not a complicated pattern so they are easier to understand.

Side note: I always have problems to determine if my code has a valid syntax because I usually use another syntax at work. With php-cs-fixer I get errors on a lot of files, so I just fix the whole file...But this leads to ugly commits. Is it possible to do a code cleanup to psr2 for most of the project?

### CODE REVIEW

**Comment by SUTJael** [comment]
Thanks, good work! Before merging, could you take a look to issue #654? We should fix that issue at the same time.
About the code cleanup, we'll do that ;)

**Comment by Razrael** [comment]
Yes I can. But it would be great if we could get a sample file for this one.
I cannot imagine how this could happen, and it never happend to me, so I need some stuff to work with.

**Comment by Razrael** [comment]
The bug has solved itselve, so we can probably continue with this one.
I already raised the config version number. Anything else to do?

**Comment by Afterster** [comment]
Looks fine to me, good work as usual. Thanks again ;)

**Pull request merged**
