### PR TITLE
Replace jQuery jstree with wunderbaum; introduce Material Symbols

### PR DESCRIPTION
**Pull request by mitchray**
Note: The upload page is dead following the recent enum updates 😭 will undraft when resolved

- Replace the jQuery based ```jstree``` with framework agnostic [wunderbaum ](https://mar10.github.io/wunderbaum/#/)
  - Reads the first level of upload folder, then subsequent folders are lazy-loaded
  - Moved file operations out of contextMenu
- Adds Google Material SVGs as a new icon library
  - Intending to replace all the current 16x16 PNG icons going forward
  - Have used it throughout Ample and have been impressed with the variety and media-related icons
- Minor UI tweaks
  - Add info icon to the "Leave artist and album blank..." message
  - Add icon to "View license" to indicate this will open an external link
  - Moved file requirements beneath the upload portal

This plus the new drop zone should improve the upload experience 🤞

Screen Shot 2024-03-11 at 17 05 02

### CODE REVIEW

**Comment by mitchray** [comment]
Tagging in @usox to take a look at the enums 🙏

```
2024-03-11T06:19:00+00:00 [admin] (C:\git-projects\ampache-preview\src\Module\Authorization\GuiGatekeeper.php:45) -> Ampache\Module\Authorization\GuiGatekeeper::mayAccess(): Argument #2 ($level) must be of type Ampache\Module\Authorization\AccessLevelEnum, string given, called in C:\git-projects\ampache-preview\src\Module\Application\Upload\DefaultAction.php on line 66
```

**Comment by usox** [comment]
> Tagging in @usox to take a look at the enums 🙏
> 
> ```
> 2024-03-11T06:19:00+00:00 [admin] (C:\git-projects\ampache-preview\src\Module\Authorization\GuiGatekeeper.php:45) -> Ampache\Module\Authorization\GuiGatekeeper::mayAccess(): Argument #2 ($level) must be of type Ampache\Module\Authorization\AccessLevelEnum, string given, called in C:\git-projects\ampache-preview\src\Module\Application\Upload\DefaultAction.php on line 66
> ```

Ahh IC, the access-level here is taken from the config.

The following change in the DefaultAction should do the trick.

```php
        $access_level = \Ampache\Module\Authorization\AccessLevelEnum::tryFrom(
          (int) $this->configContainer->get(ConfigurationKeyEnum::UPLOAD_ACCESS_LEVEL)
        ) ?? \Ampache\Module\Authorization\AccessLevelEnum::LEVEL_DEFAULT;

        if (
            $this->configContainer->isFeatureEnabled(ConfigurationKeyEnum::ALLOW_UPLOAD) === false ||
            $access_level === \Ampache\Module\Authorization\AccessLevelEnum::NONE ||
            $gatekeeper->mayAccess(AccessTypeEnum::INTERFACE, $access_level) === false
        ) {
            throw new AccessDeniedException();
        }
```

I'll fix it myself after work + I'm going to search for similar locations which are using the level from the config.

**Comment by usox** [comment]
Here we go #3865

**Comment by lachlan-00** [comment]
@mitchray merged

**Comment by mitchray** [comment]
Thanks guys, all good now

**Comment by lachlan-00** [comment]
not sure what that means with the copy
image

**Comment by mitchray** [comment]
any errors after running ```npm cache verify```?

**Comment by mitchray** [comment]
I see there's actually a preferred fork of npm-run-all so lemme set that up

**Comment by mitchray** [comment]
Let me know how you go with #3870, if it still happens then I'll amend the update command to wipe the node_modules folder which is a common fix

**Comment by lachlan-00** [comment]
using current json and the pull json is the same here. i know debian is apparently bad at npm is v18.19 an issue?

paste from the output log
```
145 timing command:install Completed in 16935ms
146 verbose stack Error: command failed
146 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/lib/index.js:53:27)
146 verbose stack     at ChildProcess.emit (node:events:517:28)
146 verbose stack     at maybeClose (node:internal/child_process:1098:16)
146 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
147 verbose pkgid ampache@1.0.0
148 verbose cwd /var/www/demo/7.ampache.dev
149 verbose Linux 6.1.0-17-amd64
150 verbose node v18.19.0
151 verbose npm  v9.2.0
152 error code 1
153 error path /var/www/demo/7.ampache.dev
154 error command failed
155 error command sh -c npm-run-all copy:*
156 verbose exit 1
157 timing npm Completed in 16999ms
158 verbose code 1
159 error A complete log of this run can be found in:
159 error     /var/www/.npm/_logs/2024-03-12T23_28_45_013Z-debug-0.log
```

**Comment by mitchray** [comment]
Hmm I'm not sure which version I'm on, will have a look tonight

**Comment by lachlan-00** [comment]
It's specific to that module though for me i get it running manually
image

There are a lot of files, could it be that my npm isn't liking how large the amount of files are?

**Comment by lachlan-00** [comment]
I had a look at the icons called in the php and reducing them to individual files works fine
```
copyfiles --up 4 node_modules/@material-symbols/svg-400/rounded/folder.svg node_modules/@material-symbols/svg-400/rounded/edit.svg node_modules/@material-symbols/svg-400/rounded/delete.svg node_modules/@material-symbols/svg-400/rounded/refresh.svg node_modules/@material-symbols/svg-400/rounded/cut.svg node_modules/@material-symbols/svg-400/rounded/folder_copy.svg node_modules/@material-symbols/svg-400/rounded/content_paste.svg node_modules/@material-symbols/svg-400/rounded/info.svg public/lib/components/material-symbols
```

**Comment by lachlan-00** [comment]
quoting the folder paths fixes it for me. 2296b8346

**Pull request merged**
