### PR TITLE
Upgrade scrobbling API (last.fm and libre.fm)

### PR DESCRIPTION
**Pull request by nioc**
Upgrade the scrobbler class, Lastfm and Librefm plugins to use the new API.
Authentication is changed:
-admin needs to create a last.fm API account, set their API key and secret in the ampache.cfg file,
-users need to grant Ampache application to last.fm / Libre.fm services by using preference tab > plugins.

Resolves ampache/ampache#922

Add the "spread the love" function to share your favorites on Last.fm and Libre.fm.

Change-Id: Ia81334f4f4506258a27d40b6c257a1e38bd69097
Signed-off-by: nioc <nioc@users.noreply.github.com>

### CODE REVIEW

**Comment by Afterster** [comment]
I reviewed the code and your PR looks good, thank you for taking care about this part.
I think it could even fix few issues referenced in #349.

Last.FM is currently migrating to their new website, I will test it properly when it become stable again.

**Comment by nioc** [comment]
Good news :bowtie:
I noticed, the last.fm website badly handle the https auth call. Sometimes it redirect to http page, sometimes not. I don't know if it is a website migration issue (and https will work at each call), or if we have to call on http only.
I don't touch the async scrobbler.class.php, so may be the issue you referred shouldn't be fixed. I'm waiting for your tests :smile:

**Comment by Afterster** [comment]
@nioc I was reviewing again your PR before merge and I got something wrong. You're always using the global lastfm api key/secret. Global lastfm api key (in ampache.cfg.php) should be used for catalog related operations only (similar artists, ...). Each Ampache user should be able to scrobble to his own lastfm account and then lastfm/librefm api key/secret should be plugin parameters.
Sorry to report this only now after few weeks, and thank you!

**Comment by nioc** [comment]
Hi!
I have to take a look, but if I remember correctly, we have the application key (with customized icon and specific callback url set in last.fm) which is the same for each users of a same installation, and the user session key (which is specific to each users and obtained by the auth sequence).
Why do you think this is wrong?

**Comment by Afterster** [comment]
Oh you're probably right in fact that could be a misunderstanding on my side. Give me some time to review/test it properly again once back at home.

**Comment by Afterster** [comment]
Ok after testing better this time, works good. I'm gonna merge it, thanks for the good PR!

**Comment by nioc** [comment]
Great :smiley: 
May be, we should update the wiki for the new authentication sequence and the need to set a custom API key?

**Comment by Afterster** [comment]
Yes wiki should be updated indeed.
I just opened the wiki for public contribution btw, no reason to limit it as long we are frequently keeping a eye on changes ;)

**Comment by ciroiriarte** [comment]
It it possible to disable all interaction with lastfm?, I'm having issues with timeouts and errors when no connected to Internet

**Comment by PlusMinus0** [comment]
Just a question, is an api key now mandatory for scrobbling? I skimmed through the code and it seems to have replaced the username as means of authentication. Am I right?

**Comment by nioc** [comment]
Hello !
@ciroiriarte yes you can disable the lastFM function in the plugin tab. If it is not enabled, it should not make any call to lastfm server (neither scrobbling or love songs, however, the related song may be called I don't know about it).
@PlusMinus0 yes API key is mandatory with the new lastFM API, you can have one by submitting [this form] (http://www.last.fm/api/account/create), then you have to set both `lastfm_api_key` and `lastfm_api_secret` variables it in your `config/ampache.cfg.php`

**Comment by PlusMinus0** [comment]
@nioc thank you for your reply. I did that and I still couldn't get it to work. I entered my the keys into the ampache.cfg.php and my credentials into the plugin's page. But when I do, my Ampache just doesn't play songs anymore. I haven't yet gotten to skimming through the logs because I'm running Ampache in a docker container and `docker logs` doesn't print anything useful.

**Comment by nioc** [comment]
You should have two informations in the config file.
And you don't have to enter credentials anymore, but you should have a button to go on last.fm website and sign-in. Can you check the last.fm plug-in installed version?

**Comment by PlusMinus0** [comment]
Version 000004.

I have the key and the secret in the config file.

**Comment by nioc** [comment]
Yes, you need to upgrade it by the plugin page, and then process the authentication by the button on the user's plug-in setting.
Let me know if it solves your issue.

**Comment by PlusMinus0** [comment]
Yes, updating the plugin helped. Thank you!

**Pull request merged**
