### PR TITLE
Prefer albumartist over artist

### PR DESCRIPTION
**Pull request by SaintDubious**
See issue: https://github.com/ampache/ampache/issues/2799

When building a new local catalog add the ability to use the albumartist tag instead of the artist tag.

### CODE REVIEW

**Comment by lachlan-00** [comment]
ahh, interesting. so if you tag songs as `X feat. y` but the album is `x` then all the songs would join under that artist? that's actually not a bad way of doing it.

**Comment by lachlan-00** [comment]
I think you've done a really good job in picking up all the things needed.

Because this is only on insert i don't think it should affect too much but we need to check some things

* does `update from tags` replace the album artist or recreate as a new id?
* if single disk is okay does verify on the catalog work okay too?
* this should also replace mbid (albumartist_mbid) because they might not be the same

**Comment by SaintDubious** [comment]
@SePHTaN raised some valid concerns with this approach in the Issue thread. It might make more sense to close this PR and pursue a more thorough solution for the "develop" branch. I'm happy to apply this as a simple hack to my own server just so I can get the behavior I want for my Android Subsonic API Client.

I'll leave this open for now. If people argue that they want it then I'll pursue answers to the questions @lachlan-00 raised.

Also, @lachlan-00 , thanks for the quick reply and thoughtful comments. I appreciate the fast consideration.

**Comment by lachlan-00** [comment]
closing as not ideal and will work in the open issue instead

**Pull request closed without merging**
