### PR TITLE
Subsonic 1.13.0 compatability

### LINKED ISSUE #1352: Ampache Subsonic backend with MusicBee plugin
# Environment
- Ampache version: 3.8.3-develop
- Web server + version: Apache 2.4.7
- Server operating system: Ubuntu 14.04.4
- Client operating system: Windows 10

- Client type:
  - SubSonic
# Description

I'm trying to use [MusicBee](http://getmusicbee.com/) and [this plugin](https://github.com/midwan/MB_SubSonic) to connect to Ampache using the Subsonic API.  I set up the API per the [wiki's](https://github.com/ampache/ampache/wiki/API#subsonic-api) instructions, and I'm able to connect to the API using some other apps I've tried, but the MusicBee plugin will not connect.  I worked with the developer in [this issue](https://github.com/midwan/MB_SubSonic/issues/7), and he suggested that Ampache is using an older authentication method and not the current Subsonic standard. Is this something that could be fixed, or is there something I can do to make this work?
# Logs

For what it's worth, I did a cursory scan of my logs and found a few instances of this line in the logs:

2016-07-28 10:54:44 [ampache](subsonic) -> Missing Subsonic base parameters

### LINKED ISSUE #1389: Ampache's subsonic api authentication protocol is depricated
# Environment
- Ampache version: 3.8.2-Develop
- Web server + version: Apache/2.4.7 (Ubuntu)
- Server operating system: Ubuntu 14.04
- Client operating system: Ubuntu 16.04

- Client type:
  - SubSonic (mopidy-subsonic via py-sonic) py-sonic version 0.6.1
# Description

I have subsonic clients that work fine on my ampache build. However, When I try to connect with mopidy-subsonic, or more specifically with its subsonic connection library "py-sonic" the connection fails with the following error:
`libsonic.errors.VersionError: Incompatible Subsonic REST protocol version. Server must upgrade.`

I was hoping this issue would be solved by the addition of the `legacyAuth` option in py-sonic. However I guess the ampache version is just too old.

See here for a description from py-sonics end: [https://github.com/crustymonkey/py-sonic/issues/17](https://github.com/crustymonkey/py-sonic/issues/17)

### LINKED ISSUE #1405: Subsonic API version bump needed
# Environment
- Ampache version: 3.8.3-develop
- Web server + version: lighttpd
- Server operating system: debian
- Client operating system: DSub

- Client type:
  - SubSonic
# Settings

# Description

DSub will not display podcast channel images unless version is at least 1.13.0 . I increased it in /lib/class/subsonic_xml_data.class.php  and then DSub displayed the images correctly.

I do not know if all other features of 1.13.0 API have been implemented in ampache.
# Logs

### LINKED ISSUE #1569: Is subsonic engine updatable
Hi guys,
So subsonic is on version 6.1 (1.15.0 api) which makes us 4 releases too old

Madsonic fork has been able to keep uptodate so i wonder can ampache binaries be updated as well ? I know subsonic has gone closed sourced but iff the other fork is doing it we should be able to do t as well

On another subject, i am adding some queries directly to the db, any advice on how to extend subsonic api so we standardize it ?

### LINKED ISSUE #1969: Do not separate multiple discs in albums when browsing by ID3 tags using Subsonic API
Just created a new issue so this doesn't get forgotten.

### PR DESCRIPTION
**Pull request by lachlan-00**
Begin working on subsonic api 1.13.0

If you have an api key you can now log in to recent subsonic versions using your username and key for your password!

close #1569
close #1352
close #1389
close #1405
close #1969
close https://github.com/nvllsvm/Audinaut/issues/15

* ADDED
  * updateUser (Since 1.10.1)
  * getTopSongs (Since 1.13.0)

* UNIMPLEMENTED
  * getAlbumInfo (Since 1.14.0)
  * getAlbumInfo2 (Since 1.14.0)
  * getCaptions (Since 1.14.0)
  * getVideoInfo (Since 1.14.0)
  * getScanStatus (Since 1.15.0)
  * startScan (Since 1.15.0)
  * createInternetRadioStation (Since 1.16.0)
  * deleteInternetRadioStation (Since 1.16.0)
  * updateInternetRadioStation (Since 1.16.0)
  * search (DEPRECIATED)

New Attributes

* Artist

```
        <xs:attribute name="userRating" type="sub:UserRating" use="optional"/>  <!-- Added in 1.13.0 -->
        <xs:attribute name="averageRating" type="sub:AverageRating" use="optional"/>  <!-- Added in 1.13.0 -->
```

* Directory

```
        <xs:attribute name="userRating" type="sub:UserRating" use="optional"/>  <!-- Added in 1.13.0 -->
        <xs:attribute name="averageRating" type="sub:AverageRating" use="optional"/>  <!-- Added in 1.13.0 -->
```

* Child

```
        <xs:attribute name="originalWidth" type="xs:int" use="optional"/>  <!-- Added in 1.13.0 -->
        <xs:attribute name="originalHeight" type="xs:int" use="optional"/>  <!-- Added in 1.13.0 -->
```

* PodcastChannel

```
        <xs:attribute name="coverArt" type="xs:string" use="optional"/> <!-- Added in 1.13.0 -->
        <xs:attribute name="originalImageUrl" type="xs:string" use="optional"/> <!-- Added in 1.13.0 -->
```

* User

```
        <xs:sequence>
            <xs:element name="folder" type="xs:int" minOccurs="0" maxOccurs="unbounded"/> <!-- Added in 1.12.0 -->
        </xs:sequence>
        <xs:attribute name="maxBitRate" type="xs:int" use="optional"/> <!-- In Kbps, added in 1.13.0 -->
```

### CODE REVIEW

**Comment by goliashcz** [comment]
@lachlan-00 I know you've just added support for API v.1.13 but do you plan to support even newer version? I am using Strawberry music player (https://github.com/jonaski/strawberry) which recently started to support Subsonic API but only v.1.15. Maybe a change on client side would be more simple, I do not know. What do you think?

Few years ago I used to use Amarok with Ampache API support but since there is no stable Qt5 version I switched to Strawberry which is also very good player.

**Comment by garzy** [comment]
Thanks for this work! I've been waiting for this. 

I think that subsonic related docs should be updated with a new fresh list of compatible players because it's very outdated.

For example I didn't know strawberry

**Comment by lachlan-00** [comment]
What are the differences between 1.15 and 1.13 that affect you?

For now I just brought it up to the minimum version required to fix the auth issues but I will have to update it again at some point.

**Comment by lachlan-00** [comment]
The first thing I would do @goliashcz is run this new version and log the issues you get.

It might work fine without updating but there are these functions unimplemented
getAlbumInfo (Since 1.14.0)
getAlbumInfo2 (Since 1.14.0)
getCaptions (Since 1.14.0)
getVideoInfo (Since 1.14.0)
getScanStatus (Since 1.15.0)
startScan (Since 1.15.0)

**Comment by apastuszak** [comment]
Is this update supposed to support token based authentication?

**Comment by lachlan-00** [comment]
For token auth
* User for username
* apikey for password

Passwords between subsonic and Ampache are handled differently and this is the only way to do it semi securely

**Comment by apastuszak** [comment]
How do I find out my API key?

**Comment by lachlan-00** [comment]
in the database or in your user page
image

**Comment by apastuszak** [comment]
Thank you!

**Pull request merged**
