### PR TITLE
Fix the layout when displaying images in "Find art" and some are filtered out.

### PR DESCRIPTION
**Pull request by cquike**
The logic to display each image in the table cells was broken in the case some of the images where filtered out due to size constraints.
The new logic simply keeps a counter for the table cell that gets increased only when an image is added to a cell. After 4 cells are filled a new row is created.

### CODE REVIEW

**Comment by cquike** [comment]
This should fix #2270

**Comment by lachlan-00** [comment]
ah, good one! Thank you for this I'll put some time aside to test this tonight and merge.
(ignore the codacy error this is all good.)

**Comment by lachlan-00** [comment]
first thing is we should mark it as invalid. the code thinks that 0x0 is an acceptable image
```
<?php if (is_array($dimensions) && (!(int) $dimensions['width'] == 0 || !(int) $dimensions['height'] == 0)) { ?>
```

Then we should fall back to the default blankalbum
```
        $image_url  = AmpConfig::get('web_path') . '/image.php?type=session&image_index=' . $key . '&cache_bust=' . date('YmdHis') . mt_rand();
        $dimensions = Core::image_dimensions(Art::get_from_source($_SESSION['form']['images'][$key], $object_type));
        if ((int) $dimensions['width'] == 0 || (int) $dimensions['height'] == 0) {
            $image_url = AmpConfig::get('web_path') . '/images/blankalbum.png';
        }
```

and move the select button into the area where it's actually used
```
                [<?php echo (int) ($dimensions['width']); ?>x<?php echo (int) ($dimensions['height']); ?>]
                [<a href="<?php echo AmpConfig::get('web_path'); ?>/arts.php?action=select_art&image=<?php echo $key; ?>&object_type=<?php echo $object_type; ?>&object_id=<?php echo $object_id; ?>&burl=<?php echo base64_encode($burl); ?>"><?php echo T_('Select'); ?></a>]
```

That leaves me with this patch
```
         $key        = $count * 4 + $j;
         $image_url  = AmpConfig::get('web_path') . '/image.php?type=session&image_index=' . $key . '&cache_bust=' . date('YmdHis') . mt_rand();
         $dimensions = Core::image_dimensions(Art::get_from_source($_SESSION['form']['images'][$key], $object_type));
+        if ((int) $dimensions['width'] == 0 || (int) $dimensions['height'] == 0) {
+            $image_url = AmpConfig::get('web_path') . '/images/blankalbum.png';
+        }
         if (!isset($images[$key]) || !Art::check_dimensions($dimensions)) {
             echo "<td>&nbsp;</td>\n";
         } else { ?>
@@ -41,14 +44,14 @@ while ($count <= $rows) {
                 <a href="<?php echo $image_url; ?>" title="<?php echo $_SESSION['form']['images'][$key]['title']; ?>" rel="prettyPhoto" target="_blank"><img src="<?php echo $image_url; ?>" alt="<?php echo T_('Art'); ?>" height="175" width="175" /></a>
                 <br />
                 <p>
-                <?php if (is_array($dimensions)) { ?>
+                <?php if (is_array($dimensions) && (!(int) $dimensions['width'] == 0 || !(int) $dimensions['height'] == 0)) { ?>
                 [<?php echo (int) ($dimensions['width']); ?>x<?php echo (int) ($dimensions['height']); ?>]
+                [<a href="<?php echo AmpConfig::get('web_path'); ?>/arts.php?action=select_art&image=<?php echo $key; ?>&object_type=<?php echo $object_type; ?>&object_id=<?php echo $object_id; ?>&burl=<?php echo base64_encode($burl); ?>"><?php echo T_('Select'); ?></a>]
                 <?php
             } else { ?>
                 <span class="error"><?php echo T_('Invalid'); ?></span>
                 <?php
             } ?>
-                [<a href="<?php echo AmpConfig::get('web_path'); ?>/arts.php?action=select_art&image=<?php echo $key; ?>&object_type=<?php echo $object_type; ?>&object_id=<?php echo $object_id; ?>&burl=<?php echo base64_encode($burl); ?>"><?php echo T_('Select'); ?></a>]
                 </p>
             </td>
 <?php
```
and a decent visual that doesn't allow selecting bad images
Screenshot_2020-01-22_21-07-40

**Comment by AshotN** [comment]
Why even display album art that can't be used?

**Comment by lachlan-00** [comment]
the code has always had it that way so it's not strictly needed but i do like it to show me that something was found even if they were all failures

A totally blank page would make it look like nothing happened.

**Comment by AshotN** [comment]
Can write “No suitable results” 

Just looks odd to have a bunch of empty images.

**Pull request merged**
