### PR TITLE
Prefer cover art when gathering art from embedded tags

### PR DESCRIPTION
**Pull request by scufre**
Sort found art in tags by a priority list (album or artist).
Refactor to remove some duplicate code to gather art in tags which also addresses in a different way #3537.

### CODE REVIEW

**Comment by lachlan-00** [comment]
one thing i think we've done now is make all artists pick up the front cover now?

Having it wide open for all the types means that artist search is going to fill up with front covers

**Comment by lachlan-00** [comment]
would there be different priorities based on the $art->type? (artist/album/song)

**Comment by scufre** [comment]
> would there be different priorities based on the $art->type? (artist/album/song)

Missed this.  Thanks for pointing this out.

Just pushed some updates where I introduced a priority list for artist, also changed a bit to not filter art when looking for artists and instead sorting it using its corresponding priorities and additionally moved some very similar code used to gather art from tags to a common place which ends up solving #3537 in another way (I'd say this is better as I think the issue was caused by having two ways of fetching art from tags for different stages which ended up being slightly different.

**Comment by lachlan-00** [comment]
cleans up good. just moved things and ran php-cs and merging now!

**Pull request merged**
