### PR TITLE
Update tools.js - fix issue #2140

### PR DESCRIPTION
**Pull request by Rhythm-of-Time**
This will make the Add New... artist in Song editor work again, like described in issue #2140. 

Instead of changing "===" to "==" to avoid strict comparison and allow for automatic type casting, one could also implicitly declare the type by using double quotes and leave the strict comparison in place: === "-1". Maybe this is cleaner?

I noticed that this version of tools.js is using double instead of single quotes (unlike the old one). This may come handy when using JSON, but adding HTML becomes more difficult, because all double quotes contained in strings need to be escaped - see line 339. Hard to read...

### CODE REVIEW

**Comment by Rhythm-of-Time** [comment]
For PHP 7.4, Travis CI build failed with the following error:

PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in ./modules/oauth/OAuth.php on line 126

I'll fix at the file and make another pull request...

**Comment by Rhythm-of-Time** [comment]
Frankly, I have no idea why the tests keep failing. May this be related with the versions of php-cs-fixer.phar i used? First I tried the one from the download link in the Ampache Wiki, which complained about my local PHP version being above 7.2 (actually 7.3.11). Then I used v2.16.1, which did change the line endings of all files to LF. Any suggestions what else could be the problem with Formatting?

**Comment by lachlan-00** [comment]
Thanks! Will test out and merge ASAP

**Comment by lachlan-00** [comment]
thanks for becoming a contributor to ampache!

**Comment by Rhythm-of-Time** [comment]
Thank you for fixing my github mess...

**Pull request merged**
