### PR TITLE
adding year to several views/ gather art when update from tags

### PR DESCRIPTION
**Pull request by noyse27**
adding column/row Year on:

- album
- song
- nowplaying
- recently played

making albums searchable with year from nowplaying year

gather art when updating album from tags

change last.fm scheme
from https to http as described in Last.fm scrobbler api
https://www.last.fm/api/scrobbling 

> As with all our write web services, requests must be sent as HTTP POST requests to http://ws.audioscrobbler.com/2.0/ with form urlencoded parameters in the body of the request. The text encoding must be UTF-8.

### CODE REVIEW

**Comment by noyse27** [comment]
seems i did something wrong but what?

**Comment by antgel** [comment]
I'd suggest rebasing the feature branch, potentially squashing commits. There are weird merges and duplicates going on, and the `git log` doesn't need that amount of detail IMHO.

**Comment by noyse27** [comment]
@antgel 
unfortunately i do not understand what do you want me to do and why :( the problem is i'm a newbee in working with git.

**Comment by wagnered** [comment]
@noyse27,

Sorry, I haven't commented earlier, but I've been very busy and the current policy is that all enhancement PR's are on hold.  I don't have the time to patch everyone's PR to see how it affects all other parts of Ampache.

@antgel is correct: see [Squash several Git commits into a single commit](https://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit).

The PR is very cluttered which makes it very hard to understand what's going on. All the changes should have been made before committing and pushing to your  remote. OR following the directions from the URL above, all the commits can be squashed into one commit.

Also, when wanting to add a new feature, a feature branch should be created on your local repo. All the changes should be done in that branch.  When all the changes are made, the branch can be merged/squashed into the  develop branch before pushing to your remote.

I do appreciate your interest in making Ampache better.  I like the PR, and don't understand why this feature wasn't added at Ampache's beginning.

**Comment by noyse27** [comment]
@wagnered 
so because i am not able to make a squash (i tried several times but it never makes only one commit) i decided to stay on my own fork with these changes :(

**Comment by antgel** [comment]
@noyse27 I'm quite good at rebasing. Can you post a screenshot of your `git rebase -i` just before you save and close it and the rebase itself starts?

**Pull request closed without merging**
