### PR TITLE
Check edit tag write

### PR DESCRIPTION
**Pull request by wagnered**
Because of the interdependence with the changes in #2898, `art:::check_for_duplicate`was made public for access by `SongId3TagWriter.php`.  Also simplified logic for determining which images to write.

### CODE REVIEW

**Comment by wagnered** [comment]
Should have I waited for #2898 to be merged?  I think that if #2898 is merged first, there should be no conflicts when this is merged.

**Comment by lachlan-00** [comment]
> Should have I waited for #2898 to be merged? I think that if #2898 is merged first, there should be no conflicts when this is merged.
> ------EDIT----
> Looking at the file diffs, it looks like this PR will be merged with #2898 whichever is done first

just merged from develop, looks okay. just have to run through it.

**Comment by wagnered** [comment]
That's interesting because earlier, it complained of merge conflicts. Now they are gone.   Very Interesting....

I'm  not very detail oriented so I'm trying to check every aspect of writing the tags.  Right now, I'm trying to find a reason to write to mbids to the files.  Is there a way to import mbids into the db from other sources than the song which was tagged by picard: Maybe a plugin? 

It will probably be necessary to pull your commits into my local before pushing my new changes.

Please advise me what you think needs to be changed, and let me do it: That way, I'll learn more efficiently.  That's how @Afterster responded to my PRs and I appreciated his approach.

Also a constructive discussion might ensue.  For example in the function ` public function update(array $data)`in Song.php, I added, `$changed[] = $key;` to almost every case in the switch statement.  You then added a redundant `(string)` conversion to each.  Except for the default case, `$key` can only be a string.  It's. always good to get aother viewpoit.

**Comment by lachlan-00** [comment]
> I'm not very detail oriented so I'm trying to check every aspect of writing the tags. Right now, I'm trying to find a reason to write to mbids to the files. Is there a way to import mbids into the db from other sources than the song which was tagged by picard: Maybe a plugin?

mbid can be filled from something like theaudiodb (https://www.theaudiodb.com/api_guide.php) which i think is a good plugin to work from.

anything with a `get_metadata` plugin can probably be extended though. I think even the musicbrainz api can search by name but in our plugin it requires an mbid. @SePHTaN has been thinking about metadata a lot. there's still a lot to be done in this area for sure
 
> Please advise me what you think needs to be changed, and let me do it: That way, I'll learn more efficiently. That's how @Afterster responded to my PRs and I appreciated his approach.

I don't think i've changed anything functional from the merges but haven't gone through this one yet. it's merged up to 61006aa02

> Also a constructive discussion might ensue. For example in the function ` public function update(array $data)`in Song.php, I added, `$changed[] = $key;` to almost every case in the switch statement. You then added a redundant `(string)` conversion to each. Except for the default case, `$key` can only be a string. It's. always good to get aother viewpoit.

that came from https://github.com/ampache/ampache/commit/a6971671c376ff2826c595d733ba8769e1d78719

the index could be a numerical index so i'm assuming it's required to be string elsewhere?

**Comment by lachlan-00** [comment]
oh and re plugins/get_metadata/other places to update, i want update catalog (`bin/cli run:updateCatalog -u`) to be extended to sync things missing with these plugins so things like licenses, labels, artists, etc can be synced with these plugins.
That might also be an option to write to tags from here / a different option in updateCatalog

**Comment by wagnered** [comment]
> the index could be a numerical index so i'm assuming it's required to be string elsewhere?

In this particular switch, any numeric key will be directed to the 'default' case in which the key is ignored.  Also, whether a key is numeric or string depends on **context**.

> That might also be an option to write to tags from here / a different option in updateCatalog

From what I read, the cli just bypasses `Catalog::process_action($action, $catalogs, $options = null)` and directly accesses the actual process.  Shouldn't be difficult to implement.

**Comment by SePHTaN** [comment]
>  Is there a way to import mbids into the db from other sources than the song which was tagged by picard: Maybe a plugin?

@wagnered 

below is some code i already do use for multi-artist feature to get additional data from musicbrainz plugin, maybe its what you are looking for, it has some formatting/identation issue at the moment as it is work in progress.
my idea is to add some functions/methods to the plugin for gathering artist metadata (getArtist, getAlias) for example.
I also just copy/pasted with the debug_events i used to confirm the correct funtionality, so yopu can test yourself quickly.

```
        $mbrainz  = new MusicBrainz(new RequestsHttpAdapter());
        $includes = array(
            'artists',
            'aliases',
            'releases',
            'artist-credits'
        );
        try {
            $track = $mbrainz->lookup('recording', $mbid, $includes);
        } catch (Exception $error) {
            debug_event('MusicBrainz.plugin', 'Lookup error ' . $error, 3);

            return null;
        }

        $results = array();

        if (count($track->{'artist-credit'}) > 0) {
            $artist                   = $track->{'artist-credit'};
            $artists                 = array_column($artist,  'artist');
            $artistsAliases          = array_column($artists, 'aliases');
            $artistsAlias            = $artistsAliases[0];
            $aliasCount              = count($artistsAlias);
            $aliasName               = $artist[0]->name;
            $artistName              = $artists->name;
            // REMOVE_ME only for testing remove when done
            //debug_event('MusicBrainz.plugin', 'Aliases Count : ' . var_export($aliasCount, true), 3);
            // REMOVE_ME only for testing remove when done
            //debug_event('MusicBrainz.plugin', 'Artist Aliases: ' . var_export($artistsAlias, true), 3);

            $results['artists']       = array_column($artists, 'name');
            $results['mb_artistid']   = array_column($artists, 'id');
            $results['artist_type']   = array_column($artists, 'type');
            $results['artisttype_id'] = array_column($artists, 'type-id');
            $results['joinphrase']    = array_column($artist,  'joinphrase');
            //$results['joinphrase']   = array_column($track->{'artist-credit'}, 'joinphrase');
            //$results['artistname']   = $track->{'artist-credit'}[0]->name;
            $results['title']        = $track->title;
            if (count($track->releases) == 1) {
                $release          = $track->releases[0];
                $results['album'] = $release->title;
            }
            $results['primary'] = null;
            for ( $i=0; $i < $aliasCount; $i++) {
                $primary  = $artistsAlias[$i]->primary;
                $name     = $artistsAlias[$i]->name;
                if (isset($primary) && ($aliasName == $name)) {
                    $results['primary']   = $primary;
                    $results['aliasname'] = ($primary == false) ? $artist[0]->name : null;
                }
                // REMOVE_ME only for testing remove when done
                //debug_event('MusicBrainz.plugin', $i . ' primary : ' . var_export($primary, true), 3);
                //debug_event('MusicBrainz.plugin', $i . ' Name    : ' . var_export($name, true), 3);
                //debug_event('MusicBrainz.plugin', $i . ' SortName: ' . var_export($sortname, true), 3);
            }
        if (count($track->releases) > 0) {
            $releases     = $track->releases;
            $key          = array_search($song_info['mb_albumid'], array_column($releases, 'id'));
            $release      = $track->releases[$key];
            $albumartist  = $release->{'artist-credit'};
            $albumartists = array_column($albumartist, 'artist');
            $results['albumartist']        = array_column($albumartists, 'name');
            $results['mb_albumartistid']   = array_column($albumartists, 'id');
            $results['albumartist_type']   = array_column($albumartists, 'type');
            $results['albumartisttype_id'] = array_column($albumartists, 'type-id');
            $results['aa_joinphrase']      = array_column($albumartist,  'joinphrase');
        }
        }
        // REMOVE_ME only for testing remove when done
        //debug_event('MusicBrainz.plugin', ' Results : ' . var_export($results, true), 3);

        return $results;
    } // get_metadata
}
```

**Comment by wagnered** [comment]
@SePHTaN Thanks,.  With this PR,  I'm only concerned with writing the db data to the file. 

I don't want to think about displaying the multiple artists. ;'>

**Comment by wagnered** [comment]
@SePHTaN   Question: Are both mb_trackid and mb_releasetrackid being used for your PR? 

@lachlan-00, 
1. Having  both track mbid and album mbid with identical db names, I would like to change one or both to be unique and more precisely labeled for writing file tags. 
2. Are both mbids above used in the grouping/searching of albums and associated songs? I would think that only the release track mbid would be necessary?

**Comment by SePHTaN** [comment]
for getting the artist metadata only the "Musicbrainz Recording Id"  = musicbrainz_recordingid = UFID for id3v2 = musicbrainzb_trackid for vorbis/ape = mbid in db is used and needed

**Comment by wagnered** [comment]
I don't think UFID is appropriate for importing musicbrainz_recordingid.  Currently, musicbrainz is the only org that adds UFID, but that can change at any time. It could create a problem in the future.  For Ampache's purpose, it could be added as a TXXX entry. 

Maybe there has been an agreement among the recording companies and musicbrainz.org to let musicbrainz be the sole user of the UFID id3v2.3 frame.   I don't remember UFID being in any of my files if there was no other musicbrainz IDs in the TXXX frames.

Never mind.... ; ' >

**Comment by wagnered** [comment]
The logic in `SongId3TagWriter::class` wasn't designed to function outside the Song model from which it was relocated.
The Album model also wasn't designed to use the `SongId3TagWriter class`. The  `SongId3TagWriter class` should probably be renamed as it also writes flac pictures and vorbiscomments.

The Album model wasn't parsing/splitting the full album name passed in from theweb interface..

Images from flac files can now be imported from file tags.  Maybe a false memory, but Ithought it could already do it.

Here are the mbids and other data that can be written.

Song->mbid (UFID?)
Album->mbid (MusicBrainz Album Id?)
 MusicBrainz Release Group Id,
Original release year

Also I would like an opinion about any other musicbrainz tags  that would be usefull to write to file? Maybe artist mbid?

**Comment by lachlan-00** [comment]
> The logic in `SongId3TagWriter::class` wasn't designed to function outside the Song model from which it was relocated.
> The Album model also wasn't designed to use the `SongId3TagWriter class`. The `SongId3TagWriter class` should probably be renamed as it also writes flac pictures and vorbiscomments.

VaInfo stands for something i assume? Various Audio Info?

Maybe VaWriter? one does the retrieval and the other does the writing
 
> Here are the mbids and other data that can be written.
> 
> Song->mbid (UFID?)
> Album->mbid (MusicBrainz Album Id?)
> MusicBrainz Release Group Id,
> Original release year
> 
> Also I would like an opinion about any other musicbrainz tags that would be usefull to write to file? Maybe artist mbid?

It looks like UFID is actually an array where the track id is defined with musicbrainz as the owner
image

Which when i print gives me this so it looks like it allows multiple ID's (which would be super cool to id your own files inside ampache under your server name)
```
id3v2 UFID: Array
(
    [0] => Array
        (
            [frame_name] => UFID
            [frame_flags_raw] => 0
            [data] => 93496b5b-c221-4dd9-b32f-8b5490296457
            [datalength] => 59
            [dataoffset] => 1361
            [framenamelong] => Unique file identifier
            [framenameshort] => unique_file_identifier
            [flags] => Array
                (
                    [TagAlterPreservation] => 
                    [FileAlterPreservation] => 
                    [ReadOnly] => 
                    [GroupingIdentity] => 
                    [compression] => 
                    [Encryption] => 
                    [Unsynchronisation] => 
                    [DataLengthIndicator] => 
                )

            [ownerid] => http://musicbrainz.org
        )

)
```

I'm going to add release_status to the album table which i think is an important column for splitting possible dupes (eg. promo release or official release status) but here's my list that i think are needed

* originalyear: 2015
* catalognumber: KOB134
* barcode: 0740030480952
* tool name: Media Center
* MusicBrainz Album Type: ep
* MusicBrainz Album Status: official
* MusicBrainz Album Id: e9fb1197-d863-4583-a52e-c4be26d84892
* MusicBrainz Artist Id: d75d1f08-bbb8-4eae-9877-399ca9121197
* MusicBrainz Album Artist Id: d75d1f08-bbb8-4eae-9877-399ca9121197

**Comment by usox** [comment]
> Adding Artist mbid will Confound the issue a bit. I think it's rather trivial since @usox added getters for the id to the models.

:tada: 

> Hey @usox, is it too early to think about using foreign keys for storing/accessing all the one-to-many and many-to-one relationships?

It's never too early to think about foreign keys, but it will take a while until we'll be able to start using them. After replacing the current `Dba` class, we can finally start to model our data structures in orm entities and add those foreign keys.
In edge, there are about 100 files left which currently import the Dba class - I made good progress so far....

**Comment by wagnered** [comment]
@usox, not sure if there is a better "forum" to ask this question and make the following suggestion:

I've been working with json documents in one of the features I've been working on.  I like the idea of keeping multiple pieces of related data in one "capsule" located in one row of a json column.  Could some kind of generic query-builder for json documents be created for the orm?

**Comment by wagnered** [comment]
> which would be super cool to id your own files inside ampache under your server name.

Because two bits of info are required for thesong mbid with one assumed to be musicbrainz.org, this could be a good column for json documents: `mb_trackid = {"id" => "data", "ownerid" => "http://musicbrainz.org"};`  This would make writing to it file much easier.

**Comment by wagnered** [comment]
While cleaning the last batch of changes using `composer fix-cs`:

```
Detected deprecations in use:
- Configuration file `.php_cs` is deprecated, rename to `.php-cs-fixer.php`.                                           - Given configuration is deprecated and will be removed in 3.0. Use configuration ['operators' => ['=' => 'align']] as replacement for ['align_equals' => true].
- PhpCsFixer\Config::create is deprecated since 2.17 and will be removed in 3.0.
- Rule "blank_line_before_return" is deprecated. Use "blank_line_before_statement" instead.
- Rule "lowercase_constants" is deprecated. Use "constant_case" instead.
```

**Comment by usox** [comment]
> While cleaning the last batch of changes using `composer fix-cs`:
> 
> ```
> Detected deprecations in use:
> - Configuration file `.php_cs` is deprecated, rename to `.php-cs-fixer.php`.                                           - Given configuration is deprecated and will be removed in 3.0. Use configuration ['operators' => ['=' => 'align']] as replacement for ['align_equals' => true].
> - PhpCsFixer\Config::create is deprecated since 2.17 and will be removed in 3.0.
> - Rule "blank_line_before_return" is deprecated. Use "blank_line_before_statement" instead.
> - Rule "lowercase_constants" is deprecated. Use "constant_case" instead.
> ```

php-cs-fixer >=2.19 added these deprecation warnings for 3.0. I pinned php-cs-fixer in develop to 2.18.*.
The upgrade to php-cs-fixer ^3 already took place in edge.

**Comment by usox** [comment]
> @usox, not sure if there is a better "forum" to ask this question and make the following suggestion:
> 
> I've been working with json documents in one of the features I've been working on. I like the idea of keeping multiple pieces of related data in one "capsule" located in one row of a json column. Could some kind of generic query-builder for json documents be created for the orm?

This is definitely possible, doctrine/dbal supports the json datatypes of mysql/postgresql. You can performs sql-operations (e.g. search) within the json structures saved in a json column. Also the dbl query-builder can handle these.
Searching in json data structures may have some impact on the query perfomance though.

**Comment by wagnered** [comment]
I'm taking the liberty of adding `release_status` to the album table  so I can continue developing the write logic.

**Comment by lachlan-00** [comment]
If you can wait till Sunday I've just about finished my db updates for release_status (plus others) and will be merging them when I get home.

Then I can update your pull with the changes and you'll get the db updates.

**Comment by lachlan-00** [comment]
Sorry if you already have done that I've just been doing a lot at work this week and haven't had the time to do it properly before merging

**Comment by wagnered** [comment]
My PR isn't ready to be merged
I would rather fetch your changes from upstream/develop and merge locally instead of pulling the changes from my remote.   It might seem like "six of one or half-dozen of the other."   I just don't like merge conflicts when I do a pull from my own remote, fix them then push them back to my remote..  Seems like a lot of unecessary work. I'll wait for your changes to be merged into develop before reverting my changes for release_status.

**Comment by lachlan-00** [comment]
> My PR isn't ready to be merged
> I would rather fetch your changes from upstream/develop and merge locally instead of pulling the changes from my remote. It might seem like "six of one or half-dozen of the other." I just don't like merge conflicts when I do a pull from my own remote, fix them then push them back to my remote.. Seems like a lot of unecessary work. I'll wait for your changes to be merged into develop before reverting my changes for release_status.

no problem, i'm running a major change at work tomorrow but i'm close to done. the scale of adding just a few columns really exploded.

**Comment by SePHTaN** [comment]
@wagnered,
i hope i can finish part1 of the modification of the musicbrainz-plugin until tomorrow, allowing to fetch much more information to enrich the userexperience of ampache and to allow to better differentiate albums pushing away some problems lachlan is trying to circumvent.
From my point of view the problems only exist as its almost impossible to reliable separate albums from each other without a identifier that is garantied to be unique, like musicbrainz id's for the individual entities.

When its ready i will make a pull request as draft, as i don't think it should be right away part of ampache without thorough review and discussion.

part1 mainly relies on mb_trackid and mb_albumid (with a try for album name when its missing), without those the plugin simply exits without doing anything.
in part2 i will look into a way to identify the given track as exactly as possible with the information that is already in the tags and first do a full search before a lookup.
you mentioned above that the UFID tag isn't in any of your files, so i am looking into a different identification tag thats unique per recording and is more widely used by users.
i think of barcode, isrcs for example together with the track number and/or name it should be possible to identify an track and retrieve the mb_trackid

as i am picard user for a really long time i hope someone without musicbrainz tagging use szenario could give me some suggestions/info what they might have as tags thats really unique for identifying a track/song

**Comment by wagnered** [comment]
As for UFID,  I managed to get Picard installed and running So I now have mp3, Vorbis and flac files with MusicBrainz data. 

> When its ready i will make a pull request as draft.

That's good. There always seems to be a push to add new features.

**Comment by SePHTaN** [comment]
for the moment if mb_albumid and/or mb_trackid is missing, i will try to check for barcode or isrc as they are unique too and especially isrc, might be present in many files.
I than only must arrange the order of the lookups to get reverse from release to the track by tracknumber/name which always should be present.
My most concern is scanning speed. Musicbrainz only allows one query/lookup per second, so i definitely want to limit lookups.

**Comment by wagnered** [comment]
I don't know if the work I've done affected the "Gather Song Art" feature.  Mainly because I don't understand the comment:
> ; Gather song art
; Gather song art additionally to the album art. This will add each
; image of a song into the database. If your database contains
; many songs not related to an album this should possibly be set to true.

I understand the concept of album art (cover front, cover back, cd label side etc)  I don't know what "song art" is.  IMHO the comment seems to contradict itself. Is this some way of gettiing around the "orphaned" status if the song doesn't list the album title?  Or possiby a compilation with cover art from each song's original release?

Also I need to know what will need to change, if anything, when the metadata is written back to the file.

**Comment by lachlan-00** [comment]
@wagnered the release_status pull has merged now.

**Comment by wagnered** [comment]
I'm trying to determine what metadata to write to files.  Is there a connection among tables "label", "label_assoc" and the "label" column in the "song_data" table? I had planned on writing Song::label to file until I noticed the two tables.

As there is a distinction between 'publisher' and 'label' but they are assumed synonymous by Ampache, id3v2 specs and Picard, one must have an instinct to know the difference between the two.

**Comment by lachlan-00** [comment]
to me it looks like label in song_data is the string from the tags.
it's probably not linked to the label table correctly as it's the string and not it label ID. and i think will only be used for display purposes.

seems like an odd one, it might be a column i added ages ago and didn't do things properly as an early Lachlan mistake.

it should probably be dropped for the label_assoc/label combo instead

**Comment by lachlan-00** [comment]
or instead of dropping it's changed to the label id instead

**Comment by wagnered** [comment]
>  to me it looks like label in song_data is the string from the tags.

It is as I believe it should be, whether it be in song_data or elsewhere.

> it's probably not linked to the label table correctly as it's the string and not it label ID.

What is the intended purpose of the label/label_assoc table pair?

Nothing gets imported into the label/label_assoc tables from a flac file (Vorbiscomments): which is written to import both 'publisher' and 'label'. Is there a config switch that needs to be set to enable the label table?  So as it exists, Song->label is the metadata that will be written to the file.  The logic should be agnostic concerning which table it came from.

> seems like an odd one, it might be a column i added ages ago and didn't do things properly as an early Lachlan mistake.

I didn't check it's history, but I believe it's been a property of the Song model for a long time. Not that my memory is that great ; ' >

> but here's my list that i think are needed

You listed 'tool name: Media Center'.  I think this would be unique to Ampache: I don't see it in any specs.  To which table should the `tool_name` column be added?  Or should I just ignore this for now?

**Comment by lachlan-00** [comment]
may be out of date but vorbiscomments are read by the label for me
`(Ampache\Module\Util\VaInfo) -> Vorbis tag: label value: Spikefarm Records`

Oh yes you're right there is actually a config item for enabling labels which are off by default. that might be why it was separated from song_data
image

**Comment by lachlan-00** [comment]
i merged the recent updates into the pull, vainfo had some more fields and the art collector had some changes that were merged.

biggest difference your your pull is the art type checks allows more art types (i put this check in the asf and flac checks too)
image

and the dupe check array changes the collector function stops adding the same picture for each file in an album/artist
image

**Comment by wagnered** [comment]
Actually, I've incorporated an alternative method to prevent duplication.  And I planned on adding the array of alternate picture ids.

You know I've been working in that area, but you refused to consult with me about those changes?  I commented about this previosly. 
 Now It looks like I'll be force-pushing changes to  my remote. and fixing merge conflicts when I update from upstream/develop.

**Comment by wagnered** [comment]
OK, Now I understand about the label table.  I just gotta search for object_type 'song'.when the metadata is written to file.

**Comment by wagnered** [comment]
Update on the `label` situation:  If the label is edited on the song edit dialog, It's the label column in the song table that gets modified, not the 'name' column in the label table.  Is that according to spec?

> ...that might be why it was separated from song_data.

You are correct in that Song->label should be an id linked to the label table.  The song's label doesn't get removed if the catalog is deleted. This is an instance that begs a foreign key:  No worry about garbage collection

**Comment by SePHTaN** [comment]
@wagnered
i have a question about your changes to VaInfo in commit 05abcb4a256ab2aba803dc301f2e945ab8f81b0e
```
case 'musicbrainz_recordingid':
    $parsed['mb_recordingid'] = $data[0];
    break;
```
According to Picard [Tag_Mapping](https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html)
musicbrainz_recordingid is an internally used name for the tag
for Vorbis the tag-name is : MUSICBRAINZ_TRACKID and for id3v2 : UFID:http://musicbrainz.org

and for musicbrainz_releasetrackid, this is the id of an track on an specific medium aka CD-Release
the musicbrainz_trackid is the id for an recording which can be present on different CD's 
so the same musicbrainz_trackid can be present on different cd's (original album, Sampler1, Sampler2)
and each track an such an cd then has an unique musicbrainz_releasetrackid representing this recording on exactly that release
with other words musicbrainz_trackid == recording !== musicbrainz_releasetrackid == track on medium
thats how i read the [musicbrainz database schema](https://musicbrainz.org/doc/MusicBrainz_Database/Schema#Recording)

maybe i misinterpreted it somehow, but anyway i tought good reason to ask the question

**Comment by wagnered** [comment]
You are correct and that is one of the reasons that I put the PR in draft mode (not ready to be reviewed).  The other reason is that i seem to be finding or causing bugs during the development.  Being retired, I tend to put in many hours.  Sometimes it gets the best of me  and I copy/paste the wrong text.  

Thanks for your explanation and bringing that mistake to my attention.

Never-the-less, I have come into possession of apparently old releases with different tag names. Perhaps the names have evolved over time. Don't know if they were added by Picard or some other app.  Anyway, I understand that Picard only adds the data that some human submits to the database.

**Comment by SePHTaN** [comment]
>  I have come into possession of apparently old releases with different tag names

Thats a thing i have on my agenda also, as i also noticed that older audiorips might have tags divergent from actuel implementations in taggers like picard.
As long as only the tag naming changed without any overlapping between different tags for mbids it would be possible to work around those false implementations and retrieve them correctly.

**Comment by wagnered** [comment]
I am closing to rethink my approach.  Hopefully I can isolate the  design flaws and work on each  without any one interfering with the other.

**Pull request closed without merging**
