### PR TITLE
review of strings part 1

### PR DESCRIPTION
**Pull request by kuzi-moto**
first part of my review. Lots of changes.

### CODE REVIEW

**Comment by stebe** [comment]
I'm doing a quick look at this. 


` show_confirmation(T_("There Was a Problem"), T_("Couldn't delete this Artist."), AmpConfig::get('web_path'));`

Are the sentences in the correct tense?  Using "Was" would imply that the problem is gone but really it still exists. Therefore shouldn't the sentence be "There Is a Problem"?


Same in this sentence, shouldn't this be "There is an error...".

       ` printf (T_('There was an error trying to open "%s"'), $path);`

**Comment by lachlan-00** [comment]
This is after you confirm the action. So it's past in the sense of your personal confirmation

Ie
are we doing this now?

*Problem
When I did this action there was a problem

**Comment by kuzi-moto** [comment]
I think it should be "was" as it's referring to something that happened in the past, since the action has already ended. Think of if it said "there was a problem with the action", it wouldn't make sense to say "there is a problem with the action" since it's not currently ongoing.

**Comment by lachlan-00** [comment]
In my regex for get_cat[e|a]gories it looks like you've got all the mispelled ones. so that's good and I like all these changes. :) i'll merge this so i can use it live and have a deeper look

@stebe please feel free to go over the original pull (https://github.com/ampache/ampache/pull/1957) and leave some comments or changes you might see. we're a few weeks from merging as i'll be away next week.

**Pull request merged**
