### PR TITLE
Use correct fields type in modules and localplay

### LINKED ISSUE #1339: Password shown in cleartext in localplay instances
# Environment

 * Ampache version: latest dev
 * Web server + version:
 * Server operating system:
 * Client operating system:

 * Client type:
   - Web

# Settings

# Description

Under localplay instances settings tab, the password are shown in cleartext. They should be "***" and an input of type password in the form.

# Logs

### PR DESCRIPTION
**Pull request by Phyks**
I fixed the `types` associated to modules in localplay and catalog and used them to display the correct input, with the correct type, preventing passwords from appearing in cleartext.

I also took profit of the new HTML5 types (int and url) to have a better experience on browsers which support them.

This fixes #1339.

### CODE REVIEW

**Comment by Psy-Virus** [comment]
@Phyks, does this include a password check field?
Because If you cant see your password input, you can't check, that you didn't misspelled anything...

**Comment by Phyks** [comment]
Indeed, it does not. I could either add a password check or a toggle between password and text type.

**Comment by Psy-Virus** [comment]
If I get it right, these passwords are pre set, right? I think a toggle would be the better idea.

**Comment by Phyks** [comment]
Depends on the page. For edit forms, yes. For adding a new catalog / localplay instance, they are not.

**Comment by Afterster** [comment]
Merging it anyway as it is still better than current code :smile:. Thanks.

**Comment by Phyks** [comment]
Thanks :)

@Psy-Virus Would be better to open a new issue with the expected best behavior please :)

**Pull request merged**
