### PR TITLE
New feature:  Movie content Certification and TV show content rating.

### PR DESCRIPTION
**Pull request by wagnered**
Movie content certification can be grabbed by country from Tmdb.

### CODE REVIEW

**Comment by wagnered** [comment]
I don't understand why `lib/class/amperror.class.php` failed the Travis tests.  I never even opened it for edit.

**Comment by Afterster** [comment]
@wagnered I didn't give you feedback yet on this PR, sorry. This is not because I don't care but because I'm doing major changes locally that I don't want to share right now (to avoid noise). You will understand in few weeks (I hope), but thank you for your work.

**Comment by wagnered** [comment]
@Afterster,

OK, but can I safely bring my local repository up-to-date by doing a
"git merge upstream/develop" with that PR being open? Or should I just
close the PR and wait for your changes?

On 03/11/2016 01:46 PM, Afterster wrote:
> @wagnered <https://github.com/wagnered> I didn't give you feedback yet
> on this PR, sorry. This is not because I don't care but because I'm
> doing major changes locally that I don't want to share right now (to
> avoid noise). You will understand in few weeks (I hope), but thank you
> for your work.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/pull/1040#issuecomment-195566729>.
> 

-- 
73 From
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment]
I'll close this and wait for the Laravel version.

**Pull request closed without merging**
