### PR TITLE
Catalog access

### PR DESCRIPTION
**Pull request by lachlan-00**
@troycarpenter i've fixed up all the things i wanted to do and will start testing this out a bit more before merging.

Thanks again for the great work as this was really clean to work on and functionally working really well

### CODE REVIEW

**Comment by lachlan-00** [comment]
moving here now too as this is basically ready
https://github.com/ampache/ampache/pull/3300

**Comment by troycarpenter** [comment]
My pleasure.  I understand if you wanted to change things a bit.  I had a crisis of names halfway through the feature as well.  That's why I never moved my production server to this code...to avoid stranding that server if the database names/structures changed.

**Comment by troycarpenter** [comment]
Thanks.  I figure it was on me to make it conform as much as possible with the existing code, but I know I missed many things.  I look forward to this being in the development branch so I can address some things using the final submitted code.

**Comment by troycarpenter** [comment]
I've looked at some of the commits.  It looks like you are merging some other big changes.

**Comment by lachlan-00** [comment]
> I've looked at some of the commits. It looks like you are merging some other big changes as well.

just naturally as you use things you tend to notice lots of little things missing/extra BUT this is done. i think it should go smoothly for everyone on develop now

**Comment by troycarpenter** [comment]
Do I (or you) need to write up a breaking change for the older private catalog feature and how to duplicate that functionality with the new catalog access feature?

**Comment by lachlan-00** [comment]
i'll put it in the wiki and link it all up.

I've tested a few times and it migrated my private groups the way i wanted it to so i'll write it up now

**Comment by troycarpenter** [comment]
Cool.  Once I find some time to digest the changes you've made, I'll look and see if I still need to do some of the other changes I thought of after submitting the code...like adding a way on the create catalog page to add a catalog to the proper groups during creation so the admin doesn't have to do that afterwards...and by extension have the same functionality on the catalog edit screen.

I can also start looking at some of the other bugs I've written...

**Comment by lachlan-00** [comment]
> Cool. Once I find some time to digest the changes you've made, I'll look and see if I still need to do some of the other changes I thought of after submitting the code...like adding a way on the create catalog page to add a catalog to the proper groups during creation so the admin doesn't have to do that afterwards...and by extension have the same functionality on the catalog edit screen.
> 
> I can also start looking at some of the other bugs I've written...

first draft up now.
https://github.com/ampache/ampache/wiki/catalog-filters

i'm moving onto 5.4.1 now and will come back to develop after that

**Comment by troycarpenter** [comment]
That looks good.  I like that you converted the private catalog to the new system automatically.  Unfortunately it was an afterthought for me.  Good job there.

**Comment by lachlan-00** [comment]
> That looks good. I like that you converted the private catalog to the new system automatically. Unfortunately it was an afterthought for me. Good job there.

replace a feature i like to make sure there's an easy way to move everyone on to the new one, it's just polite! :)

**Pull request merged**
