### PR TITLE
Some link are generated with &amp; instead of &

### PR DESCRIPTION
**Pull request by fufroma**
Some browser convert successfully, but crawlers aren't

### CODE REVIEW

**Comment by lachlan-00** [comment]
is that specific for links? (<a>)
There are 44-80 links that could be affected by just checking with a regex like `<a.*&amp;` or just `&amp;`

**Comment by lachlan-00** [comment]
@fufroma should i update all these <a> links where i've found &amps? or was this specific to these rows?

**Comment by fufroma** [comment]
I think we must update all of them, but I didn't had the time to test it.

**Comment by fufroma** [comment]
Work done in da6978ebf42bcd4a8bde747c586f6cc30de7e01b

**Pull request merged**
