### PR TITLE
General translation update

### PR DESCRIPTION
**Pull request by Psy-Virus**
Just another general translation update

:-)

### CODE REVIEW

**Comment by Psy-Virus** [comment]
I decided to also push a cs-fixer-commit. I didn't merge it with the translation commit, so you can merge the translation commit but not the formatting commit, if it's not okay.

:-)

**Comment by Phyks** [comment]
Ok, I was puzzled because https://github.com/ampache/ampache/pull/1269 should have handled the cs-fixer things and we should get back on our feet concerning the codestyle. But apparently it was not the case and Travis-CI was still complaining.

It turns out PHP-CS-Fixer had [a bug in version 1.11.4](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases) which I was using when I started to work on the above PR and did not change afterwards. Version 1.11.6 has a fix and indeed gives all the Travis warnings.

So, :+1: for the PHP-CS-Fixer commit, and sorry for missing it in my previous PR =(

**Comment by Psy-Virus** [comment]
> Phyks changed the title from General tranlation update to General translation update 2 days ago

I really made a typo? O.o I think I've written the word to often :-D

> So, :+1: for the PHP-CS-Fixer commit

Whohoo :grinning: 

Don't be sorry, you filled my lack of brain cells and I filled yours. We're even.^^

:-)

**Comment by Phyks** [comment]
:)

**Comment by Afterster** [comment]
Thanks! :smile:

**Pull request merged**
