### PR TITLE
Display flag/fav alongside star ratings

### LINKED ISSUE #2797: [Feature Request] Small Layout Tweak to optimize use of screen space
## Describe what you don't like about Ampache, or what it is missing

I would like to move the heart icon to the same line as the ratings while browsing albums, artists, etc
The reason for this request is to just make a little bit better use of the screen space.
Here is an example I did in Gimp:

## Describe how you would like the feature to work**

This could be the new default, or there could be a setting for compressed layout or something to that affect.

### PR DESCRIPTION
**Pull request by mitchray**
Fixes #2797 

So many edits for such a small change... in most places the flag/fav now appears next to the star ratings (didn't bother changing definition lists)

- Rating::show method has been edited slightly to optionally output global/average ratings
- Condensed the average rating display to accommodate the heart icon being adjacent

firefox_KSU2UwemwN

firefox_dmQ4qvF3rV

firefox_bUoPKUeCWJ

### CODE REVIEW

**Comment by mitchray** [comment]
Since its editing so much I'm going to refactor further

**Comment by lachlan-00** [comment]
good change to focus on though, it's a really odd old feature

**Comment by usox** [comment]
> Since its editing so much I'm going to refactor further

Afraid of that :laughing:

**Comment by mitchray** [comment]
Decided to abandon the refactoring, settled for a cleanup

**Comment by lachlan-00** [comment]
i wasn't following this for a while, was there any more you want to do here @mitchray ?

**Comment by mitchray** [comment]
Nope ready to rock and roll!

**Comment by xekon** [comment]
Beautiful! Thank you so much for your work on this!

**Pull request merged**
