### PR TITLE
Add random_albums API method

### PR DESCRIPTION
**Pull request by AshotN**
Returns random albums from the user.

### CODE REVIEW

**Comment by lachlan-00** [comment]
stats already gets random albums?

**Comment by lachlan-00** [comment]
in master the api only searched for songs but in develop i put in album and artist
image

**Comment by AshotN** [comment]
I did not notice stats, I guess the name of it really didn't give me the impression. I should've searched for ::get_random 

I guess we can close this out

**Comment by lachlan-00** [comment]
We could alias it out but i did the same thing before i realised stats already did it for songs

**Comment by AshotN** [comment]
I think an alias would be nice, wouldn't really require much code. 

I changed my code to `stats` worked exactly the same, cool. 
image

**Comment by lachlan-00** [comment]
if something like that caught you up i think it's a good idea. being able to think of the action you want and actually find it would be beneficial for others.

**Pull request closed without merging**
